### ISSUE TITLE
RAS update via Add-ons Manager (Github version)

### ISSUE THREAD

**Issue by ldgbc** [dillbyrne/random-agent-spoofer#114]
Update can only be done using build found here: https://github.com/dillbyrne/random-agent-spoofer/releases

Make it so that update can be done using Firefox Add-on's Manager. The guys over at RequestPolicyContinued know how to do it should you need any help.

**Comment by deqoksijnc** [comment]
Autoupdate can be done but I am not so sure I would want to have anything autoupdated from github.

**Comment by dillbyrne** [comment]
I can add an option to check for updates on startup and notify the user. If there is an update it will open the latest release page where the user can choose to download it themselves and 
can manually verify the checksums before doing so. 

This would of course be optional

@ldgbc @deqoksijnc  would this be sufficient ?

**Comment by dillbyrne** [comment]
RAS now has the option to check for updates on startup, which is enabled by default but can be disabled and an additional option to download the update automatically which is
 set to disabled by default. 

When the automatic download option is disabled, the latest release page is
opened instead in a new tab where the user can manually verify the download.

When the automatic download option is enabled the user will still see the Firefox addon install prompt after the addon has been downloaded and before the new version can actually be installed.

The options can be set in the about addons page seen in the screenshot below.

![ras_update_prefs](https://cloud.githubusercontent.com/assets/2903711/6098317/7784401a-afd2-11e4-96d2-5a5640079fef.png)

**Comment by dillbyrne** [comment]
I still have to add the translations for the new strings added when implementing this.

**Comment by dillbyrne** [comment]
I found out how to update using the built in update mechanism. https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx#updateURL_and_updateLink

So I will remove my custom solution and use the built in one. The built in update system supports code signing too so it is the better option.

**Comment by scorpiszter** [comment]
Hello master.
Can you update for Choose A Browser Profile :  Random (Mobile Only)?
Thank's You.

**Comment by dillbyrne** [comment]
Hello @scorpiszter I have opened a new issue for your request #148 . You can track it's progress there. I will get to it when I can. If you have anything more to say please use that issue. I will be deleting your comment on this issue as it is not related to this issue.

**Comment by dillbyrne** [comment]
Just a quick update on this issue. I have tried using the built in update mechanism  on a test branch but I was unable to get it to work. I will try again soon and update this issue when I know more.

**Comment by dillbyrne** [comment]
Closing this as the full version is now back on AMO
