### ISSUE TITLE
Disable "mouse context menu"

### ISSUE THREAD

**Issue by ldgbc** [dillbyrne/random-agent-spoofer#115]
It seem like you remove the ability to "Right click" on RAS Icon which Version 0.9.4.3 allow user to Enable/Disable RAS and it was moved to the Mouse Context Menu.

Wouldn't it be better if the same menu come up when Right clicking on RAS and (optionally) Mouse Context Menu can be disable/enable.

**Comment by dillbyrne** [comment]
ldgbc There is no right click with the action button or toggle button that replaced the widget. That is why I added the context menu. I would have preferred to keep it as it was. The context menu is not needed as all the settings can be changed in the tabs.  I added the context menu for convenience. 

I can add an option to disable the context menu in a future update.

**Comment by dillbyrne** [comment]
@ldgbc 

>You mean right clicking will popup with context menu such as
"Move to Menu
Remove from Toolbar"?

Yes the firefox devs no longer allow a click listener to use the right click. Those addons are still using the old Widget. You can see this with the [Linkificator addon](https://addons.mozilla.org/en-US/firefox/files/browse/288088/file/resources/linkificator/lib/controler.js#L477) you mentioned.


The past few versions of the sdk have been showing warnings when the widget is used and it will be removed soon. The widget was the cause of some icon related issues that the new australis buttons solve.

Would you still like an option to disable the context menu ?

**Comment by ldgbc** [comment]
That make sense. Yes, I would appreciate that option.

**Comment by dillbyrne** [comment]
I have added the option to show or hide the RAS context menu entry. When the next version of RAS is released you will find the option under the preferences in the addons screen as shown in the images below. I put it there as it is not likely to be used as frequently as the options in the panel. 

![115a](https://cloud.githubusercontent.com/assets/2903711/5765072/8ec66e98-9cee-11e4-8444-ef1a91313875.png)
![115b](https://cloud.githubusercontent.com/assets/2903711/5765073/8ef70d8c-9cee-11e4-9a4f-b55803b790bd.png)

**Comment by ldgbc** [comment]
I'm curious, why did you use to the "new" widget? Is it some kind of e10s requirement?

**Comment by dillbyrne** [comment]
I used the new action button because the widget is going to be removed from the sdk in the future and the widget was causing problems for some users with icons not showing.

**Comment by Faberman** [comment]
I've just installed the GitHub version of RAS, but I can't find the option to hide context menu entries. Firefox 37.0.1.

<img src="http://armarium.org/u/2015/04/12/b3c8c145cc38886bff3795710ab7e329.png" border="0">
