### ISSUE TITLE
big toolbar icon

### ISSUE THREAD

**Issue by heforfree** [dillbyrne/random-agent-spoofer#116]
i installed Version 0.9.5.0 and i see toolbar icon is to big and not like older version
can you restore it?
![1420190205767](https://cloud.githubusercontent.com/assets/2247864/5595060/f1573464-927d-11e4-89a8-31bc1ad1379e.png)

**Comment by dillbyrne** [comment]
@heforfree Thanks for the bug report can you please tell me what version of firefox you are using and what platform and any addons you are using

**Comment by heforfree** [comment]
hello,sure
Software:Firefox 34.0.5 (20141126041045)
OS:WINNT (x86-msvc) windows 8.1 update1

-Add-ons Manager Context Menu 0.4.2
-Addon List Dumper (restartless) 0.1
-Australis Small Icons 1.0
-Bookmark Quick Mover 0.2
-Clear Console 1.11
-CookieKeeper 1.7.4
-DblClicker 1.7.6
-Download Panel Tweaker 0.2.2
-Easy Copy 2.5.2
-FireCaptor 0.1.8.1
-GlobalFindBar 1.0
-Greasemonkey 2.3
-IDM CC 7.3.88
-IPvFox 0.8.6
-Manage Folders 1.0.5
-Menu Filter 6
-NoClick 2.7
-Paste and Search (Forms) reloaded 0.0.2
-Policeman 0.16.1
-Pop-up Controller 0.7
-Private Tab 0.1.7.3
-ProfileSwitcher 1.6.2
-Random Agent Spoofer 0.9.5.0
-RefControl 0.8.17
-RefreshBlocker 0.8
-RoboForm Toolbar for Firefox 7.9.11.1
-S3.Google Translator 3.06
-SSL Version Control 0.4
-Stylish 2.0.0
-Tab Focus 1.0.8
-URL Focus 0.0.1
-Yet Another Remove It Permanently 0.3.4
-Zorcher 0.4.3.0.2
-url-addon-bar 0.2.4

**Comment by dillbyrne** [comment]
@heforfree Thanks I'll have a look and get back to you when I have something

**Comment by dillbyrne** [comment]
@heforfree can you tell me if this version makes any difference ? . If not can you try the addon on its own in a fresh profile to see if it still happens ? https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by heforfree** [comment]
ok now i tested on new profile,and work fine but seem not work with url-addon-bar  addon

**Comment by heforfree** [comment]
but working with and older version

**Comment by dillbyrne** [comment]
I updated the test release link above. Pasted the wrong release by mistake. The older version was using the widget code and that code has been depreciated and I have to move to the new ActionButton to replace the widget.

**Comment by heforfree** [comment]
still big with below link
https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.1-beta1

**Comment by dillbyrne** [comment]
@heforfree did  https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.1-beta1 make any difference

**Comment by dillbyrne** [comment]
@heforfree I'll see if there is anything else I can do but It sound like it is a problem with the other addon. In the test version above I forced 16x16 icons to be used so it should have fixed any issues if RAS was the cause, considering it works fine on its own.

**Comment by dillbyrne** [comment]
I tried the url-bar-addon and it worked on my system but RAS was not added to the url bar. The icon was the correct size.

perhaps it could be the small australis icons addon causing the issue https://addons.mozilla.org/en-US/firefox/addon/australis-small-icons/reviews/626342/

**Comment by heforfree** [comment]
select customize put RAS  icon in url-bar-addon toolbar exit customize it change to big
tested with small australis icons too but not for that.
and i back to Version 0.9.4.3 and work fine and as you say i see depreciated in ctrl+shift+j
https://gist.github.com/heforfree/a8e4637589465885554c

**Comment by dillbyrne** [comment]
@heforfree I tried selecting customize to move the RAS icon to the url-bar-addon but the url-bar is greyed out and will not allow me to drag the RAS icon or any other icon such as the built preferences icon to it either.

**Comment by heforfree** [comment]
it is work fine for me.
Version 0.9.4.3
![image 1](https://cloud.githubusercontent.com/assets/2247864/5596199/8f2b9ce2-929d-11e4-90b1-2cd0be61d04b.png)

test version in customize icon is normal after exit icon change to big
![image 2](https://cloud.githubusercontent.com/assets/2247864/5596208/b4b64c14-929d-11e4-8512-a7b4abc574c9.png)

**Comment by dillbyrne** [comment]
I have managed to reproduce the issue on windows 7 with the url-bar-addon and RAS. I'll see if there is anything I can do and get back to you.

**Comment by heforfree** [comment]
keep this open for some days to see if someone else have my problem or not
so if not i will try contact with url-bar-addon developer
thank you

**Comment by dillbyrne** [comment]
@heforfree Sure no problem. I'll let you know if I manage to find a fix but as I said the only code in RAS related to the icons is all standard code which you can find on the mozilla site itself. I don't do anything out of the ordinary with the icons that I can see causing such an issue.

**Comment by dillbyrne** [comment]
@heforfree I have check this with other addons using toggle/action Button and it happens for all of them. The addons included addons by myself and other developers. As a result I can safely say this is not an issue with RAS.

**Comment by heforfree** [comment]
i put an review for url-bar-addon
thank you for Attention

**Comment by dillbyrne** [comment]
@heforfree Sure. It is not specific to this addon though it seems to be addons using the ActionButton or ToggleButton so it may be worth mentioning that instead so the developer is more informed.

For example it happens with https://addons.mozilla.org/en-US/firefox/addon/gmail-notifier-restartless

**Comment by heforfree** [comment]
:+1:  thanks updated review.so if you want close this.i hope he look the review :)

**Comment by dillbyrne** [comment]
@heforfree Sure,  no problem. Thanks for supporting RAS.
