### ISSUE TITLE
Add E-TAG protection

### ISSUE THREAD

**Issue by danielcra** [dillbyrne/random-agent-spoofer#122]
I enabled Send spoofed 'If-None-Match' headers (ETags) but
I still get identical e-tags between browser sessions on the page below, although I have disabled cache, DOM and history in RAS and I clear my cache through FF prefs. upon exit.

http://ip-check.info/?lang=en

RAS version 0.9.5.0, FF 34

**Comment by dillbyrne** [comment]
@danielcra the if-none-match header takes a function call as a paramater which when called returns random data. There is no variable to store the data so there is no way it could persist between between requests so it is not possible that it could be the same. 
ip-check.info does not check for Etags. It is simply displaying the spoofed header you are sending each time. 

If you want to actually test etags and see the spoofed header preventing the site from reading the etag see http://lucb1e.com/rp/cookielesscookies/ 

The [User Manual](https://github.com/dillbyrne/random-agent-spoofer/wiki/User-Manual) explains the options in RAS and how they work. I recommend you to take a look if you have not done so already.

There are 2 methods in RAS to block etags. One is to send the spoofed if none match header and the other is to disable the browser's cache.

**Comment by danielcra** [comment]
Interesting. I tried the following to verify the issue:
- Created a new FF profile on same machine, installed same ras 0.9.5, activated only the "if-none-match" header option, and loaded http://ip-check.info/?lang=en. Result: *different* e-tag every time.
- Went back to my normal working profile, uninstalled RAS, installed same ras 0.9.5, activated only the "if-none-match" header option, and loaded http://ip-check.info/?lang=en. Result: *same* e-tag every time.

So it must be something in my FF profile that differs from the default and makes the etags sticky despite using RAS. Any idea what it could be?

BTW: Storing text on http://lucb1e.com/rp/cookielesscookies/ does *not* work with either of the two profiles, if RAS is active.

**Comment by dillbyrne** [comment]
RAS gets a random value and sends it for the if-none-match header. It is not stored anywhere and changes per request as I mentioned above . It sounds like it has to be something with your browser specifically. I'm not sure what could be causing it. 

Text will not be stored if the cache is disabled. From 0.9.5.1 onwards it is disabled by default to fix #121 . The current cache method in extras does the same thing but operates on different firefox cache prefs but it seems the network.http.use-cache pref achieves the same result so the current cache option is kind of redundant now that it is forced by default. It is useful only for the AMO versions now.

**Comment by danielcra** [comment]
I am still investigating this. Problem is still reproducible with the latest 0.9.5.1 version. I get identical ETAGs between browser sessions although RAS option "if-none-match" is ON.

As I said I suspect this is something in my browser profile. I tried disabling all other extensions and plugins, but no change. I looked through FF options related to cache that were different from their defaults, but found nothing suspicious either.

**Comment by danielcra** [comment]
Could this be related to proxying...if the proxy does caching?

Interesting also that I get identical etags here http://ip-check.info/?lang=en
but not here: http://noc.to/ (under zombie cookie)

**Comment by danielcra** [comment]
I now brought the computer to a network where I can connect to the Internet without proxy.
Without changing anything else, I now get a *different* ETAG on every reload of the page above.
So problem is in fact related to the proxy.
I guess there is nothing that FF or RAS can do about it.

(Reason why problem was gone with a new profile is that a different proxy got used.)

**Comment by dillbyrne** [comment]
@danielcra Thanks for following up on this. I'm glad you found the cause of it.

**Comment by Mosrite** [comment]
Apparently, ipcheck.info recognizes that the If-None-Match header was modified. Therefore, the browser fingerprint will be more unique. Could this maybe be implemented in a non-discoverable way?
