### ISSUE TITLE
http basic auth fails

### ISSUE THREAD

**Issue by RaymiiOrg** [dillbyrne/random-agent-spoofer#123]
With this extension enabled every website that uses http basic auth fails to login. When added to the whitelist the basic auth works again.

Not an issue for me, but why is this?

**Comment by dillbyrne** [comment]
Hello @RaymiiOrg The option `Disable Authorization header` on the headers page disables basic authentication. Once that is unticked sites should work. I had a whitelist option for it before but It was not working as expected. So the whitelist in this case should not make a difference if the option is still checked. It sounds like its a bug.

Can you post some sites you have experienced this on so I can test it please ?

**Comment by RaymiiOrg** [comment]
Howdy @dillbyrne,

The `Disable Authorization header` option seems to be unticket by default. After ticking it and unticking it , basic auth works on websites that are not on the whitelist. (I only have work or private related sites behind firewalls, but any apache basic auth will do). When the option is ticked websites on the whitelist still work but sites not on the whitelist don't.

For me it is solved by ticking and unticking the option.

**Comment by dillbyrne** [comment]
@RaymiiOrg Thanks for reporting this. It definitely sounds like a bug. Thanks for reporting it. I will update the issue when I have had a chance to look into it and fix it.

**Comment by floalma** [comment]
Hi,
Can't work with instagram, even with my real profile. I can't login. Disable authorization header was disabled too.

**Comment by floalma** [comment]
Hi Dillbyrne,

It doesn't work with the following site, even with my real profile and with Disable Authorization header unchecked. Please check it : https://web.skype.com/

Hope you can fix it soon
