### ISSUE TITLE
TorButton-like behaviour

### ISSUE THREAD

**Issue by Kagami** [dillbyrne/random-agent-spoofer#130]
Hi. Thanks for great plugin.

While RAS provide a lot of options to tune your browser fingerprint, it's rather difficult (especially for non-advanced users) to set it up to make your browser non-unique. Also as was mentioned in #90 it would require constant manual tuning because browser trends are change from time to time.

So what do you think if RAS would provide option out-of-the-box to make your browser non-unique as much as possible using fine-grained maintaned settings?
As I can find, RAS is the only extension for Firefox that provides a lot of settings of such kind. Other extensions provide UA and timezone settings only at best. TorButton [is not supported anymore](https://www.torproject.org/docs/torbutton/) unfortunately and [Chameleon](https://github.com/ghostwords/chameleon) is only available for Chrome/Chromium.

Thanks.

**Comment by dillbyrne** [comment]
Hello @Kagami  

Panopticlick is out of date so while it is useful I would not be relying on that for a true test of uniqueness. The main things contributing to uniqueness in the case of RAS are the date and timezone strings, on which I still have more work to do and the fonts, or lack of fonts I should say as we use a limited subset for now.

The thing about the fingerprint is that it is only useful until the profile changes again. Then a brand new fingerprint would be generated. 

I have lots more to add to RAS including new features and improvements to existing ones. I'm in the process of moving right now so I have to wait until I get that out of the way and I can get back to it.  

I will add a torbrowser profile to RAS . Although If you want that profile it is better to use the real thing.

**Comment by Kagami** [comment]
Yea, I'm fully aware that for real anonimity only TBB should be used. I'm just thinking that it still be useful to make your "normal" browser profile less unique and trackable.

**Comment by dillbyrne** [comment]
A tor browser profile has been added as firefox 31 ESR.  The fonts will be different on the tor browser but it is as close as I can get for now with RAS.

**Comment by Kagami** [comment]
Thanks! Should this issue now be closed?

**Comment by dillbyrne** [comment]
@Kagami sure I'll close it now
