### ISSUE TITLE
cleverer random switching

### ISSUE THREAD

**Issue by deqoksijnc** [dillbyrne/random-agent-spoofer#131]
Timer based switching is useless or even counterproductive if the remote server can track us by other means.

Most importantly, while there are still tabs open for a domain the remote side has many easy possibilities to track us:
* cookies
* javascript storing data and doing remote requests or adding cookies

Fighting this  might be doable like this:
(1) sync cookie deletion and other spoofing measures
(2) switch agent (and other spoofable things) independently for groups of tabs belonging to a certain "domain", preferably when the last tab tied to a certain domain is closed. Domain would be defined as related sites which are likely to share tracking information.

I realize that  (2) is a herculean if not impossible task - requires keeping track of all server which a webpage contacted and cookies originating from servers.

**Comment by dillbyrne** [comment]
@deqoksijnc It depends on how you browse. I deny cookies by default but I am well aware that is it not the default behaviour for most people.

1) I have plans to add cookie options to RAS . I plan to delete cookies as soon as the user is done with them and have a block all option with the ability to whitelist specific cookies.

2) Per tab profiles is not currently an option. I tried it before and the overhead from all the checking involved in different places significantly slows down browsing time. Also it is very difficult to get right with concurrent connections and different profiles such as desktop and mobile.

When firefox moves to a multiprocess architecture I can perhaps revisit it and see if it would be possible but for now it is not.
