### ISSUE TITLE
Date picker not working

### ISSUE THREAD

**Issue by evdw87** [dillbyrne/random-agent-spoofer#132]
Hi, whenever I have time zone spoofing enabled with other than the default setting, the date picker (arrival date and departure date) on http://www.hotels.nl/ fails. Any clue?

**Comment by dillbyrne** [comment]
Hello @evdw87 . Sorry about the delay in getting back to you. The current date spoofing code needs a lot of work and is in the very early stages. it is currently only updated per request so when a page is loaded we send a fake date which is used is all calls to the date object. This is why I suspect the date picker is breaking it is trying to load different dates for the picker and it is not working and causing it not to show. 

You can add the site to the whitelist with the date whitelisted or temporarily use the default date on that site. 

I have an issue open to improve the date code. #66 So you can keep track of the progress there and I'll close this issue as it is a duplicate.
