### ISSUE TITLE
Whitelist option for authorization header

### ISSUE THREAD

**Issue by letorbi** [dillbyrne/random-agent-spoofer#141]
Hej,

is there an option to allow authorization headers on certain sites? The wiki says that there are the options `referer`, `xff`, `via` and `ifnonematch`, but nothing like `authorization`.

It would be really nice to allow authorization headers on certain sites. For example to make Firefox Sync work again (see also #92).

Bai
Torben

**Comment by dillbyrne** [comment]
@letorbi There was initially support for the authorization header which was implemented exactly as in your patch but It didn't work in my tests so I took it out but now that I think of it I probably didn't whitelist one of the urls required for it to work .

I have merged your patch. Thanks @letorbi

**Comment by letorbi** [comment]
Thanks for the fast merge :+1:
