### ISSUE TITLE
option for per-site user agent switcher (per each site (domain).

### ISSUE THREAD

**Issue by Monessem** [dillbyrne/random-agent-spoofer#144]
maybe this one of the best user agent switcher for Firefox but i think missed per-site agent switcher (per each site (domain).
to open some service work with other browser like Google inbox , whatsapp web
B.W

**Comment by copywrong** [comment]
+1

Sometimes people don't want to spoof user-agent in some websites.

**Comment by dillbyrne** [comment]
@Monessem @copywrong that is what the whitelist is for, It allows you to define what the whitelist profile is and is set to a recent version of firefox by default for maximum compatibility. 

As I have stated elsewhere I will not be adding per site profiles. The reason for this is that I tried it already and it slows down page loading to a crawl. As RAS is not simply changing a user agent there are lots of checks to do. The headers, the javascript injection values and the internal firefox preferences.  Each of these checks add overhead to the page loads and the more checks involved the longer the page takes to load. Also mixed requests can have unpredictable results when some requests of a page are requested by a mobile and others by a desktop.

You can either exclude problematic profiles, whitelist the site or compile a custom version with your own profiles which I will help you with should you desire.
