### ISSUE TITLE
Feature Request-Option to add custom useragent

### ISSUE THREAD

**Issue by drake1989** [dillbyrne/random-agent-spoofer#145]
There should be an option to use a custom user-agent if we want our useragent to stay the same for each session along with the option to change it per session and cycle through each presets. There should be a feature where it spoofs browser sizes and resolutions with each session that would make this addon awesome.

**Comment by dillbyrne** [comment]
Hello @drake1989  There is already an issue open for this #61 . Closing this as it is a duplicate

If you want it to stay the same then pick a specific one from the expandable lists. It already does spoof the screen resolution.

**Comment by drake1989** [comment]
ok dillbyrne i understand, if u ever do make an update pls try to add random ip changer so it hides your real ip and spoof your browser window size not just your screen resolution size and an option to choose which country to appear your ip is from that would be great, this is still a great plugin btw.

**Comment by dillbyrne** [comment]
Thanks @drake1989 .

I will not be adding IP spoofing because it is beyond the scope of this addon. You will need to route your connection through a different location to hide your IP. I can add an option to set proxy settings if you would like but you will have to provide your own proxy.

If you want to protect your IP address look at https://torproject.org

**Comment by drake1989** [comment]
hi dill can you please add an option to spoof browser size i know you added
spoof screen resolutions which is great.

**Comment by dillbyrne** [comment]
@drake1989 I have responded to your query in the other issue. Please stick to that issue and stop posting in other issues that have nothing to do with what you are asking.
