### ISSUE TITLE
detecting real ip

### ISSUE THREAD

**Issue by drake1989** [dillbyrne/random-agent-spoofer#146]
Addon does a good job spoofing ip on most sites but not on this site http://whatismyipaddress.com/ this site will detect your real ip hope admin can fix this and also add an option to spoof browser size and resolution.

**Comment by dillbyrne** [comment]
@drake RAS is not supposed to hide your IP address the XFF and VIA headers are related to routing. This is explained in the [user manual](https://github.com/dillbyrne/random-agent-spoofer/wiki/User-Manual#headers-tab-options)

**Comment by drake** [comment]
wrong drake... @drake1989 and not me :)
