### ISSUE TITLE
Window.name breaks Youtube comments --> Add to default whitelist?

### ISSUE THREAD

**Issue by Mosrite** [dillbyrne/random-agent-spoofer#147]
I just figured out that protecting window.name breaks Youtube comments. While it is easy to set up a whitelist entry it took me a while to find the cause for this problem.
Maybe you could add window.name for Youtube to the default whitelist?
--> {"url":"youtube.com","options":["canvas","windowName"]}

**Comment by dillbyrne** [comment]
@Mosrite I added it. Thanks for the help :+1:

**Comment by Mosrite** [comment]
Same goes for pictues (and fonts?) of the Play Store web app:
{"url":"play.google.com","options":["windowName"]}

**Comment by dillbyrne** [comment]
@Mosrite I'll update the default whitelist again soon

**Comment by dillbyrne** [comment]
@Mosrite fonts not displaying would be due to using the standard font set which does not have fonts for certain icons.  The profile influences the pictures as google forces webp for webkit based browsers.

What is the "windowName" option added for ? it does not make any difference to the pictures or fonts. I don't have an account so I'm guessing it is comments ?

**Comment by Mosrite** [comment]
I don't have the font limiting setting enabled. And I'm not logged in either. I just use the Play Store web app occasionally to look up some apps.
Fonts and images weren't viewed properly and this changed when I created a window.name whitelist entry for the Play Store. But maybe it was mere coincidence. If you cannot reproduce it, don't add it to the default whitelist.

**Comment by dillbyrne** [comment]
Hello @Mosrite when you said window.name breaks comments on youtube, was that for posting , viewing or both ?

I'm about to release  0.9.5.2 and as I'm testing it I can view comments fine on youtube with only canvas whitelisted. I don't have a google account to post which is why I'm asking.

**Comment by Mosrite** [comment]
No, I'm just talking about viewing, I never comment myself.
Apparently,  RAS leads to some issues on my PC that aren't reproducible. So, you shouldn't care about them at the moment.

**Comment by dillbyrne** [comment]
Thanks for getting back to me so quickly, I appreciate it. It could be the update to the script injection code which is responsible for it. In any case it does not seem needed now.
