### ISSUE TITLE
Notifications are not always displayed on FF36

### ISSUE THREAD

**Issue by dillbyrne** [dillbyrne/random-agent-spoofer#149]
I need to investigate this further to find the cause. The error messages listed in this [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1130830) are present but I am not sure if they are related to this notification issue .

**Comment by dillbyrne** [comment]
This issue does not occur on windows 7 with firefox 36 with the current stable version of RAS. It happens on linux. I suspect it is due to a change in how the notifications are  displayed on linux. 

I will need to investigate this further.

**Comment by dillbyrne** [comment]
While trying to find the exact cause of the issue I found out that removing the notification icon will result in the notifications being displayed all the time. I have temporarily removed the notification icon for now in the last commit until a better fix can be found

**Comment by heforfree** [comment]
blank white space show for me in windows 8.1 update3
https://gist.github.com/heforfree/9c09a35b8563ed49ca9f

also big icon #116 problem seems fixed in ff36

**Comment by dillbyrne** [comment]
Hello @heforfree 

Thanks for the bug report. 

When you say RAS popup do you mean the panel when you click on  an icon or do you mean the notifications ?

**Comment by heforfree** [comment]
hello
when i click on an icon toolbar

**Comment by dillbyrne** [comment]
@heforfree Thanks for clarifying. Is this with version 0.9.5.1 ?
I don't have windows 8.1 on hand to test it but I'll try to fix it for you soon.

**Comment by heforfree** [comment]
yes it is 0.9.5.1
thankyou very much

**Comment by dillbyrne** [comment]
@heforfree No problem. I'm a bit busy for the next few days but I'll try to have a test release ready for you soon to see if it fixes the issue.

**Comment by dillbyrne** [comment]
Hello @heforfree 

Was it working fine for you before the windows update ?

Can you try 0.9.5.1 in a [fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) so I can see if it is a problem with that version in its default state ?

**Comment by heforfree** [comment]
hello
no problem in new profile,i dont use windows update i used MSMG ToolKit to update iso image
i disabled some addon,after disable some addon i try to enable one by one each of them
and after enable policeman,RAS show blank popup,but with Ras and police man on new profile both working

https://addons.mozilla.org/en-US/addon/policeman

**Comment by dillbyrne** [comment]
@heforfree I'll try RAS and policeman and see if I can replicate the issue and get back to you

**Comment by heforfree** [comment]
i see this log too
https://gist.github.com/heforfree/b13e6a94cf548ab1b296

**Comment by heforfree** [comment]
the same thing happen too Addon List Dumper (restartless) 0.1

Software:Firefox 37.0.1 (20150402191859)
OS:WINNT (x86-msvc)

-Add-ons Manager Context Menu 0.4.2
-Addon List Dumper (restartless) 0.1
-Australis Small Icons 1.0
-Bookmark Quick Mover 0.2
-Bypass Forced Download 0.0.1
-Clear Console 1.11
-CookieKeeper 1.8.5
-DblClicker 1.7.6
-Download Panel Tweaker 0.2.3
-Easy Copy 2.5.2
-FireCaptor 0.1.9.0
-Form History Control 1.4.0.3
-Greasemonkey 3.1
-IDM CC 7.3.99
-Manage Folders 1.0.5
-Menu Filter 7
-NoClick 3.1
-Paste and Search (Forms) reloaded 0.0.2
-Pop-up Controller 0.9
-Private Tab 0.1.7.3
-ProfileSwitcher 1.6.2
-Random Agent Spoofer 0.9.5.1
-RefControl 0.8.17
-RefreshBlocker 0.8
-RoboForm Toolbar for Firefox 7.9.11.1
-S3.Google Translator 3.09
-SSL Version Control 0.4
-Stylish 2.0.2
-Tinfoil 0.7
-Web Paste & Go 1.1
-Yet Another Remove It Permanently 0.3.4
-Zorcher 0.4.3.0.2
-url-addon-bar 0.2.4

**Comment by dillbyrne** [comment]
@heforfree can you try 0.9.5.2 and tell me if that works for you.

It sounds like it is one of your addons cause issue. Since RAS worked on its own it is not RAS specific. Also https://gist.github.com/heforfree/b13e6a94cf548ab1b296#file-ras2-L17 is the addon list trying to use the widget module which is now obsolete in the addon sdk.

**Comment by heforfree** [comment]
hello
on same profile dont work but clean profile working.so if you want close it seems you can not do anything about it.
https://gist.github.com/heforfree/40e0d497c3bc3bbaa961

**Comment by dillbyrne** [comment]
This issue is tracking the notification image issue so I'll keep it open. It could be that the profile has become corrupted or else it is another addon interfering with it as it works on its own in a fresh profile and no other users have reported a similar issue.

My suggestion would be to use a new profile. If you do decide to use a new profile let me know if the issue crops up again. Other than that there is not much I can do as I can't reproduce it.

**Comment by paulderdash** [comment]
Using RAS 0.9.5.3 on Windows 7 SP1 Pro 64-bit and Windows 8.1 Pro 64-bit. Both with Firefox 38.0.1.
Notification appears when randomly switching browsers on Win 7, but not on Win 8.1. I do have quite a lot of add-ons in both environments, but as far as I know they are the same.

**Comment by dillbyrne** [comment]
Hello @paulderdash  Can you confirm if  a notification shows when you start the browser ?  it should show your starting profile as well as when it is changed . Assuming notifications have not been disabled.

**Comment by paulderdash** [comment]
Hi @dillbyrne - it does show notification on browser start ... there was never a problem. My mistake.

**Comment by dillbyrne** [comment]
@paulderdash Good to know thanks for your reply.

**Comment by heforfree** [comment]
it is fixed on my profile that not working in firefox 38.0.5
so very well
thanks
