### ISSUE TITLE
hello sir

### ISSUE THREAD

**Issue by magicraja** [dillbyrne/random-agent-spoofer#155]
@dillbyrne  - hello sir ..... v glad to find ur add-on . im no expert on coding or programming but your creation is so good for it's purpose ,  invoked me to write 2 lines. Gratitude and thank you .  
I have couple of question and wondering if  could ask you .  My ICQ - 687041710  & Jabber -  magicraja@im.hot-chilli.eu.
bit addrs. copied.
cheers

**Comment by dillbyrne** [comment]
Hello @magicraja I have listed my contact details in the contact section of https://dillbyrne.github.io/ 

It contains my dev XMPP address and it's  OTR key fingerprint. I have added your account above as a contact.

**Comment by magicraja** [comment]
hello sir ,

this is my otr - ED7B21EA BADA3234 9D8FE231 32EF2EB5 D887B303 ..... thank you.
