### ISSUE TITLE
Valve Steam in-game browser for linux

### ISSUE THREAD

**Issue by fredsteel54** [dillbyrne/random-agent-spoofer#156]
here's data from the Valve Steam in-game browser currently running on ubuntu 64bit (desktop)

navigator.appName	Netscape
navigator.appCodeName	Mozilla
navigator.appVersion	5.0 (Linux; U; X11; en-US; Valve Steam GameOverlay/1424305157; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.86 Safari/537.36
navigator.appMinorVersion	Property is not supported! navigator.appMinorVersion is not a string. It's a undefined
navigator.vendor	Google Inc.
navigator.userAgent	Mozilla/5.0 (Linux; U; X11; en-US; Valve Steam GameOverlay/1424305157; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.86 Safari/537.36 . More info...
navigator.oscpu	Property is not supported! navigator.oscpu is not a string. It's a undefined . More info...
navigator.platform	Linux x86_64
navigator.securityPolicy	Property is not supported! navigator.securityPolicy is not a string. It's a undefined . More info...
navigator.onLine	true . More info...
Info browser.name	chrome
Info browser.version	35.0.1916.86
Info layout.name	webkit
Info layout.version	537.36
Info os.name	linux
Internet Explorer real version	This only works in Microsoft Internet Explorer!
Operating System	Linux/Unix - More info...

----------

Accepted Documents	text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8
Accepted Charsets	Not available!
Accepted Encodings	gzip
deflate
Accepted Languages	en-us
en;q=0.8

----------

Width	60
Height	20
AvailHeight	20
AvailWidth	60
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	0
ColorDepth	0
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

--------

Time and date	Wed Mar 18 2015 21:23:47 GMT-0400 (EDT)
GMT'ed	Thu, 19 Mar 2015 01:23:47 GMT
Locale String	18/3/2015 21:23:47
Time-Zone offset	240 minutes
Milliseconds since January 1, 1970	1426728227000
Internet Beat	@ 99
Time on browserspy.dk server	Wed, 18 Mar 2015 20:23:46 -0500
Time on your PC	18/3/2015 21:23:47
Difference between server and PC time	1 seconds

**Comment by fredsteel54** [comment]
some more data

UserAgent from header	Mozilla/5.0 (Linux; U; X11; en-US; Valve Steam GameOverlay/1424305157; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.86 Safari/537.36
User Agent from JavaScript	Mozilla/5.0 (Linux; U; X11; en-US; Valve Steam GameOverlay/1424305157; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.86 Safari/537.36
Browser string	Google Chrome
Operating System	Linux/Unix
Browser name	Yes - version chrome
Browser version	Yes - version 35

**Comment by fredsteel54** [comment]
Operating System	Linux/Unix
OS detected via jQuery	linux
OS detected via platform	Linux x86_64 - Linux i686 64bit
OS CPU detected via JavaScript	Property is not supported! navigator.oscpu is not a string. It's a undefined

**Comment by fredsteel54** [comment]
oh, I also found this if it helps, they have tons of data:
http://id.furud.net/index.php

**Comment by dillbyrne** [comment]
Hello @fredsteel54 . I'll add this profile into the console browsers section when I get some of the current issues done. It'll be in 0.9.5.2. Thanks for your contribution :+1:

**Comment by dillbyrne** [comment]
Hello @fredsteel54 before I close this can you double check the accept headers and screen size values you submitted above. I ask this because the webkit / Chrome  based browsers generally send `gzip,deflate,sdch` for accept encoding header and this does not match it.

Also the screen size reports 0 for pixel depth and color depth is 0 which is unusual. 

I just want to be sure before I close this, thanks

**Comment by fredsteel54** [comment]
This is weird man, it fluctuates. seems random.

Width	1004
Height	617
AvailHeight	617
AvailWidth	1004
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	0
ColorDepth	0
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

=====

Width	60
Height	20
AvailHeight	20
AvailWidth	60
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	0
ColorDepth	0
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

**Comment by fredsteel54** [comment]
also here's more data. I relaoded the links a few times to see if anything else varied, so far only what i mentioned above fluctuates.

Accepted Documents	text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8
Accepted Charsets	Not available!
Accepted Encodings	gzip
deflate
Accepted Languages	en-us
en;q=0.8
=====
Browser says that it has GZip support?	Yes via gzip
Browser supports GZipped JavaScript?	Yes
Browser supports GZipped CSS?	Yes
=====

HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_ACCEPT_ENCODING	gzip,deflate
HTTP_ACCEPT_LANGUAGE	en-us,en;q=0.8
HTTP_CONNECTION	close
HTTP_COOKIE	__utmt=1; __utma=190908281.1381603815.1426201581.1427248727.1427490895.4; __utmb=190908281.5.10.1427490895; __utmc=190908281; __utmz=190908281.1427490895.4.3.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); __unam=6b6ab6d-14c103d1c97-596c29a8-30
HTTP_HOST	browserspy.dk
HTTP_REFERER	http://browserspy.dk/accept.php
HTTP_USER_AGENT	Mozilla/5.0 (Linux; U; X11; en-US; Valve Steam GameOverlay/1427176184; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.86 Safari/537.36
HTTP_X_HTTP_PROTO	HTTP/1.1

....

=====

Running Google Chrome Browser?	Yes
Google Chrome Version	Yes - version 35
Google Chrome Full version	35.0.1916.86
AppleWebKit version	537.36
Google Chrome Layout Engine Info	Yes - version webkit5
Google Android version	No or unable to detect
User Agent	Mozilla/5.0 (Linux; U; X11; en-US; Valve Steam GameOverlay/1427176184; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.86 Safari/537.36

=====

innerWidth	1004
innerHeight	617
outerWidth	0
outerHeight	0
Offscreen buffering	Property is not supported! window.offscreenBuffering is not a string. It's a boolean
Frame Rate	Property is not supported! window.frameRate is not a string. It's a undefined

=====

ActiveXControls	False
Alpha	False
AolVersion	False
BackgroundSounds	FalseI started up steam and only opened the browser in-game without touching anything else. Here's a bunch of data, I just dumped everything I could find.

Accepted Documents	text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8
Accepted Charsets	Not available!
Accepted Encodings	gzip
deflate
Accepted Languages	en-us
en;q=0.8
=====

ActiveXControls	False
Alpha	False
AolVersion	False
BackgroundSounds	False
Beta	False
Browser	Safari
Comment	Safari Generic
Cookies	True
Crawler	False
CssVersion	True
Frames	True
IFrames	True
JavaApplets	True
JavaScript	True
MajorVer	False
MinorVer	False
Parent	Safari Generic
Platform	Linux
Platform_Version	unknown
Tables	True
VBScript	False
Version	0.0
Win16	False
Win32	False
Win64	False
browser_name	Mozilla/5.0 (Linux; U; X11; en-US; Valve Steam GameOverlay/1427176184; ) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.86 Safari/537.36
browser_name_pattern	Mozilla/5.0 (*Linux*) AppleWebKit/* (KHTML, like Gecko) *Safari/*
browser_name_regex	^mozilla/5\.0 \(.*linux.*\) applewebkit/.* \(khtml, like gecko\) .*safari/.*$
isMobileDevice	False
isSyndicationReader	False

**Comment by fredsteel54** [comment]
ok I kept refreshing it a bunch of times and it seems to be this:

Width	1004
Height	617
AvailHeight	617
AvailWidth	1004
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	0
ColorDepth	0
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

=====

Got a second opinion on that pixel/color depth, 0 seems true:

http://postimg.org/image/jblkkph21/

**Comment by fredsteel54** [comment]
I thought maybe it was some cusomt extension put in by vavle. 
interestingly when I go to:
chrome://extensions/

it redirects to:
chrome://version/

Which dispalys:

Chromium Embedded Framework (CEF)
Copyright © 2015 The Chromium Embedded Framework Authors.
All rights reserved.
license | credits
CEF	3.1916.1692
Chromium	35.0.1916.86
OS	Linux
WebKit	537.36
JavaScript	3.25.28.15
Flash	
User Agent	Mozilla/5.0 (X11; Linux i686 (x86_64)) AppleWebKit/537.36 (KHTML, like Gecko) Valve Steam Client Safari/537.36

 Which is then followed by some file path details on my machine. I'm gussing this is a custom Chromium browser they moded themselves.

**Comment by dillbyrne** [comment]
@fredsteel54 Thanks for double checking. I have corrected the screen size and I'll close this issue now
