### ISSUE TITLE
Microsoft's Internet Explorer's User Agent References

### ISSUE THREAD

**Issue by ldgbc** [dillbyrne/random-agent-spoofer#158]
I recently came across this articles from Microsoft: https://msdn.microsoft.com/en-us/library/ie/hh869301%28v=vs.85%29.aspx

It list many of their product user-agent that you can either (1) User as references to confirm your finding
(2) Copy/paste it rather than install OS and test it yourself.

**Comment by dillbyrne** [comment]
@ldgbc Thanks for this, but I would still have to test it on a real version to make sure all the other attributes have not changed between the versions, such as the headers for example, as the user would stand out if there was a mismatch.  With IE I'll probably only update the current ones RAS has  and eventually add MS's "Spartan" browser in place of IE when it replaces it .
