### ISSUE TITLE
RAS cannot override if fingerprint script before it

### ISSUE THREAD

**Issue by zxzxzx123** [dillbyrne/random-agent-spoofer#159]
removed

**Comment by dillbyrne** [comment]
>Hello,

>As i tested, RAS cannot "override" if ... alright, here is example (not sure it syntax correct):
...(i think RAS will be put here)

>as i known, RAS use appendChild to inject, it will be put after all other scripts
so, browsersize will not change by RAS

>Thank for reading


hello @zxzxzx123 

RAS injects the script before the document has a chance to load anything .
it uses the `start` paramater for  the `ContentScriptWhen` method of the PageMod object which states  


>"start": Load content scripts immediately after the document element is inserted into the DOM, but before the DOM content itself has been loaded

Can you please confirm if you actually were able to read the real values ?
