### ISSUE TITLE
RAS 0.9.5.1 breaks procedure for closing eBay account

### ISSUE THREAD

**Issue by bugreport0** [dillbyrne/random-agent-spoofer#161]
When trying to close a logged-in eBay account via http://cgi1.ebay.com/ws/eBayISAPI.dll?CloseAccount there is a menu to select reason categories for closing the account. Normally, once a category has been selected, another menu should appear to further specify the reason. With RAS enabled, however, the website seemingly does not respond to any category selection whatsoever, thereby breaking the procedure.
I have tried disabling all spoofing and other options, including user agent, yet only disabling RAS itself (by unticking "Enable RAS") solves this problem.

**Comment by dillbyrne** [comment]
Hello @bugreport0 

This sounds like it was the script  injection causing the issue. I will add an option to toggle script injection to the extras and inform users that certain options will not work while it is disabled.

**Comment by dillbyrne** [comment]
@bugreport0 I have added the option to disable script injection #162 . When I get a chance I will test it on a temporary ebay account and see if it allows the account to be closed.

**Comment by bugreport0** [comment]
Thank you. You don't need a temporary account to test this because eBay would as the last step ask you whether you are really sure to close the account, at which point you could abort.

**Comment by bugreport0** [comment]
Thank you. You don't need a temporary account to test this because eBay would, as the last step, ask you whether you are really sure to close the account, at which point you could abort.

**Comment by dillbyrne** [comment]
@bugreport0 I don't have an account so I'd need to make one anyway :smile: . I'll let you know when I get a chance and get back to you.

**Comment by dkasak** [comment]
@dillbyrne If @bugreport0 wasn't using a custom-compiled latest master for testing, he may have just stumbled upon the same bug as myself in #184. I just tested the above close account procedure and it seems to work (a list of reasons appear after selecting the reason category).

**Comment by dillbyrne** [comment]
@dkasak Thanks for testing it and reporting back :+1: .

**Comment by dillbyrne** [comment]
@bugreport0 0.9.5.2 has been released if you want to try that and see if it solves the issue. I have not yet had a chance to look into it.

**Comment by bugreport0** [comment]
Yes, you have solved it, thank you. You don't even need to disable script injection now.
