### ISSUE TITLE
Conflict with RES - reddit enhancement suite

### ISSUE THREAD

**Issue by jamesdwilson** [dillbyrne/random-agent-spoofer#175]
Not sure where the fault lies, I will open one with them also. 
When RAS is enabled, RES doesn't load.

**Comment by jamesdwilson** [comment]
Figured out it is an issue with RES not working if "Disable local dom storage" is checked. Still a conflict. Still need a way to let these both work at the same time. I guess whitelist is my only option at this stage?
Ideally I don't have to lose my privacy gained from RAS for this.

**Comment by jamesdwilson** [comment]
Firefox 37.
RES 4.5.4
RAS 0.9.5 (From github)
https://github.com/honestbleeps/Reddit-Enhancement-Suite/issues/2172

**Comment by dillbyrne** [comment]
Hello @jamesdwilson 

It looks like RES requires dom storage to function. The current option in RAS is system wide. I have an [issue](https://github.com/dillbyrne/random-agent-spoofer/issues/117) open to improve the dom storage option in RAS but for now your only option is to allow dom storage in RAS if you want to use both RES and RAS.

I'm closing this issue now and I will post any updates concerning dom storage to issue #117
