### ISSUE TITLE
Error with Roundcube attachment upload when using RAS

### ISSUE THREAD

**Issue by dkasak** [dillbyrne/random-agent-spoofer#184]
I have a private installation of [Roundcube](http://roundcube.net/) on an email server which I sometimes use as webmail. I noticed today that when RAS is turned on, uploading attachments makes Roundcube produce a modal dialog saying "An error occured: File upload failed.". However, the file then seems to upload correctly.

I realize this isn't enough information to know for sure what's going on, but I also noticed this happens on a clean profile with only RAS installed and with the default settings. I tried turning off the spoofing options that are turned on by default (documents, encoding, language) but the result was the same. What things does RAS change by default, even when everything is checked off in the options?

**Comment by dillbyrne** [comment]
Hello @dkasak in 0.9.5.1 there only 2 settings where no gui option is available in RAS. These are the network cache which was disabled by default as  a fix to #121 and the script injection capability itself.  

You can change the network cache preference if you want by setting the pref `network.http.use-cache` to `true` . This cache option is different from the ones already in RAS.

0.9.5.2 has options to toggle all of RAS's settings including the cache mentioned above and script injection but while script injection is disabled certain options will not work such as date and time spoofing, screen and window spoofing, the vendor profile attribute spoofing and the whitelist.

**Comment by dkasak** [comment]
I noticed that you talked about the network cache being forced off elsewhere so I already tried leaving RAS on and setting `network.http.use-cache` to `true` but it didn't help. Since then, I stumbled upon another site that got broken in similar circumstances and then I noticed something weird: it appears that RAS overwrites the first `<script>` element of the page with the script injection element instead of the element getting appended. I've tested this on a minimal html file. Furthermore, it only happens when opening the file through the `http(s)://` schema and not through `file://`. It also doesn't happen on a clean profile so it must be some extension interaction. I'll investigate further and report back.

Also, thanks for the advice. I only disabled the headers for debugging purposes.

**Comment by dkasak** [comment]
Well, this is weird. I can't make it not happen on my usual profile even when I disable all extensions except RAS.

**Comment by dillbyrne** [comment]
Yes RAS needs to inject the script first to overwrite the desired properties so that when subsequent scripts try to get the information the get the injected information. In general most of the settings used in the script injection can be toggled off so by default only a minimal script is actually injected to spoof the vendor attribute.

As I said above 0.9.5.2 will have the option to completely disable script injection making it like the AMO version.

>Well, this is weird. I can't make it not happen on my usual profile even when I disable all extensions except RAS.

I can confirm that RAS works with NoScript, ABP,  https-everywhere, disconnect and cookie monster.

**Comment by dkasak** [comment]
> Yes RAS needs to inject the script first to overwrite the desired properties so that when subsequent scripts try to get the information the get the injected information.

Right, and this is how it behaves for me on a clean, new profile (I took a look at the code and saw you're using `window.document.head.insertBefore`). However, what I'm seeing is the first `<script>` element of the page being *overwritten* with the RAS injection script. That's why I was getting weird errors with RAS on some sites, but I'm lost as to what the cause of this could be. If I can't determine what's causing it, I guess I'll just have to move to a new profile.

Closing this for now since it seems to be an error in my setup.

**Comment by dillbyrne** [comment]
@dkasak  [0.9.5.1](https://github.com/dillbyrne/random-agent-spoofer/blob/d6dd0f66c38c406b28043bd7d97a1463d9552741/data/js/inject.js#L131) uses `window.document.head.appendChild( script );` 

I changed the code for  the 0.9.5.2 release to use `window.document.head.insertBefore`

**Comment by dkasak** [comment]
@dillbyrne Hmm, right. I guess [this line](https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/js/inject.js#L129) was a bug before, right?

**Comment by dillbyrne** [comment]
@dkasak Yes it appears so. It would explain the behaviour you are seeing. 0.9.5.2 will be released soon so it should fix this issue. Sorry for the confusion

**Comment by dkasak** [comment]
Gotcha, thanks. Don't worry about it.
