### ISSUE TITLE
Better defaults

### ISSUE THREAD

**Issue by alct** [dillbyrne/random-agent-spoofer#186]
We should consider releasing RAS with predefined options so that it works *out-of-the-box*.

We should go for non-breaking options (in the sense that they do not degrade the user experience to the point that regular applications/websites are broken).

What do you think?

### Profile

- Random (desktop)

### Headers

- Enable DNT (Do Not Track)
- Spoof Accept
- Spoof Accept-Encoding
- Spoof Accept-Language (US English) 

### Extra

- Enable script injection
- Timezone spoofing [random]
- Disable link prefetching
- Disable DNS prefetching
- Disable webRTC
- Use click to play for plugins
- Block active mixed content
- Disable browser pings
- Disable plugin name enumeration
- Disable CSS visited links

**Comment by dillbyrne** [comment]
RAS already sets the accept headers on by default but they only get applied when a spoofed profile is in use.

RAS will also set the script injection to enabled by default but only the vendor info for the currently spoofed profile is applied in the injection script unless the user explicitly adds the other options using the dropdowns or checkboxes.

As it stands in the current version of 0.9.5.2 RAS will set the extras using built in prefs  based on their states before RAS was installed so it honours the users previous choices. 

I don't want to set too many preferences as enabled by default as I want to respect the users choices prior to installation with respect to the extras and I want to reduce confusion for new users as the script injection options can cause issues on some sites.

I would rather let the user decide on DNT as it can change the fingerprint as there is no guarantee sites will honour it. 


By default the following are set in firefox and will be set in RAS unless the user has changed them

browser pings are disabled
mixed content blocking is enabled
click to play is enabled

I'll add
* desktop profile as default 
* enabling tracking protection
* disable plugin name enumeration
* disable CSS visited links 


The [tracking protection preference uses disconnect's blocklists](https://support.mozilla.org/en-US/kb/tracking-protection-firefox) 

Also RAS sets the network cache as disabled by default as a fix to #121 as I still have not found a better solution to that problem.

**Comment by dillbyrne** [comment]
These are the defaults now. I'm going to close this issue now

Profile

*  Random (desktop)

Headers

*  Spoof Accept
*  Spoof Accept-Encoding
*  Spoof Accept-Language (US English)

Extras

*   Disable network cache (as a fix for #121)
*   Use click to play for plugins (default in firefox)
*   Block active mixed content (default in firefox)
*   Disable browser pings (default in firefox)
*   Disable plugin name enumeration
*   Disable CSS visited links
*   Enable tracking protection 

Whitelist

* Disabled by default
