### ISSUE TITLE
Add Color Depth support

### ISSUE THREAD

**Issue by smithhooray** [dillbyrne/random-agent-spoofer#188]
Your plugin is awesome. Just awesome! I would really like to see in a new update Color Depth support among the Screen Size Spoofing.

One more question. I posted another thread where you said you will update it with the latest code(including my suggestion (https://github.com/dillbyrne/random-agent-spoofer/issues/177) ). So the question is when will it be available? Do I need to compile it by myself or will it be located in "releases" section? Thanks in advance

**Comment by dillbyrne** [comment]
Thank you @smithhooray 

ColorDepth is already spoofed. See https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json#L22

It is set based on the color depth of the target profile.

When 0.9.5.2 is ready it will be available under the releases section. It'll be available in a few days.

I'm closing this issue now.
