### ISSUE TITLE
Some locales break the UI

### ISSUE THREAD

**Issue by dillbyrne** [dillbyrne/random-agent-spoofer#192]
This will have to be fixed before 0.9.5.2 can be released
Screenshots to follow

**Comment by dillbyrne** [comment]
Screen shots of the UI issues during testing.

* da-DK
![da-1](https://cloud.githubusercontent.com/assets/2903711/7217186/66911b76-e613-11e4-837f-c44b898ec425.png)

* de-DE
![de-1](https://cloud.githubusercontent.com/assets/2903711/7217188/68209c6e-e613-11e4-80ad-55ac1265051b.png)
![de-2](https://cloud.githubusercontent.com/assets/2903711/7217192/683b2a34-e613-11e4-8cf9-28ffabfc71d4.png)

* es-ES
![es-1](https://cloud.githubusercontent.com/assets/2903711/7217189/6839e188-e613-11e4-9635-8fa6a42a969f.png)
![es-2](https://cloud.githubusercontent.com/assets/2903711/7217193/683bb1f2-e613-11e4-835f-d95edfd1aaf0.png)

* fr-FR
![fr-1](https://cloud.githubusercontent.com/assets/2903711/7217187/66a83284-e613-11e4-8013-bffe20e6127b.png)
![fr-2](https://cloud.githubusercontent.com/assets/2903711/7217194/683bc94e-e613-11e4-9094-d11765607e93.png)

* ja
![ja-1](https://cloud.githubusercontent.com/assets/2903711/7217191/683b1e22-e613-11e4-8c52-d8dbdac9e106.png)
![ja-2](https://cloud.githubusercontent.com/assets/2903711/7217190/683a1e1e-e613-11e4-9d7a-e7db8cf379b4.png)
![ja-3](https://cloud.githubusercontent.com/assets/2903711/7217196/6853c292-e613-11e4-883c-9f087d467af4.png)

* ko
![ko-1](https://cloud.githubusercontent.com/assets/2903711/7217195/68524232-e613-11e4-8ec9-1d31de709df0.png)
![ko-2](https://cloud.githubusercontent.com/assets/2903711/7217199/68590acc-e613-11e4-9df5-f791c1ce5ae2.png)

* no
![no-1](https://cloud.githubusercontent.com/assets/2903711/7217197/6857540c-e613-11e4-80d7-1f4c1583626d.png)

* pl
![pl-1](https://cloud.githubusercontent.com/assets/2903711/7217198/6858b2f2-e613-11e4-8c5d-561cf45ada07.png)

* pt
![pt-1](https://cloud.githubusercontent.com/assets/2903711/7217200/685b2fd2-e613-11e4-99df-8b425de13f3f.png)

* ru
![ru-1](https://cloud.githubusercontent.com/assets/2903711/7217201/686a6d62-e613-11e4-8b35-a6486dd7e177.png)
![ru-2](https://cloud.githubusercontent.com/assets/2903711/7217202/686ca942-e613-11e4-9e65-9ca995c21a74.png)



@alct Any ideas on this ? Making the panel width bigger will sort some of the issues but some languages still mess up the tabs.

**Comment by alct** [comment]
I'll have a look into it.

**Comment by dillbyrne** [comment]
Thanks :+1: . By setting the panel width to 480 most of the issues are resolved. Some languages still have problems such as Japanese and Russian with the tabs. I could reword some of the headings on tabs for problematic locales, such  as Extras to Options  and Whitelist to List .

The above should work if we can not find another solution.

**Comment by alct** [comment]
(I'll have some time on tuesday)

**Comment by dillbyrne** [comment]
@alct Cool. I'm still working through the locale files and rewording them where necessary I have managed to reduce a number of the issues so far but there are still some remaining despite the rewording.
