### ISSUE TITLE
Canvas spoofing

### ISSUE THREAD

**Issue by rullskidan** [dillbyrne/random-agent-spoofer#199]
I know RAS can block canvas fingerprint but why can it not spoof it instead? Everything that is blocked looks suspicious! It is better to have a spoofed value instead. It should have a random button like many other functions in RAS.

**Comment by dillbyrne** [comment]
hello @rullskidan there is already an [issue](https://github.com/dillbyrne/random-agent-spoofer/issues/111) open for this so I'm closing this issue.
