### ISSUE TITLE
Profile exclusions not persistent

### ISSUE THREAD

**Issue by sbs4000** [dillbyrne/random-agent-spoofer#202]
Hello,

the exclude options in the Profile tab are not persistent. If I exclude some profiles, they are no longer excluded when I reopen FF (37.0.2).

Best

**Comment by dillbyrne** [comment]
Hello @sbs4000 . 

I am unable to reproduce this , it works as expected for me.

Did you install it 0.9.5.2 fresh or upgrade it from 0.9.5.1 ? If so there should be no problems.

**Comment by sbs4000** [comment]
Hello dillbyrne,

I indeed upgraded from the previous version. I removed it and reinstalled and now everything works fine. Sorry for that, I should have tried this before posting.

Best,
sbs4000

**Comment by dillbyrne** [comment]
@sbs4000 What version did you have previous and where did you install if from. If you previously had 0.9.5.1 and upgraded to 0.9.5.2 it should have worked fine. Were you using a version from the mozilla site previously ?

**Comment by sbs4000** [comment]
It was 0.9.5.1 and I believe it was installed from the Mozilla site though I cannot guarantee. All other settings were retained from the previous version after upgrade and were persistent in case of change. Only the profile exclusions were not persistent.

**Comment by dillbyrne** [comment]
The mozilla version is out of date, it is on version 0.9.3.1 and will not update correctly to the github version of 0.9.5.2.  I'm still working on a limited version of 0.9.5.2 for the AMO site will will allow a clean upgrade.
