### ISSUE TITLE
Please bring back "Enable RAS" control

### ISSUE THREAD

**Issue by g2781644** [dillbyrne/random-agent-spoofer#203]
"The toggle based system was removed as it confused users."

Now I have a big problem: there is no way (at least I have not found one yet) to quickly disable and enable RAS entirely. Very many web sites do not work when RAS is active, so I need this function all day. Disabling RAS through the FF extensions page has the side effect of deleting all RAS settings.

It would also be nice to get the option back to disable notification.

Thanks

**Comment by dillbyrne** [comment]
Hello @g2781644 

I understand where you are coming from but I will not be bringing back the toggle based system for several reasons.  


It caused a great deal of confusion to some users as the toggle system would reset preferences to their default value when spoofing was disabled. This was necessary to ensure that sites would work correctly when sites were disabled. 

It was a recurring complaint.

Now only script injection, the accept headers and the whitelist are disabled when the default profile is selected. The standard options and the non accept header options remain in use unless specifically disabled.

With the toggle based system in use I had to maintain 2 preferences for every single option, one for the option and one for its state. Not only was that wasting memory but it also significantly slowed down development. Now I have stremlined the whole process of adding about:config options to RAS that they can be added very quickly.

I will eventually be adding a slider section which will have several levels #139 . When adding it I will be seeking user input on what preferences should be enabled disabled at each level. This could allow for similar system to the toggle system but it will not work the same. 
  
The notifications preference was moved to the addons tab page  (`about:addons`).

![temp](https://cloud.githubusercontent.com/assets/2903711/7373673/d3f76f1c-edc5-11e4-9a7a-4ba0243bd8df.png)
