### ISSUE TITLE
Add Flattr Account

### ISSUE THREAD

**Issue by Mosrite** [dillbyrne/random-agent-spoofer#204]
I'd really like to support this project. As I'm not a programmer I cannot add anything to do the code, so at least I'd like to help financially. Could you set up a Flattr account for RAS?

**Comment by dillbyrne** [comment]
Hello @Mosrite . Thank you I appreciate it :bow: ,  I'll look into flattr and get back to you. 

Apart from coding there are other ways to contribute if you'd such as gathering profile information so we can keep RAS up to date. It is as simple as installing the latest version of the browser you want added and visiting the following three links

http://browserspy.dk/browser.php for the main profile
http://browserspy.dk/accept.php for the accept headers
http://browserspy.dk/screen.php for the screen size

Either copy and paste it the output or add screenshots of the pages into a new issue titled like `Chrome 43.xx.xx  64bit on Windows 8.1 profile` and I can then add the new profile or update an existing one. 

Common mobile profiles are always helpful too.

**Comment by dillbyrne** [comment]
Hello @Mosrite I have added a flattr button to the read me at https://github.com/dillbyrne/random-agent-spoofer . Thanks again
