### ISSUE TITLE
(Linux) Unreadable GUI with dark GTK theme

### ISSUE THREAD

**Issue by DaarkWel** [dillbyrne/random-agent-spoofer#205]
I guess GUI window somehow uses font color from GTK, but background color is hardcoded white. So with dark themes it looks like this:

![Screenshot](http://storage3.static.itmages.ru/i/15/0501/h_1430477101_9748763_7dbf2c2a35.png)

**Comment by dillbyrne** [comment]
Hello @DaarkWel Thanks for your bug report I'm working on it now and I will have a fix out shortly.

**Comment by dillbyrne** [comment]
@DaarkWel can you try https://github.com/dillbyrne/random-agent-spoofer/releases/download/0.9.5.3-beta-1/random-agent-spoofer.xpi and tell me if that fixes your problem. It should but I want to be sure before  closing

**Comment by DaarkWel** [comment]
Yes, now it's quite all right. Thank you.
