### ISSUE TITLE
Links do not open on About tab

### ISSUE THREAD

**Issue by Jiriss** [dillbyrne/random-agent-spoofer#207]
Bug in version 0.9.5.3. The links do not open on About tab

**Comment by dillbyrne** [comment]
All the links open fine for me here. 

What version of firefox are you using 

Have you tried it in a fresh profile

https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Jiriss** [comment]
I use Firefox ESR (31.6). I really don't like create a new profile because I would lost all my settigs etc.

**Comment by dillbyrne** [comment]
I'm saying to make a new additional profile as a test it will be a separate profile from your current  one with separate settings and addons.

**Comment by dillbyrne** [comment]
I'm closing this see  as it is not reproducible #208 for details

**Comment by Jiriss** [comment]
I created a new profile and then the links opened well
