### ISSUE TITLE
Limit tab history to 2 option doesn't work

### ISSUE THREAD

**Issue by tegru** [dillbyrne/random-agent-spoofer#211]
Noticed this also on ip-check.info. Had to manually change browser.sessionhistory.max_entries in about:config. It was at default value 50 even though setting this option in RAS.

**Comment by dillbyrne** [comment]
The issues you reported require script injection to be enabled, make sure you have it enabled .  It works fine for me as you can see from the screenshot in your other issue #210 .

Try it in a new profile and RAS should work. It could be another addon causing it not to work.

**Comment by dillbyrne** [comment]
Closing see #210
