### ISSUE TITLE
[Request] Change whitelist to per-site options

### ISSUE THREAD

**Issue by tegru** [dillbyrne/random-agent-spoofer#216]
To me the whitelist is not so useful. I haven't seen any of the options breaking websites, except maybe for canvas (but I'm now using the CanvasBlocker add-on for that anyway).

In my case it would be more useful to enable additional options per site. Like for example enable x-forwarder-for only on some sites.

So my feature request would be changing whitelist to something that can be used to disable AND enable certain features per-site.

**Comment by dillbyrne** [comment]
X-Forwarded-For is already available in the whitelist. All of the standard extras are global options so there is no way to pick and choose what to enable or disable on a site by site basis. The whitelist works per url, although it is not perfect, I do plan to improve it when I know (as an addon developer) where where I stand with the APIs when the multi process stuff comes into effect.

**Comment by dillbyrne** [comment]
There is already an issue open for per site profiles, #214 

Closing as duplicate, https://github.com/dillbyrne/random-agent-spoofer/wiki/Bug-reporting-guide
