### ISSUE TITLE
FFDE 40.x Breaks Functionality

### ISSUE THREAD

**Issue by GuardianMajor** [dillbyrne/random-agent-spoofer#220]
As of the release of the 40.x branch (ie 40.0a2 (2015-05-18)) it has broken functionality of this addon. While ALL addons are getting the same type of warning:

![capture](https://cloud.githubusercontent.com/assets/5274181/7687966/bd9f7bd4-fd55-11e4-802c-13475dbb4a65.PNG)

They continue to function normally but this one disappears completely and won't work even though it shows up fine in the list.

Just wanted to drop a heads up. It might have to do with the Electrolysis release but I am not 100% convinced yet, hopefully you can figure it out.

**Comment by beefcurtains** [comment]
What version do you have?

**Comment by GuardianMajor** [comment]
@beefcurtains - read the post its inside the parenthesis.

**Comment by beefcurtains** [comment]
I meant the addon, not Firefox.

**Comment by dillbyrne** [comment]
The addon still works. This is a warning about addon signatures I suspect but it will not come into effect and block the addon until June 15th. I received the following from mozilla

```
Dear add-on developer,

Mozilla will begin signing all add-ons in order to protect users from malware and extensions that haven't been reviewed. Here's what you need to know about the new process:

No action is required for add-ons distributed via addons.mozilla.org (AMO). On May 28, 2015, the latest versions of your existing add-ons will be automatically signed and pushed as updates to your users, after which you will receive an email notification. Starting on June 1, all files you submit will be signed after they pass review.

If you have add-ons that are not distributed via AMO, including beta versions or debug builds, there will be a new option in the add-on submission process to submit these as unlisted add-ons starting on June 1. Starting around June 15th, users of builds based on Firefox 40 or higher (currently Nightly and Developer Editions) will see unsigned add-ons disabled by default, with the option to bypass the signature check to re-enable them. Users will no longer be able to bypass the signature check when builds based on Firefox 41 reach beta, on or around August 11. 

The Firefox add-on distribution agreement has also been updated to reflect the new distribution options and clarify our review policies. You can read the updated agreement here: https://developer.mozilla.org/Add-ons/AMO/Policy/Agreement

If you have any questions or concerns, read the add-on signing FAQ or visit our forums: 
FAQ: https://wiki.mozilla.org/Addons/Extension_Signing
Forums: https://forums.mozilla.org/viewforum.php?f=7

Sincerely,
The Add-ons Team
```

I have to wait until June 1st to submit the github version of RAS for signature signing.

**Comment by dillbyrne** [comment]
@GuardianMajor I'm using (ie 40.0a2 (2015-05-20)) and it works fine with RAS. Is there anything else aside from the warning above ?

**Comment by GuardianMajor** [comment]
@dillbyrne  sorry my friend for not seeing this sooner, for some stupid reason they don't notify me. I know it should work, as others do too and the warning is just that but it won't work. I am running version 0.9.3.1 which is the latest available. I don't see anything else that would prevent it from showing up and no other errors or warnings besides what I shared. Thoughts?

**Comment by GuardianMajor** [comment]
Since the latest update is not available on the addon page, I went ahead and put it on from here and it seems to show up, I will keep you posted if I hit any hiccups.

**Comment by dillbyrne** [comment]
Ah 0.9.3.1 is very outdated now as it is the version on AMO. I have a limited version on AMO awaiting review , version 0.9.5.2 , it is currently at position 29 out of 120 in the review queue.  It is taking them a while to review it as I suspect there is an influx of addons and updates due to the API changes.

If you want the latest full version use the github version at https://github.com/dillbyrne/random-agent-spoofer/releases

The 0.9.3.1 version probably no longer works due to mozilla updating the firefox API's .

**Comment by dillbyrne** [comment]
I'll close this for now and you can let me know if there are any issues.

**Comment by GuardianMajor** [comment]
I have to say that the latest one is taking too much liberties with changes to the settings that should ONLY be active when the profile is activated, should not remain permanently, I prefer the non-intrusive behavior of the older one than the new one, its overreaching way too much without containing itself to when activated. I have to think about this.

**Comment by dillbyrne** [comment]
Users complained about the old behaviour prompting the new behaviour. I can't win it seems.

I do plan to add a slider to allow users to select sets of options ranging from none to all and various settings in between. This should achieve the result of allowing a user to "toggle" it like the old behaviour #139

**Comment by GuardianMajor** [comment]
You should be able to build a configured profile and when active, it does everything selected and when not, it leaves the browser alone to the defaults that has been configured for it. This is not right and I don't see why anyone would ask a simple user agent spoofer to reach into areas on a normal basis that it frankly has no business doing. Disappointing, sorry you had to yield but its your decision to make, but you should have stood your ground more and done more to ensure that it was done more properly without overreaching like this.

**Comment by beefcurtains** [comment]
@GuardianMajor why don't you send in a PR instead of bitching to the developer who puts in free time to create something cool that improve our lives?

@dillbyrne As I expected, reporter used an old version and didn't bother to update before filing an issue. The add-on is quite useful and you're doing a great job here. Please don't take the criticisms personal, haters will hate, plebs will pleb. Thanks for making such a great add-on.

**Comment by dillbyrne** [comment]
@beefcurtains Thanks

@GuardianMajor 

As noted in the update pages the update must be done from the previous version or install fresh. I state this in the release notes of every update. If coming from AMO version to the github version, you need to install it fresh.

If it has been installed correctly then uninstalling it removes all of the changes and resets all the preferences so please don't level accusations which are based on falsities, I don't care for it.

It does not overreach, it is simply now using the actual firefox preferences most of which are system wide and now have to be toggled on or off manually as is the case in most addons.

Maintaining an intermediary state of all the settings made it time consuming to develop, added a lot of code and confused users. Removing makes it much cleaner to add settings and respects the users about config preferences when they install the addon. 

I already said I plan on implementing a slider. Which will allow for something similar to the toggle based behaviour. 

I'm not going to debate this further as it is a waste of my time. If you like the addon use it if not don't . Obligatory [xkcd](https://xkcd.com/1172/)

I'm locking this issue now
