### ISSUE TITLE
Firefox 28 Issue

### ISSUE THREAD

**Issue by marzametal** [dillbyrne/random-agent-spoofer#222]
I am able to sucessfully install the Git version into Firefox 28. However, there is no icon to use... try to customise the bars and there is no sign of RAS.

I managed to get it working on version 0.9.4.3 ... is there any way to get the icon to show in addon-bar for FF 28?

**Comment by marzametal** [comment]
I figured it out... had to upgrade to v29!

**Comment by dillbyrne** [comment]
Glad you figured it out
