### ISSUE TITLE
Issue with screen resolutions

### ISSUE THREAD

**Issue by wrzhouse** [dillbyrne/random-agent-spoofer#223]
It's easy for anyone to spot faked screen resolution, as 'Your screen:' and 'Available screen:' are always same values, while if not faked are different.

Example: http://ipleak.net

**Comment by dillbyrne** [comment]
@wrzhouse there is an open issue for this already. #54

Closing as duplicate

https://github.com/dillbyrne/random-agent-spoofer/wiki/Bug-reporting-guide

**Comment by wrzhouse** [comment]
OK. One more thing....

http://www.imamasim.com/cli/css3.htm

screen resolution detection by css3. Can you change the screen
resolution the way, so it could be detected right way via css3 as
well?

Now css3 shows original value, while js working OK (not talking about
the bug I told you before)

**Comment by dillbyrne** [comment]
@wrzhouse I don't know of a way off hand to do it but I'm sure it can be done. If myself or someone else can figure it out I'll be sure to add it.
