### ISSUE TITLE
Usage in Firefox for Android v38?

### ISSUE THREAD

**Issue by mmn980** [dillbyrne/random-agent-spoofer#225]
Are there any chances, that the add-on will start working with FF for Android? That would very nice. Sorry, if this is posted to a wrong place.

**Comment by dillbyrne** [comment]
Hello @mmn980 . RAS is largely integrated with various firefox desktop specific API's that are not available in the android version . I suspect it would require a lot of effort to port it and I don't have time to do that I'm afraid. If you would like to do so feel free . It is [free software](http://www.gnu.org/philosophy/free-sw.en.html) after all :smile_cat:
