### ISSUE TITLE
Icon size too large when placed in bookmarks toolbar

### ISSUE THREAD

**Issue by dkasak** [dillbyrne/random-agent-spoofer#229]
When the RAS icon is placed in the bookmarks toolbar, it is much larger in size than the rest of the icons. The issue is the same as in ChrisAntaki/plugins-and-mimetypes-firefox#5. The fix seems to be to add icons at other suggested sizes.

**Comment by dillbyrne** [comment]
This seems to be fixed now as you can see in the image I have added.

![temp](https://cloud.githubusercontent.com/assets/2903711/7891683/91dc7930-0646-11e5-9815-4682613f1d93.png)


It'll be available in the next release which will be soon. I'm holding off until I can submit the next release to be signed by mozilla but they are not accepting externally hosted addons just yet.

I'm closing this now. Feel free to reopen it if  you see it in the next release

**Comment by dkasak** [comment]
Actually, the size was still wrong for me until I applied the changes as in #232.

**Comment by dillbyrne** [comment]
@dkasak My apologies you are correct. I tested it on the developer edition and it worked as expected, I forgot to test it on version 38.  I will merge your PR and change it back when 40 is released as using the lowest resolution icon for the toolbar forces it to be used for the dropdown menu as you can see in the image below. In firefox 40 the highest resolution icon is scaled down. 

![pl-2](https://cloud.githubusercontent.com/assets/2903711/7964020/8ebcab1a-0a0d-11e5-8e49-baa5e1f7d7d9.png)
