### ISSUE TITLE
How to install RAS 0.9.5.2 on firefox

### ISSUE THREAD

**Issue by potholiday** [dillbyrne/random-agent-spoofer#230]
I have downloaded the github zip file and i am unable to find XPI for RAS 0.9.5.2. can you tell me how to install RAS extension on firefox

**Comment by RoxKilly** [comment]
Use the .xpi links at https://github.com/dillbyrne/random-agent-spoofer/releases

**Comment by dillbyrne** [comment]
Hello @potholiday  clicking on the  .xpi links will install the github version as RoxKilly  has said

**Comment by potholiday** [comment]
thanks for the info @RoxKilly  @dillbyrne
