### ISSUE TITLE
Does/should RAS disable Beacons?

### ISSUE THREAD

**Issue by RoxKilly** [dillbyrne/random-agent-spoofer#233]
I wonder whether RAS protects users against tracking done via Beacons? According to the specs, Beacons allow sites to transfer data asynchronously to servers, even after the page is unloaded.  Spec: "The specification addresses the needs of analytics and diagnostics code that typically attempt to send data to a web server prior to the unloading of the document."  My understanding is that any  script that  can attach an event listener to the document unloading event would be able to send data via POST to any server once the page is unloaded. This happens behind the scenes though so I don't think most blockers would stop it. Spec: "The actual data transfer may occur after the page has unloaded."  

I noticed that RAS disables browser pings, but I don't know whether Beacons are addressed. I read the user manual but some of the options found in RAS (0.9.5.3) are not explained in the manual.  I think that in FF, the Beacons can be disabled in  about:config  by setting beacon.enabled=false

This came to my attention because @gorhill is adding protection to his uBlock Origin tool. I am not sure that there is a significant additional privacy exposure given that the Javascript is already being allowed to run. Would this issue even fall under what RAS is meant to protect users against?

Further reading
Spec: http://w3c.github.io/beacon/
uBlock Origin release notes: https://github.com/gorhill/uBlock/releases
Discussion:  http://www.wilderssecurity.com/threads/hyperlink-auditing-aka-a-ping-and-beacon-aka-navigator-sendbeacon.364904/,

**Comment by dillbyrne** [comment]
@RoxKilly Sure I'll add in for the next version. RAS currently has not option for beacons. I will add a checkbox for it in the extras section

**Comment by dillbyrne** [comment]
@RoxKilly I have added an option to toggle the preference and it will available in 0.9.5.4 which I will submit to mozilla for signing when they open the submission process for external addons.
