### ISSUE TITLE
No icon  on win 8 64bit FF dev edition 40.0a2 (2015-06-08)

### ISSUE THREAD

**Issue by dillbyrne** [dillbyrne/random-agent-spoofer#240]
@mack318 writes 

```
one of my favorite add ons.
tried to add it to the new developer addition of Firefox. The icon does not appear.
it might be helpful if there was an alt settings button inside the add on manager. 
Without the icon there is no way to adjust the settings.
Im running win 8 64bit
Firefox developer edition 40.0a2 (2015-06-08)
```

**Comment by dillbyrne** [comment]
@mack318 

I don't have windows 8 on hand at the minute but it is working fine on the latest developer edition on linux 64 bit. 

![](http://i.imgur.com/tzNpG3F.png?1)

I'll try to get a a windows 8 machine to test it on and get back to you. 


Can you tell me which version (github or AMO) and the version number that you are using

**Comment by dillbyrne** [comment]
@mack318 I had a friend test firefox dev edition and RAS on windows 8 64bit and it worked fine. See attached the  screenshot  .

![ras-windows 8 x64](https://cloud.githubusercontent.com/assets/2903711/8398195/437640b0-1ddd-11e5-9682-347dc347df2b.png)




Can you try it in a [fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and tell me if it works

**Comment by mack318** [comment]
using random agent spoofer version 0.9.3.1.1-signed if that makes a difference.  I tried un installing and re-installing it.

the add ons manager shows it installed, but the toolbar icon is not there.  

i wonder if  there is some really simple thing im just missing?

my regular edition of firefox uses 0.9.4.1   on  firefox 38.0.5

could the two different versions of firefox be conflicting somehow?

is there any other info about my set up that may help?  I could not take a screen shot of my extensions page.

i have not installed github to this laptop.  Would it help you if i did that?

thanks for all your help

**Comment by dillbyrne** [comment]
Hello @mack318 Those versions of RAS are really old now. I have a version on AMO but the review is taking much longer than anticipated. If you would like to use the most up to date release then you have to uninstall the current versions and install the version from https://github.com/dillbyrne/random-agent-spoofer/releases

the .xpi link will download and install RAS https://github.com/dillbyrne/random-agent-spoofer/releases/download/0.9.5.3/random-agent-spoofer.xpi

The reason the icon is not showing is because the browser no longer supports the widget module which 0.9.3.1 still uses. All newer versions of RAS now use the ActionButton in its place. Sorry for the delay in getting back to you

**Comment by mack318** [comment]
That did the trick.  I was using the install portal at Mozilla.  I do recall that one had less features that what you had on GitHub.  I just presumed that the add on would update itself like all the others typically do.

Thank you once again.  Much respect for your work on one of the greatest add-on's of all time

**Comment by dillbyrne** [comment]
Well it would have updated to the next limited AMO version when they review it but it has been in the review queue for over a month now. It has never taken this long before so I thought it would have been available by now. 

The github version updates at a different pace than the AMO version and as such the update code between the two are not compatible. So that is why you had to remove the AMO version first before installing the github version.

Glad you got it working and thanks for the support.
