### ISSUE TITLE
Disable Notifications

### ISSUE THREAD

**Issue by kekkc** [dillbyrne/random-agent-spoofer#241]
With the AMO version it's possible to disable RAS notifications ("browser profile has changed"), however this seems not to be available anymore for the 0.9.5.3. Was there a reason to remove it or was it simply forgotten to transfer?

**Comment by dillbyrne** [comment]
It is still available . If you read the read me it says `Profile notifications can be toggled in the addons preferences (see about:addons).` 

![temp_1](https://cloud.githubusercontent.com/assets/2903711/8255681/9afa464c-1699-11e5-8d51-d37ba071057e.png)

**Comment by Kezxo** [comment]
In the user manual it says the setting is under the profile tab and nothing else.

**Comment by dillbyrne** [comment]
@Kezxo I need to update the manual, Sorry about that. I plan to do it soon
