### ISSUE TITLE
Change periodically: Every request is not working

### ISSUE THREAD

**Issue by s00iyool** [dillbyrne/random-agent-spoofer#249]
1. visit image gallery
2. RAS pick up only one UA, ans stick with it.

get /  UAAAAAAAAAAA
get /img1.jpg UAAAAAAAAAAA
get /img2.jpg UAAAAAAAAAAA

I'm expecting this. "Secret Agent" can do this...

get /  UAAAAAAAAAAA
get /img1.jpg UAAAABBBBBBBA
get /img2.jpg UCCCCAAA

**Comment by dillbyrne** [comment]
Ras does work like that. 

 See attached images 

![ras-request1](https://cloud.githubusercontent.com/assets/2903711/8396563/58134d5e-1da3-11e5-8b25-ef74027998a4.png)
![ras-request2](https://cloud.githubusercontent.com/assets/2903711/8396566/5814607c-1da3-11e5-8361-d403380759b7.png)
![ras-request3](https://cloud.githubusercontent.com/assets/2903711/8396564/5813de18-1da3-11e5-96f5-1fbff9d12945.png)
![ras-request4](https://cloud.githubusercontent.com/assets/2903711/8396567/5814f7ee-1da3-11e5-8d60-e228585e8cfa.png)
![ras-request5](https://cloud.githubusercontent.com/assets/2903711/8396565/58145956-1da3-11e5-9dea-1c0cdfbfb01b.png)
