### ISSUE TITLE
User-agents: Why and How and How to

### ISSUE THREAD

**Issue by alct** [dillbyrne/random-agent-spoofer#251]
For the record: https://firstlook.org/theintercept/document/2015/07/01/user-agents/

**Comment by RoxKilly** [comment]
Thanks that was an interesting read.  One slide 34, there is mention that if a search by IP turns out several user agents, there may be several users, and that to better identify the target, the user agent should be correlated with cookies and TDI.   Do you know what TDI means in that context?

**Comment by alct** [comment]
>  Do you know what TDI means in that context?

[Telecom data intelligence](https://en.wikipedia.org/wiki/Telecom_data_intelligence) : informations obtained via communication service providers

**Comment by dillbyrne** [comment]
@alct Thanks for sharing. It has always been part of the design goals of RAS to appear like multiple users behind a single IP. When I add self destructing cookie like functionality to RAS it should make it better. The next release will support the option for different language headers too which adds more variables to the mix.

**Comment by RoxKilly** [comment]
@dillbyrne Doesn't RAS already spoof the Accept-Language header?

**Comment by dillbyrne** [comment]
@RoxKilly It does but the current release only uses US english. This is about using alternative languages as you can see in the screenshot below. 

![temp](https://cloud.githubusercontent.com/assets/2903711/8576875/d521fda8-259c-11e5-893f-ff2ed74f709e.png

**Comment by RoxKilly** [comment]
@dillbyrne OK thanks.

Sidenote about the image: I know what you shared is probably a work in progress so this feedback may already be outdated/irrelevant but for what it's worth: beware of overwhelming the user with many switches about the same feature. In your image, I see 4 controls for the `Referer` header.

**Comment by dillbyrne** [comment]
They are there to offer finer controls over the referer header. I may as well use the built in prefs to manage it if they are there. All options will be explained in the documentation which I will update before the 0.9.5.4 release

**Comment by RoxKilly** [comment]
You're right about using built-in preferences. Didn't realize that's what you were doing (thought you were spoofing `Referer` header).

**Comment by dillbyrne** [comment]
I try to use built in prefs in most cases. The only referer pref I did not use it the one to send it or not because using RAS's version at the header level allows us to selectively whitelist it, allowing greater control in this case
