### ISSUE TITLE
Android version?

### ISSUE THREAD

**Issue by irregularisnotrandom** [dillbyrne/random-agent-spoofer#252]
Hi

Is it possible to make it android friendly? Not installing on Android 38.0.5

**Comment by dillbyrne** [comment]
Hi @irregularisnotrandom  Currently RAS uses som SDK modules that are not compatible with the android firefox version. It is possible that it could be ported if new mobile specific interfaces were designed but I do not have the time to do that. Anyone is free to do so if they wish.
