### ISSUE TITLE
GUI Enhancment

### ISSUE THREAD

**Issue by Noitidart** [dillbyrne/random-agent-spoofer#253]
Hi there this addon is really spectacular however the element in the toolbar is way off and doesnt fit, and lots of times doesnt stay. It needs to be converted to use CusomzableUI.jsm view type. I have a template here: https://github.com/Noitidart/BingRBot/

If you need help I can make some contributions to this project.

**Comment by alct** [comment]
Hello,

Thank you for your feedback.

> the element in the toolbar is way off and doesnt fit, and lots of times doesnt stay

Can you please elaborate (provide screenshots if needed), the issue you are raising is unclear to me.

> If you need help I can make some contributions to this project.

Help is always welcome!

**Comment by Noitidart** [comment]
Are you available to chat on mozIRC? I'm on #extdev and #introduction and would love to show you. Like the toolbar icon is not showing at all for me right now I can't find it anywhere.

It seems you made an addon-sdk addon? Is that true?

**Comment by Noitidart** [comment]
Oh here's mibbit link in case you dont have an irc client for the mozilla channels: https://client00.chat.mibbit.com/?url=irc%3A%2F%2Firc.mozilla.org%2F%23introduction

my username is noida, if you can show me how to change user agent globally i can write up a very simple demo for you

**Comment by dillbyrne** [comment]
Hello @Noitidart .  What version of the addon are you using and what version of firefox ?

**Comment by Noitidart** [comment]
Thanks. Firefox 40 (beta channel) and addon version is 0.9.3.1.1+signed

**Comment by dillbyrne** [comment]
Ok we 0.9.3.11 is really old and still using the widget module which has been depreciated. I have had an updated version on AMO (0.9.5.2) for over a month and its still in review. if you wish to use the current github version you can install it by clicking the .xpi link under https://github.com/dillbyrne/random-agent-spoofer/releases

https://github.com/dillbyrne/random-agent-spoofer/releases/download/0.9.5.3/random-agent-spoofer.xpi

**Comment by Noitidart** [comment]
O so cool! Thanks!

**Comment by dillbyrne** [comment]
Sure no problem. Is it showing up correctly for you with that version ?

**Comment by Noitidart** [comment]
Oh wow this is super elegant! Thank you!!

**Comment by dillbyrne** [comment]
Glad to hear You can thank @alct for the new UI :)
