### ISSUE TITLE
Beware: help RAS avoid the feature bloat pitfall

### ISSUE THREAD

**Issue by RoxKilly** [dillbyrne/random-agent-spoofer#255]
RAS is without a doubt one of my must-have addons. I am worried that as time elapses, it will become less and less usable as more and more unexplained options are added to its menus.  I believe that RAS should stay true to its objective of *enhancing privacy and defeating tracking by making if difficult for a web server to recognize the same browser* (this is my understanding anyway).  I have just 2 observations I wanted to share with @dillbyrne and the community:

1) In its current state, RAS already presents the user with a ton of great options to meet its goal; because the options are not explained in the UI itself (and the documentation is outdated),  RAS is getting tougher to use.  If the user were given information from the UI (a tooltip or a link next to each UI option), it would be much easier to make informed decisions about whether an option should be checked/unchecked.  I am not a developer, but I would be glad to help write this context info. In most cases though, a simple link  to Wikipedia or to a page discussing the privacy implication of each option would be fine.

2)  RAS should be clear about what it's trying to accomplish and avoid adding features that do not fit its narrow objective.  For instance, I've never understood why the options to `Disable CSS visited links`, `Disable clipboard events`, `Block display mixed content`, `Block active mixed content`, `Disable Dom resource timing`, and `Disable browsing and download history` are present in RAS.  What do they have to do with a remote server tracking users? I may be off on some of these options because I don't fully know their implications but I hope you understand what I mean.  If RAS adds options that fall outside of its narrow objective, in two years it will be completely bloated, which makes for poor user experience, difficult to maintain code, more bugs etc...

**Comment by dillbyrne** [comment]
The aims of RAS are preventing fingerprinting and improving general privacy. It is much easier to check a box than to going into about:config every time you wish to change something.

I will update the documentation before the 0.9.5.4 release. 



`Disable CSS visited` links prevents a site from using css to determine if you have visited a link on the page

`Disable clipboard events` - prevents a site from knowing what you are copying and when you are copying.

`Disable Dom resource timing` - helps prevent fingerprinting based on the time it takes resources to load or not if you have them cached or blocked

`Disable Dom performance` - From the tor browser design doc "Currently, our mitigation against performance fingerprinting is to disable Navigation Timing through the Firefox preference dom.enable_performance" . https://www.torproject.org/projects/torbrowser/design/

`Disable browsing and download history` -  is obvious. It is there for users who want to use it.

`Block display mixed content` - protects users by not loading insecure display (passive) content over a secure link . Mixed Passive Content is HTTP Content on an HTTPS website that cannot alter the Document Object Model (DOM) of the webpage. 

`Block active mixed content` - protects users by not loading insecure active content over a secure link. Mixed Active Content is content that has access to and can affect all or parts of the Document Object Model (DOM) of an HTTPS page

see https://blog.mozilla.org/tanvi/2013/04/10/mixed-content-blocking-enabled-in-firefox-23/

**Comment by RoxKilly** [comment]
@dillbyrne , I learned some useful stuff from your reply.  It's your extension so obviously your vision rules; I just worry that trying to meet broad objectives (prevent fingerprinting specifically, and improve privacy generally) instead of a narrow objective with one piece of software is not a good idea, but I take-away that you see all of this as one objective: *privacy*.

Thanks for taking the time to respond

**Comment by ldgbc** [comment]
@dillbyrne You should add those description in the wiki, currently it doesn't include them.

**Comment by dillbyrne** [comment]
I'll update the wiki when I get a chance. I have changed the settings on the wiki now so it should be editable by anyone if anyone wants to add some information.

**Comment by sucht** [comment]
Block display mixed content 
and
Block active mixed content

is there a chance that those two can be used as an option for whitelisting sites?
i have one or two sites i'd like to enable these two options, while i like to have them disabled for everything else.
