### ISSUE TITLE
Headers - Disable Authorization - Site Login Popup Appeared...

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#261]
When I clicked to Disable Authorization and then visited a site, I was then presented with a user/pass login prompt;

http://i.imgur.com/dWNmfWD.jpg

**Comment by dillbyrne** [comment]
That prompt is common for that site. It's a test it does. You can see that when you select disable Authorization header in RAS that the test results reflect it.


![t](https://cloud.githubusercontent.com/assets/2903711/8748862/36262b02-2c95-11e5-9e72-c0f567667882.png)

So you can ignore that popup. It even says it is a test on it

**Comment by Geyup** [comment]
Ahh ok...
thank you
