### ISSUE TITLE
Disable the insecure ciphers...

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#262]
I haven't been following this for newer versions of Firefox, but there are still versons affected with ```Insecure Ciphers``` listed as ```true``` in ```about:config```

You can do a test to see if you are vulnerable by performing a test at Qualys SSL Labs or weakdh.org;

https://www.ssllabs.com/ssltest/viewMyClient.html
https://weakdh.org/

You might want to consider adding this feature to disable this;

```
security.ssl3.dhe_rsa_aes_128_sha - (default boolean)
true
security.ssl3.dhe_rsa_aes_128_sha  - (user set boolean)
false

***
security.ssl3.dhe_rsa_aes_256_sha - (default boolean)
true
security.ssl3.dhe_rsa_aes_256_sha  - (user set boolean)
false
```

**Comment by dillbyrne** [comment]
Hello @Geyup 

I have an addon specifically for managing and testing your cipher suites , it includes tests for Qualys SSL labs and hows my SSL. 

https://addons.mozilla.org/en-us/firefox/addon/toggle-cipher-suites/

I will not be adding this directly into RAS

**Comment by Geyup** [comment]
Fingerprinting is about the differences in settings that make you stand out.

It's not just about spoofing, or hiding, it's any and all options, that make you more or less identifiable.

As Panopticlick even says; ```Is your browser configuration rare or unique?```

https://panopticlick.eff.org/

Fingerprinting is only about the ```Configuration``` of a browser.

A lot of the settings you have in RAS are more security related for protection, that help by disabling them.

If youi check out version statistics, from what I've read online, only 9% of the browser market for Firefox users are on the latest version...

To be honest I'm not so sure I'd add in this option either, but I would certainly have it mentioned somewhere on your GitHub page to inform users.
