### ISSUE TITLE
Conflicts With NoScript...

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#264]
Using NoScript in combination with RAS gives mixed results...

Meaning, sometimes they are nice togther, and sometimes the online tests results are showing more positive tests with NoScript not running.

Personally I would not want to ever disable NoScript on sites I don't trust, but when it's enabled then features in RAS are not working, I'm assuming because NoScript is blocking javascript, that is needed to make this work...

Examples, below when using JonDONYM test site; http://ip-check.info/?lang=en

1. NoScript enabled ```Browser window``` size detected
2. NoScript disabled no fonts visible
3. NoScript enabled 3 fonts are visible

So if NoScript is enabled then the ```Screen size spoofing``` I do not see working, at least with the results that JonDONYM gives.

If I enable NoScript then my system shows to JonDONYM that I have 3 fonts, and the test results we want, are not fonts visible/detected.

The http://www.browserleaks.com/fonts site you show, if I go there and test, it shows zero fonts, but JonDONYM shows 3, so I'm sure which is more accurate, just that results are varied, so maybe the font option is not working as intended?

**Comment by dillbyrne** [comment]
Hello @Geyup 

They work fine together. NoScript will block script injection by RAS but RAS spoofs on three fronts , script injection, built in preferences and using headers so only the script injection will be blocked but it will still function in other areas. 

The main thing script injection is used for is the canvas blocking , the screen and window attributes, the date spoofing and the whitelist. If you are using no script then sites will not be able to read these anyway so it is fine.

The reason jondonym is able to read the screen when no script is enabled is that it is using a CSS font hack to determine the size so it is bypassing javascript in this case. It is also using it to check for fonts. I have an issue open for this , I need to find a way to block or limit calls to `@font-face`. That is how NoScript blocks it I assume. 

The fonts preference in RAS will limit the browser to use three fonts only, it uses `browser. display. use_document_fonts` . There is an issue open to improve this but in terms of the built in options that is the best we can do for now until I can figure out how to limit the font face calls.

**Comment by Geyup** [comment]
I don't see with NoScript enabled a screen size, only the window size of Firefox is being reported...

**Comment by dillbyrne** [comment]
Sorry I meant window size, you're correct.

As there is no conflict with noscript I'm closing this issue. I have an [issue](https://github.com/dillbyrne/random-agent-spoofer/issues/104) open for the font detection method .
