### ISSUE TITLE
Update Browsers

### ISSUE THREAD

**Issue by airborne01** [dillbyrne/random-agent-spoofer#265]
Hello it's possibel to upadate the browsers manually.
example the last ipad cpu os is 8.1.1 on PSD, but on a new ipad is the cpu 8.3.
can wi upgrade that thanks you do great job : )
regards Airborne

**Comment by dillbyrne** [comment]
Hello @airborne01 . See https://github.com/dillbyrne/random-agent-spoofer/wiki/How-To-contribute and the section about browser profiles and post the information in this issue and I will add it .

**Comment by dillbyrne** [comment]
The latest ipad version in 0.9.5.5 is 8.4 .I'll be doing an update of profiles again soon
