### ISSUE TITLE
Hide / Spoof 'Hostname' & ISP

### ISSUE THREAD

**Issue by lukanblake** [dillbyrne/random-agent-spoofer#267]
Hi,

Is there anyway to edit the hostname on my server for each IP? at the moment - the hostname field links all my IP's together as the ISP has entered their name URL: random.com followed by my main IP number, which is really annoying. 

I've been using your fantastic plugin to spoof all of the other data I need, but just these two fields left which I can't seem to edit.

thanks!

**Comment by RoxKilly** [comment]
This is really interesting; where do you see the hostname?  Could you give an example of a URL you go to, and which hostname is displayed? 

Also, your post mentions two fields which you can't seem to edit. If hostname is the first, what's the second?

**Comment by alct** [comment]
Hello,

> Is there anyway to edit the hostname on my server for each IP? at the moment - the hostname field links all my IP's together as the ISP has entered their name URL: random.com followed by my main IP number, which is really annoying.

I'm not sure to get what you mean. Are you talking about reverse DNS?

Anyway, when it comes to IP addresses, RAS is not the right tool (check TOR, TORBrowser and/or VPNs).

**Comment by dillbyrne** [comment]
@lukanblake can you clarify what you mean ? with an example , obviously use a false ip and not your own in the example.

I read a while back verizon was injecting headers into requests https://www.eff.org/deeplinks/2014/11/verizon-x-uidh

if it is at the header level it is trivial to block it.

**Comment by lukanblake** [comment]
Hi,

Thanks for getting back to me.

I have attached an example of what I want to spoof.

I can't use a vpn or proxy to spoof this. The IP must stay the same, but 
if poss - change the criteria in the box highlighted, especiallly the 
'hostname'

thanks!

**Comment by dillbyrne** [comment]
@lukanblake 

I meant in your *example* don't post your IP but use a fake one instead. if you are attaching an image then you can use gimp to blur out all or certain ranges of your IP for example.

> I have attached an example of what I want to spoof. 

There was no example attached. Can you try again  ?

**Comment by lukanblake** [comment]
Hi,

So sorry for the delay in getting back to you about this. I've been away with work.

Have added the example to imgur: https://imgur.com/i5tL6qf

So, anyway to spoof the information inside the pink box? without using a proxy or vpn? I need my  IP to be my real IP. The IP range (inside the box) can stay the same - but I was wondering if it might be possible to change the ISP hostname, ISP, organisation fields?

thanks

**Comment by alct** [comment]
Hello,

> So, anyway to spoof the information inside the pink box?

So, I got it right the first time, see my previous answer.

These information are obtained through reverse DNS, AS lookups etc based upon your IP address. You can not spoof these info without changing/spoofing your IP address.

RAS is not the right tool for that.

**Comment by lukanblake** [comment]
ok, no probs that's what I thought. Just wanted to check
One other question. When I close down firefox and reopen again, a new (different) configuration (linux/windows /chrome/opera etc) is automatically chosen....is there anyway to ensure it selects the same user profile each time?
Thanks 


     On Friday, August 21, 2015 6:09 PM, alct <notifications@github.com> wrote:
   

 Hello,
So, anyway to spoof the information inside the pink box?
So, I got it right the first time, see my previous answer.These information are obtained through reverse DNS, AS lookups etc based upon your IP address. You can not spoof these info without changing/spoofing your IP address.RAS is not the right tool for that.—

**Comment by RoxKilly** [comment]
@lukanblake 
>.is there anyway to ensure it selects the same user profile each time?

1. Open RAS settings at the `Profile` tab.  
2. Set the `Change periodically` dropdown menu to `no`
3. Below the radio buttons is a list of browser types `Windows`, `Mac`, `Linux`...  Expand the browser type you are interested in.
4. Use the radio buttons to the left of the browser profile names to select the profile that you want RAS to use every time.

Please note that unless you have a specific reason for wanting a consistent profile, using the same profile every time can significantly reduce your privacy by making you easy to track.  Although trackers will have a difficult type knowing your real browser, they will be able to follow you by your consistent fake profile.

You can also use the options on the `Profile` tab to exclude browser profiles you are not interested in, and force RAS to select from a limited number of profiles that fit your needs.  Privacy-wise, this is better than using the same profile all the time.

**Comment by dillbyrne** [comment]
@alct Thanks again :+1: 

@lukanblake you can simply

1. Open RAS settings at the Profile tab.

2. Below the radio buttons is a list of browser types Windows, Mac, Linux... Expand the browser type you are interested in.
    
3. Use the radio buttons to the left of the browser profile names to select the profile that you want RAS to use every time.

@RoxKilly  RAS will stay on that particular browser until you specifically  select another one. The timer is not used when a specific browser is selected so you do not need to change it when using a specific profile
