### ISSUE TITLE
Option to Disable Profile Change Notifications

### ISSUE THREAD

**Issue by GitHubbyDude** [dillbyrne/random-agent-spoofer#268]
The plugin keeps telling me it changed profile. I don't care. Please provide a way for us to turn that off.

**Comment by luxoflux** [comment]
The option is already there. Find Random Agent Spoofer in the Add-ons Manager and click Options, then uncheck *Show notifications*).

**Comment by dillbyrne** [comment]
@luxoflux Thanks :+1:
