### ISSUE TITLE
How to deselect a browser from random(desktop)

### ISSUE THREAD

**Issue by potholiday** [dillbyrne/random-agent-spoofer#269]
I have problem with an app when RAS uses chrome/chromium as an user agent. Currently i select random(desktop) option to spoof my firefox but the problem is i cant deselect chrome browser from it. Can you tell me how i can deselect chrome browser alone from random (desktop) operating systems dont matter

**Comment by alct** [comment]
Hello,

> the problem is i cant deselect chrome browser from it

You can, yet not in an optimal manner: once you have selected one of the "random profile" option, you can exclude any browser by expending operating systems and checking the exclude box right next to the item that you do not want to be taken into account (for the time being, you have to do it for each and every OS/platform).

**Comment by potholiday** [comment]
@alct  thanks its a bit lengthy process. any way thanks

**Comment by dillbyrne** [comment]
@alct Thanks :+1: 

@potholiday if it is on a particular site you can select a specific firefox profile or you can use the whitelist.
