### ISSUE TITLE
Remove Toggle based system so RAS uses built in about:config options directly

### ISSUE THREAD

**Issue by requiredregistration** [dillbyrne/random-agent-spoofer#27]
disable geolocation support
disable dns prefetching
disable link prefetching

clicking in the options of RAS doesn't toggle the options in about:config

**Comment by dillbyrne** [comment]
A quick update on this. I am  working on removing the toggle system for this issue . This relates to the option to enable or disable RAS from within the addon. Users will still be able to select the default profile to disable profile spoofing but this will not toggle the extras as the enable/disable system did. They must be toggled individually. 

This has a number of advantages.

It will lead to less user confusion
it will reduce  code as intermediary states do not need to be stored
it will make RAS easier to maintain
It will allow for new options to be added quickly.
it will reduce the memory footprint as there are less options needed to store

The option to completely disable the addon is still present using the addon manager's built in system.

The toolbar icon will be gray on the default profile and blue on all the others to indicate when profile spoofing is active or not, in addition to the tooltips and notifications. Extras are not toggled unless a user specifically toggles the option.
 
I have most of the work done on this but there are still some things I have to fix and test. I will update this issue when I have it working
