### ISSUE TITLE
Disable RAS - Options Revert

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#270]
In Linux using FIrefox 31.8.0 ESR, if I disable RAS, when I reneable it, all the options have reverted back to default settings, like when you start it for the first time...

**Comment by RoxKilly** [comment]
This has happened to me several times on Firefox as well (FF 38).

**Comment by Geyup** [comment]
I forgot to mention, I meant disable from the, Tools > Addons > Disable

Because if I click on Profile > Real Profile which I assumed meant to also disable it doesn't seem to be working, it appears to continue to use options...

**Comment by danielcra** [comment]
There used to be an option in the RAS GUI of version 0.9.5.1 to disable RAS completely without losing the settings.

Anyway, I agree there needs to be an easy way to disable RAS, because many web sites simply do not work when it is active.

I am so far staying on 0.9.5.1, but as soon as FF starts requiring signed extensions I am going to have an issue because the old version is not signed.

**Comment by kekkc** [comment]
Discovered the same. Even more so, accoroding to the changelog, RAS should use all current specified options within Opetions -> Standard Options when you activate it again Tools > Addons > Activate. But it doesn't for me for Disable clipboard events & Disable contextmenu events. No matter if they're activated in FF, RAS will overwrite and deactivate them. And they stay deactivated if RAS is deinstalled. This is serious and shouldn't happen.

**Comment by dillbyrne** [comment]
see  #127 .  https://github.com/dillbyrne/random-agent-spoofer/wiki/Bug-reporting-guide

**Comment by Geyup** [comment]
Hi,

Who's the bug reporting url for?

Sorry I didn't add in version; 0.9.5.3 I'm using...

So is this a bug being working on?

Thanks

**Comment by dillbyrne** [comment]
The bug report url is for recommended practices when reporting a bug, one of which is to check for duplicates before posting. It has been added to the 0.9.5.5 milestone

**Comment by Geyup** [comment]
ok...
