### ISSUE TITLE
Github and RAS's Future

### ISSUE THREAD

**Issue by ldgbc** [dillbyrne/random-agent-spoofer#271]
With the decent aggressiveness ethnic conduct of Github including; removing repo, forcing maintainer to change their code. censorship, forcing user to follow a certain tone of voice/writing, etc.

Will RAS consider moving to a more open and free platform such as Gitlab.com or Gitgud.net?

**Comment by dillbyrne** [comment]
@ldgbc I have a local copy and backups , there is no reason to assume RAS would be removed from github and in the event that it was, it would be trivial to get it back up and running. 

I know from past experience that gitlab can bring browsers to a crawl on a issue with many comments which a project such as RAS is sure to attract from time to time so from an infrastructure point of view github is better suited. 

So I will not be moving RAS at this time, anyone is free to mirror it there if they wish though.
