### ISSUE TITLE
How to save settings?

### ISSUE THREAD

**Issue by D1GITALelementz** [dillbyrne/random-agent-spoofer#273]
Is there an option to save settings?.... it's a little tedious to check off all the browsers and others i want to exclude every time i reinstall the plugin.

..btw.... plugin icon not visible on Light (firefox browser) upgrade to v4.0

Any help much appreciated... =]

**Comment by RoxKilly** [comment]
I also think this option would be great.  From a user experience perspective, this is really close to #270

**Comment by D1GITALelementz** [comment]
..or maybe just a select all option.. would be nice...=]

**Comment by RoxKilly** [comment]
Saving settings through uninstall-reinstall cycle may be a bad idea. Usually when I uninstall a program, I want to remove all traces of it, unless I expressly allow settings to remain.  Maybe a simple option would be to add export/import (or backup/restore) functionality to the settings. We then export -> uninstall -> reinstall -> import.

**Comment by D1GITALelementz** [comment]
Yep, import / export settings like you're able to do with the NoScript plugin and others ... that's exactly what I meant  - a saved settings file... =]

**Comment by dillbyrne** [comment]
The addon is not designed to be uninstalled and reinstalled every time. In fact AMO guidelines specify that an addon should always clear its settings when it is uninstalled. Also it is good general programming practice to do so. 

You could use a `user.js` file to set/reset any preference http://kb.mozillazine.org/User.js_file

I will be adding a built in toggle based system back into RAS so you will be able to completly enable/disable the addon using the mouse menu.  This will save settings in separate temporary preferences when the state is set to disabled and copy the temporary preferences to the original preferences when it is re-enabled achieving what you want.

See #272 for more on this.

**Comment by dillbyrne** [comment]
>..btw.... plugin icon not visible on Light (firefox browser) upgrade to v4.0

@D1GITALelementz  can you provide a screenshot and more information see https://github.com/dillbyrne/random-agent-spoofer/wiki/Bug-reporting-guide

**Comment by D1GITALelementz** [comment]
Many thanks for the reply, and the toggle feature would be most helpful.. =] 
...I've been trying out different browser builds... from Light (a cut down version of firefox) and also Pale Moon.... trying get all my favourite plugins working without issue, as well as finding a browser version with minimal other issues, which is why i have been uninstalling / reinstalling quite a bit lately.

(Then I install my addons again, incl. RAS) ......... the way I use RAS at the moment is, Random Desktop only... and I exclude all but the latest few browser builds of each browser, on each desktop platform.... thinking that might offer the least amount of grief with websites ...... so there has been quite a bit of checking off boxes I've been doing.
(I've got no real problem with doing that, but even a bulk select / select all / deselect all option might be useful?)

-------------

RAS installs on Light (firefox) v4.0, 
https://sourceforge.net/projects/lightfirefox/files/?source=navbar

....but the icon for it that should be visible on the toolbar somewhere is not showing, and it's not in "Customise" > "Additional Tools and Features" either,

...sometimes icons get sent to the status bar, but the status bar feature is not available..or has been cut in Light v4.0 in favour of further browser slimming. :S

Works fine with Pale Moon though... :D
