### ISSUE TITLE
general.useragent.override removed with Firefox 39.0.3+

### ISSUE THREAD

**Issue by CHEF-KOCH** [dillbyrne/random-agent-spoofer#275]
Seems that the <code>general.useragent.override</code> string doesn't exist anymore by default. The big questions seems if it still works to re-enable this settings with future FF builds (40 stable coming). 

Or do we need new tricks? I not checked the ESR build yet but I guess it's also removed there.

**Comment by dillbyrne** [comment]
@CHEF-KOCH  We can send the user agent header manually if it does affect it, like we do for whitelisted sites and we still inject it in the page too so we have no cause for worry.

Where did you see that it was removed ? 

I see no mention in the firefox 40 addon compatibility notes. It could be the case that it is still a preference but it has to be manually defined. 

It still works for now, you can test it by disabling script injection  and changing the preference manually to a random string, then load `browserspy.dk/browser`

I'm closing this for now as it still works. If it stops working then feel free to reopen it and I'll send the header manually.
