### ISSUE TITLE
Network.websocket.enabled?

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#280]
Hi dillbyrne,

I just noticed that `network.websocket.enabled` is no longer in Firefox. Is there something that is replacing this? I had this disabled before, so if there is some equivalent replacement, I might want to disable it as well...

I do see there is this; `dom.workers.websocket.enabled`

thanks

**Comment by dillbyrne** [comment]
@Geyup `dom.workers.websocket.enabled` is only about websocket support in workers not websocket support in general which is built into firefox. The only way to remove it is to compile a custom version of the browser with that code removed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1091016

Having said that we could probably use script injection to override the websocket constructor to return `undefined` when invoked in webpages.

This would not be 100% but it should work well enough for a lot of cases. 

https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications

**Comment by Geyup** [comment]
ok

**Comment by dillbyrne** [comment]
I have added an option to disable websockets and they can also be whitelisted if needed
