### ISSUE TITLE
Support Firefox WebExtensions API

### ISSUE THREAD

**Issue by JeffD800** [dillbyrne/random-agent-spoofer#282]
If this comes true (link below), will RAS still be able to exist as we know it?

http://arstechnica.com/information-technology/2015/08/mozilla-sets-plan-to-dump-firefox-add-ons-move-to-chrome-like-extensions/

**Comment by dillbyrne** [comment]
Hello @JeffD800 . 

RAS uses  the jetpack APIs and not the XUL based APIs which is what mozilla are dropping support for. They have said they will continue to support the jetpack APIs into the future so RAS should be fine as long as they keep to their word.

**Comment by dillbyrne** [comment]
[There are no plans to deprecate the Addon SDK in its current form at this time. It’s already Electrolysis compatible (although, per above, the use of require(‘chrome’) will not be supported). However, we expect that most of our effort will be directed towards extending WebExtensions to meet developer’s needs. Some of these APIs may be ported to Jetpack as needed, but WebExtensions will be our favored platform.](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/comment-page-1/#comment-218588)

Based on the above RAS will be severely crippled based on their plans. It looks as if their end goal is to move towards the WebExtensions completely, despite them saying months ago that the addon sdk was *the* way to make addons. 

They have stated that WebExtensions will also not allow `require("chrome")` access .

At the very least RAS needs to be able to override the headers otherwise the user will stand out due to mismatches in the profile. If there is no way to do this then RAS will be done.

**Comment by Balloon2mars** [comment]
Palemoon is the future... Mozilla wants to completely destroy firefox... PLEASE just make RAS for Palemoon!

**Comment by kekkc** [comment]
>At the very least RAS needs to be able to override the headers otherwise the user will stand out due to mismatches in the profile. If there is no way to do this then RAS will be done.

Seems that this is already guaranteed and fully supported already:
https://wiki.mozilla.org/WebExtensions#List_of_supported_APIs
https://developer.chrome.com/extensions/webRequest

onBeforeSendHeaders (optionally synchronous)
    Fires when a request is about to occur and the initial headers have been prepared. The event is intended to allow extensions to add, modify, and delete request headers (*). The onBeforeSendHeaders event is passed to all subscribers, so different subscribers may attempt to modify the request; see the Implementation details section for how this is handled. This event can be used to cancel the request.

The following example illustrates how to delete the User-Agent header from all requests:

      chrome.webRequest.onBeforeSendHeaders.addListener(
        function(details) {
          for (var i = 0; i < details.requestHeaders.length; ++i) {
            if (details.requestHeaders[i].name === 'User-Agent') {
              details.requestHeaders.splice(i, 1);
              break;
            }
          }
          return {requestHeaders: details.requestHeaders};
        },
        {urls: ["<all_urls>"]},
        ["blocking", "requestHeaders"]);

**Comment by dillbyrne** [comment]
@kekkc That is specifically for web extensions, I was talking about the addon SDK.  RAS and all of my other addons are designed to work with the addon SDK . Moving to webextensions would require a rewrite of most of the code in each of them. Also at this point in time some of the API's RAS uses don't even exist in the webextensions API such as context menu.

Honestly I have no desire to port 11 extensions to use the webextensions API. I'm now waiting **over three months** to have a now outdated version of RAS approved on AMO and like xpcom and now the [addon sdk](https://discourse.mozilla-community.org/t/confused-about-require-chrome-support/3630) we have no guarantee that they will not change their minds yet again once web extensions are the recommended method to use. 

Even if I wanted to port my addons to use webextensions the APIs are still in development and the level of flexibility will no doubt be much more restrictive going forward. Either way there is not much point in adding new features to RAS now if I will have to rewrite it again in a few months. 

I will keep the SDK  based addons going for now and with respect to RAS I plan to release 0.9.5.4 soon and support that with minor changes until the removal of support for require("chrome"). As mentioned above there is no point in me adding major changes if it will require a rewrite or be deprecated so for now the changes planned for 0.9.5.5 and onwards are postponed for now.  

When I have more information about the capabilities of the web extensions API I will make a decision about the future of RAS and my other addons.

**Comment by dillbyrne** [comment]
I won't be porting my addons to use web extensions. I'll keep RAS going until support for require("chrome") is dropped. I won't be supporting pale moon or seamonkey as they use incompatible components such as widget.

**Comment by captainhook** [comment]
Has your decision on this changed, since Firefox 57 is around the corner?
