### ISSUE TITLE
Screen size spoofing doesn't work

### ISSUE THREAD

**Issue by gemapo** [dillbyrne/random-agent-spoofer#284]
Hi.

Using latest tor browser, java & flash disabled, w/RAS. Screen size spoofing is set to Random, but http://ip-check.info/ can still show the real screen size, changing it in real time if I change the window size while on site.

**Comment by dillbyrne** [comment]
Hi @gemapo  please see issue #104 for more on this, it is not using javascript but a css font hack  to get the window size.
