### ISSUE TITLE
Icon missing on FF version 40

### ISSUE THREAD

**Issue by kyhunt** [dillbyrne/random-agent-spoofer#285]
I have installed RAS on a fresh install of FF v 40.0.3. The icon is missing from my toolbar.
Other addons I have installed:
* uBlock Origin
* noScript
* Better Privacy
* HTTPS everywhere
* RefControl
* LastPass

**Comment by RoxKilly** [comment]
That's interesting.  I had the same problem with the uBlock Origin addon on FF 40.0.3.  The icon wouldn't show in the toolbar even though the addon was installed and enabled.  The RAS icon showed ok though.  Maybe an issue with FF?  Or a conflict with uBlock Origin?  I don't know.

I ended up re-installing uBlock Origin and the icon appeared once more.

**Comment by dillbyrne** [comment]
@kyhunt What version of RAS are you using ? the one on AMO (0.9.3.1.1-signed)  is using the old widget API which has been deprecated. I have a version on AMO to fix this but it has been in the review queue for over three months now . If you are using the AMO version and don't want to wait until they decide to review it you can install the github version at https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.3

**Comment by dillbyrne** [comment]
There is a new version on AMO that uses the new API. It took a very long time to be reviewed but it should work. I'm closing this issue now as you didn't get back to me. Feel free to reopen it if the issue persists with the newer version
