### ISSUE TITLE
Whitelist to display current default browser.

### ISSUE THREAD

**Issue by Chris344** [dillbyrne/random-agent-spoofer#286]
Hi, 

Sorry for the dumb question. Is there an option to set the whitelist to use the current default browser rather than some manually specified browser? If not, is it possible to add such feature/option?

**Comment by dillbyrne** [comment]
Hi @Chris344 . It is not a dumb question.

I intentionally allow the whitelist to be manually set and by default set it as the latest stable firefox version for widows at the time of release for that version of RAS. 

I did not set it to automatically get the current default in the event that a user did not want to divulge their actual browser information. For example a linux user may want to keep the profile as a windows version of firefox or vice versa, updating using the actual profile will break this . 

I do update them as I mentioned with each release, so if the default has not changed then they are updated. This particular release has taken much longer than anticipated as I am waiting to hear feedback from mozilla but in general I try to keep the updates frequent enough to match the releases.

Im sure it is possible to add such functionality but it is not as simple as checking a single string and as such I prefer to keep it the way it is and issue the updates with new releases.

**Comment by Chris344** [comment]
Thanks for the answer. IF you try to keep the browser up to date for the whitelisted site/browser info when you update the addong, it's fine too. I was just worried about ended up with an obsolete browser as browser info for the whitelisted sites.

**Comment by dillbyrne** [comment]
A valid concern. I have actually updated it to 42 for the upcoming release https://github.com/dillbyrne/random-agent-spoofer/commit/467b3c30102d28b970305a817853b23142b7e9e4
