### ISSUE TITLE
show which profile is currently in use

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [dillbyrne/random-agent-spoofer#293]
would be nice if at the bottom of the profile tab, it showed some information on the current profile being used, as in, whichever random profile was last chosen which affects the current page, or if its whitelisted, show that

**Comment by dillbyrne** [comment]
RAS has this feature for a long time. The current profile is shown in a tooltip when you place your mouse over the icon in the toolbar. See screenshot below

![smoothie1](https://cloud.githubusercontent.com/assets/2903711/10021589/9caab354-6140-11e5-809e-9f8418bc1c60.png).

**Comment by berrythesoftwarecodeprogrammar** [comment]
oh true! cool :)
