### ISSUE TITLE
Disabling of the notifications

### ISSUE THREAD

**Issue by spekulatius** [dillbyrne/random-agent-spoofer#299]
I'm using it on a Linux Mint and get regular notifications about the changes of the agent. I would like to keep the time down, yet the notifications annoy me too much. Would it be possible to include a option to disable the notifications?

**Comment by rimmington** [comment]
As noted in the README, there's a preference in `about:addons` -> Random Agent Spoofer -> Preferences. I had to search around for the option as well.

**Comment by spekulatius** [comment]
Ah, okay. I wasn't aware there are more options. Thank you @rimmington !

**Comment by dillbyrne** [comment]
Thanks @rimmington :+1:
