### ISSUE TITLE
Screen size spoofing failed in direct navigation

### ISSUE THREAD

**Issue by ZIEXED** [dillbyrne/random-agent-spoofer#302]
This site was able to detect my real screen resolution
http://www.whatismyscreenresolution.com/
When this site is opened from google it can't detect your real resolution
But if you navigate to this site directly it will gain your resolution every time

While this site ↓ can't detect it in both cases and working fine :+1: 
http://www.screenresolution.org/

thanks for your work (:

**Comment by SINE** [comment]
I can agree that this seems not to work in every case.
Example: http://ip-check.info

If you start a test there, and scroll down very quickly, the test will tell the real window resolution.
After a while, the rest of the test will be finished, then it will display a different resolution.

**Comment by dillbyrne** [comment]
This is fixed with the latest screen code and will be available in the next release. Thanks for reporting this. :+1:
