### ISSUE TITLE
Clicked links don't grey out.

### ISSUE THREAD

**Issue by grrrrrr** [dillbyrne/random-agent-spoofer#304]
Installed RAS and now clicked links no longer change colour.
Running FF 41.0.2

**Comment by RoxKilly** [comment]
In the `Options` tab of RAS menu, scroll all the way down and uncheck `Disable CSS visited links`

**The benefit**: Changing link appearance after you've visited a page allows you to see at a glance which pages are in your browsing history.

**The trade-off**: If links change after you click them, a site will be able to determine which pages are in your browsing history by looking at the formatting of links.

**Comment by grrrrrr** [comment]
Thanks mate.
Can't believe I missed that option.

**Comment by RoxKilly** [comment]
You're welcome

**Comment by evaryont** [comment]
@RoxKilly FYI, this is less effective than it used to be. IIRC, accessing a link's color will now always return it's regular link color.

**Comment by RoxKilly** [comment]
Thanks I wasn't aware of this; it highlights why Firefox has remained my browser of choice.

**Comment by dillbyrne** [comment]
@evaryont Thanks for this. I can remove the preference in that case.
