### ISSUE TITLE
Screen Size Spoofing Always Easily Detected With iframe.contentWindow

### ISSUE THREAD

**Issue by stevensebaweg** [dillbyrne/random-agent-spoofer#309]
No matter what size/setting the Screen Size Spoofing option is set at, the real OS screen size is always easily detected using an easy Browserleaks.com javascript.

1. Visit the page: http://www.browserleaks.com/javascript
2. click the "iframe.contentWindow" button and notice that the "Screen Resolution" will show the real OS sizes no matter what setting the RAS is set at.

**Comment by elsagecien** [comment]
I am also interested in solving this issue, so if anybody have an idea of how access and alter the information in iframe.contentWindow object/proprety, let us know

**Comment by berrythesoftwarecodeprogrammar** [comment]
probably the same way the current properties are changed? whats changed right now?

**Comment by dillbyrne** [comment]
The new screen spoofing code also handles iframes and fixes this issue. Thanks for reporting it.

**Comment by stevensebaweg** [comment]
Thats good to hear. Can you tell me if the new version is available on github now?

**Comment by dillbyrne** [comment]
@stevensebaweg The current code has been commited to the master branch but I have not yet found a way to spoof window.name and window attributes such as window.innerHeight. Also the date spoofing has to be redone and the whitelist needs to be fixed too. 

There are some other issues that will be easier to fix that need to be taken care of too but my main focus has been on restoring the lost functionality.  Also the profiles will need to be updated before the next release.
