### ISSUE TITLE
Where are the new releases?  0.9.5.3 is from May 2015.  

### ISSUE THREAD

**Issue by opav** [dillbyrne/random-agent-spoofer#311]
Where can I find more current releases since 0.9.5.3's May release?

The profiles are woefully behind in the browser version.  Using these old version profiles is bad for fingerprinting.

**Comment by dillbyrne** [comment]
I plan to release 0.9.5.4 soon. The signing requirements coupled with the long AMO queues held up this release as I was waiting on feedback from the AMO reviewers about getting the full addon hosted on AMO again. In addition to that I have had other obligations that kept me busy.
