### ISSUE TITLE
No Ads showing on YOUTUBE

### ISSUE THREAD

**Issue by sansanwal** [dillbyrne/random-agent-spoofer#316]
No Ads showing on YOUTUBE..no skip ads, nothing....

**Comment by B00ze64** [comment]
And this is ... bad ?

**Comment by Gitoffthelawn** [comment]
@B00ze64 I thought maybe I was the only one who didn't understand. ;-)

**Comment by dillbyrne** [comment]
I don't know why anyone would want this but it could be the tracking protection option in the standard options section.

You should know that ads can be used to [track you] (https://www.eff.org/deeplinks/2009/09/online-trackers-and-social-networks) and [attack you] (https://en.wikipedia.org/wiki/Malvertising)
