### ISSUE TITLE
Whitelist addons.mozilla.org

### ISSUE THREAD

**Issue by flyingzebras** [dillbyrne/random-agent-spoofer#317]
https://github.com/dillbyrne/random-agent-spoofer/issues/305
https://github.com/dillbyrne/random-agent-spoofer/issues/318
https://github.com/dillbyrne/random-agent-spoofer/issues/314#issuecomment-155081714

**Comment by flyingzebras** [comment]
Whitelist says: ```The options in this section are only available in the github version``` so the ```Enable whitelist support``` cannot be enabled for me as I'm using the AMO (https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/) version of Random Agent Spoofer

**Comment by Kwaadpepper** [comment]
```about:accounts``` needs to be white listed somehow i guess because Firefox Sync could not work properly with this plugin.

**Comment by flyingzebras** [comment]
@Kwaadpepper Good point!

**Comment by dillbyrne** [comment]
@flyingzebras  the Whitelist says: The options in this section are only available in the github version for a reason, The whitelist requires script injection and that was the reason for the split into GH and AMO versions. I have added addons.mozilla.org to the whitelist but it will only work in a version that has scripot injection enabled. The canvas option is not needed.

I hope to get the full version of RAS back on AMO for the next release

**Comment by flyingzebras** [comment]
@dillbyrne Thank you.

**Comment by davidhedlund** [comment]
What is the status of this issue @dillbyrne?

**Comment by davidhedlund** [comment]
[mylabel:enhancement](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aenhancement%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment]
@dillbyrne Can you please label this issue duplicate of https://github.com/dillbyrne/random-agent-spoofer/issues/305 ?
