### ISSUE TITLE
Enable Whitelist for AMO version of RAS

### ISSUE THREAD

**Issue by flyingzebras** [dillbyrne/random-agent-spoofer#318]
Whitelist says: ```The options in this section are only available in the github version``` so the ```Enable whitelist support``` cannot be enabled for me as I'm using the AMO (https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/) version of Random Agent Spoofer

**Comment by flyingzebras** [comment]
https://github.com/dillbyrne/random-agent-spoofer/issues/305
https://github.com/dillbyrne/random-agent-spoofer/issues/317

**Comment by dillbyrne** [comment]
See #317

**Comment by davidhedlund** [comment]
@dillbyrne Can you please label this issue duplicate of https://github.com/dillbyrne/random-agent-spoofer/issues/305 ?
