### ISSUE TITLE
Add more language

### ISSUE THREAD

**Issue by Machou** [dillbyrne/random-agent-spoofer#319]
Hello

Possible to add more language ? (fr-FR, de-DE, ru-RU, pt-BR)

Thanks :)

**Comment by dillbyrne** [comment]
@Machou do you mean in th euser interface or in the browser headers ?. If it is the browser headers then there is already some support for specifying the accept language headed language

**Comment by dillbyrne** [comment]
@Machou do you mean in th euser interface or in the browser headers ?. If it is the browser headers then there is already some support for specifying the accept language headed language

**Comment by Machou** [comment]
User Interface :D

**Comment by dillbyrne** [comment]
@Machou I had the addon localized at one stage but when it came to CSS the different proportions of certain languages made the UI look bad and most of the language is technical in nature. See #195
