### ISSUE TITLE
TonyA79/random-agent-spoofer

### ISSUE THREAD

**Issue by TonyA79** [dillbyrne/random-agent-spoofer#322]
I don't have a check box for disable widgets.

**Comment by TonyA79** [comment]
I have Win.8.1 64-bit,Portable Firefox 42

**Comment by dillbyrne** [comment]
Hi @TonyA79 . If you are talking about the disable options mentioned at https://github.com/dillbyrne/random-agent-spoofer/issues/272 that is because that version is not yet ready for release.
