### ISSUE TITLE
Future of GitHub version with Firefox addon verification

### ISSUE THREAD

**Issue by tmar33** [dillbyrne/random-agent-spoofer#330]
Hi, thanks for your awesome addon. I'm using the Github version with script injection, and I'm wondering what will happen to this when Mozilla starts de-activating unsigned addons.  Will you be able to have the Github version signed even if it's not approved for the AMO site? I hope the functionality of this addon isn't lost as Mozilla transitions to their new plan.

Sorry BTW for using the "Issues" forum to ask this question. But I figure the answer will be of general interest.

**Comment by dillbyrne** [comment]
Hi@tmar33 

I am currently testing the upgrade code from both the current AMO and current github releases to a full version which I intend to upload to AMO. I have made changes to the script injection code after talking to AMO editors. See #325 and #228

So I intend to get the full version back on AMO which will be signed
