### ISSUE TITLE
feature: show user-agent in menu

### ISSUE THREAD

**Issue by hendrickbert** [dillbyrne/random-agent-spoofer#331]
As far as i know the only way to know which user agent is active is by a (anoying) notification. Add this information in the menu of the addon.

Good job!

**Comment by dillbyrne** [comment]
The notifications can be disabled and the current profile is shown if you mouse over the toolbar icon. 


![icon mouse over](https://addons.cdn.mozilla.net/user-media/previews/full/166/166830.png)

**Comment by anoadragon453** [comment]
Huh, I didn't even know this.

Maybe some grey text telling the user "hover over icon to see current UA" in the Profile menu would help? UX and all.

**Comment by dillbyrne** [comment]
@anoadragon453 I am still writing the user manual for 0.9.5.4.

**Comment by dillbyrne** [comment]
@anoadragon453 I have added it to the wiki in the profile section. Thanks for you input and sorry about the delay

**Comment by anoadragon453** [comment]
@dillbyrne No problem, glad to see it implemented.
