### ISSUE TITLE
Linux Firefox GLib-CRITIALand GLib-GObject-WARNING when running from terminal

### ISSUE THREAD

**Issue by DistantParadox** [dillbyrne/random-agent-spoofer#333]
When running Firefox 42.0 from the terminal in Linux Mint 3.19.0-generic #34~14.04.1~Ubuntu SM, it causes the following errors which when disabled, it does not:

user@Basically-a-Toaster ~ $ firefox

(process:3628): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed

(firefox:3628): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::sm-connect after class was initialised

(firefox:3628): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::show-crash-dialog after class was initialised

(firefox:3628): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::display after class was initialised

(firefox:3628): GLib-GObject-WARNING **: Attempt to add property GnomeProgram::default-icon after class was initialised console.error:  Could not read session file    Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/recovery.js (Permission denied)    console.error:    Could not read session file   Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/recovery.bak (Permission denied)    console.error:    Could not read session file   Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/previous.js (Permission denied)    console.error:    Could not read session file   Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/upgrade.js-20150826185918 (Permission denied)    console.error: random-agent-spoofer:    Message: Module `sdk/widget` is not found at resource://gre/modules/commonjs/sdk/widget.js   Stack:
    CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 @resource://jid1-avgcef1zovzmja-at-jetpack/random-agent-spoofer/lib/Widget.js:1:14 CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 @resource://jid1-avgcef1zovzmja-at-jetpack/random-agent-spoofer/lib/Ras.js:1:14 CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 @resource://jid1-avgcef1zovzmja-at-jetpack/random-agent-spoofer/lib/Panel.js:3:11 CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 @resource://jid1-avgcef1zovzmja-at-jetpack/random-agent-spoofer/lib/main.js:1:1 CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19 startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7 Handler.prototype.process@resource://gre/modules/Promise-backend.js:922:23 this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:801:7 this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:740:39

console.error: random-agent-spoofer:    Message: Module `sdk/widget` is not found at resource://gre/modules/commonjs/sdk/widget.js   Stack:
    CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 @resource://jid1-avgcef1zovzmja-at-jetpack/random-agent-spoofer/lib/Widget.js:1:14 CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 @resource://jid1-avgcef1zovzmja-at-jetpack/random-agent-spoofer/lib/Ras.js:1:14 CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 @resource://jid1-avgcef1zovzmja-at-jetpack/random-agent-spoofer/lib/Panel.js:3:11 CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 @resource://jid1-avgcef1zovzmja-at-jetpack/random-agent-spoofer/lib/main.js:1:1 CuddlefishLoader/options<.load@resource://gre/modules/commonjs/sdk/loader/cuddlefish.js:79:18 run@resource://gre/modules/commonjs/sdk/addon/runner.js:145:19 startup/</<@resource://gre/modules/commonjs/sdk/addon/runner.js:86:7 Handler.prototype.process@resource://gre/modules/Promise-backend.js:922:23 this.PromiseWalker.walkerLoop@resource://gre/modules/Promise-backend.js:801:7 this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise-backend.js:740:39

console.error:    Could not write session state file    Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/recovery.js.tmp (Permission denied)    console.error:    Could not write session state file    Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/recovery.js.tmp (Permission denied)    console.error: privacybadger:    Policy document request to https://ajax.googleapis.com/.well-known/dnt-policy.txt returned with status 404 console.error:    Could not write session state file    Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/recovery.js.tmp (Permission denied)    console.error:    Could not write session state file    Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/recovery.js.tmp (Permission denied)    console.error:    Could not write session state file    Message: Unix error 13 during operation open on file /home/user/.mozilla/firefox/mwad0hks.default/sessionstore-backups/recovery.js.tmp (Permission denied)

**Comment by dillbyrne** [comment]
https://github.com/dillbyrne/random-agent-spoofer/wiki/Bug-reporting-guide

RAS no longer uses widget so you are using an old version. uninstall that version and install a newer version

**Comment by DistantParadox** [comment]
I reinstalled it to the same results.  Is the newer version in a different location?

**Comment by dillbyrne** [comment]
Restalling the same version will have the same result as the widget module is now depricated. use version 0.9.5.2 on AMO or 0.9.5.3 on github https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.3

0.9.5.4 is still awaiting review on AMO


since you are using a much older version I recommend uninstalling it , the shutting down and restarting the browser and then install the AMO or github version
