### ISSUE TITLE
0.9.5.5 xpi?

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#335]
Where is the 0.9.5.5 .xpi?

thank you

**Comment by TonyA79** [comment]
unsubscribe me

On 12/17/2015 11:16 PM, Geyup wrote:
> Where is the 0955 xpi?
> 
> thank you
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dillbyrne/random-agent-spoofer/issues/335>.
> 

-------------------------------------------------

ONLY AT VFEmail! - Use our Metadata Mitigator to keep your email out of the NSA's hands!
$24.95 ONETIME Lifetime accounts with Privacy Features!  
15GB disk! No bandwidth quotas!
Commercial and Bulk Mail Options!

**Comment by RoxKilly** [comment]
> Where is the 0.9.9.5 .xpi? -@Geyup

This was addressed in #228

**Comment by Geyup** [comment]
thank you

**Comment by Geyup** [comment]
@TonyA79 LOOK to the ----> Right and click ```Unsubscribe```.

**Comment by dillbyrne** [comment]
The xpi will be on AMO if it passes review.

**Comment by Geyup** [comment]
No more xpi on github?
