### ISSUE TITLE
Version 0.9.5.5 .xpi

### ISSUE THREAD

**Issue by JohannesTK** [dillbyrne/random-agent-spoofer#338]
I know we could use Addon SDK but it'd be a nice touch to have already an .xpi file as well with the new release.

**Comment by dillbyrne** [comment]
@JohannesTK 0.9.5.5 is in the review queue in AMO. It is the full version. If it passes review it will be signed and available on AMO. I intend to host releases only  on AMO going forward, assuming the current version passes review.
