### ISSUE TITLE
Canvas exposed

### ISSUE THREAD

**Issue by ron-gh** [dillbyrne/random-agent-spoofer#340]
When you use real profile + disable canvas support, your canvas footprint is still exposed. The solution for me was to use a random (desktop) profile. I use Linux + firefox on pc1 and  Linux + icecat on pc2

To reproduce:
- select "real profile"
- (check) disable canvas support

Check for your canvas on one of the available websites that test your canvas, like https://amiunique.org/

**Comment by seli11** [comment]
take this and go to options and set block everything, https://addons.mozilla.org/en-US/firefox/addon/canvasblocker/   downloas with chrome and install manually because mozilla will tell you its not compatibilite ;)

**Comment by dillbyrne** [comment]
This is already fixed in 0.9.5.5 which is in the review queue on AMO.  Thanks anyway for the bug report :+1:
