### ISSUE TITLE
can you make it compatibilite with palemon?

### ISSUE THREAD

**Issue by seli11** [dillbyrne/random-agent-spoofer#341]
i have edit  .rdf  and installed on palemon but icon dont show up in right?

**Comment by dillbyrne** [comment]
RAS depends on Austrailis specific modules that are not in pale moon .

**Comment by seli11** [comment]
thnx for replay, can i make 1 question? can random user agent spof all fingerprints? i dont wont to use noscript ect,, i ned to spof everything like normal human, what another fingerprinting  firefox leaving with random agent spoofer enabled. can htlm5 palyer detect something about me? or javascript? something unique in my browser? thnx so much for your work bro
