### ISSUE TITLE
0.9.5.5 Updated Through Firefox?

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#343]
I had installed from here on GitHub version 0.9.5.3.

I just noticed today it has been updated automatically in Firefox to 0.9.5.5.

I thought any updates like this in Firefox is because I downloaded RAS from AMO? Because it's listed here on the notes; ```Do not upgrade from an AMO version to a github version```, so it doesn't make sense to me either that I had installed GitHub version 0.9.5.3 and it upgraded in Firefox...

hmm

**Comment by dillbyrne** [comment]
Yes the full version is back on AMO and has upgrade code to handle upgrades from github version 0.9.5.3 or the previous AMO version 0.9.5.2.

All future releases will be on AMO.

**Comment by Geyup** [comment]
Ok, I wasn't sure how the wording is listed...

thanks and keep up the great work, the addon is really appreciated!
