### ISSUE TITLE
Disabling RAS clears user settings (version 0.9.5.5)

### ISSUE THREAD

**Issue by brefal** [dillbyrne/random-agent-spoofer#344]
Operating system: Windows 7 64-bit
RAS version: 0.9.5.5 (fresh install from Firefox add-ons website)
Firefox version: 46.0a1 (nightly)
Addons: HTTPS-Everywhere, NoScript, Random Agent Spoofer, uBlock Origin

I disabled RAS to verify if it was the add-on causing problem on a website. After I enabled it again, I found that all my settings for the add-on had been wiped.

**Comment by dillbyrne** [comment]
Did you use the mouse context menu item or the *checkbox* in about:addons and **not the disable addon button**

https://github.com/dillbyrne/random-agent-spoofer/wiki/Context-Menu-Usage

**Comment by brefal** [comment]
Sorry for not specifying further. I did not notice there was an option to disable the add-on from the context menu so to clarify: I used the built-in Disable-button on the Add-ons manager page. Given that it was a browser function I used to disable it, perhaps it is more likely the error is on Firefox's side and I am better off reporting it to Mozilla instead.

**Comment by dillbyrne** [comment]
No worries. No it is not a browser issue.  I could not get the built in disable button to work how I wanted in addition to the context menu option so I just added the checkbox in "about:addons" instead, in the event users did not want to use the context menu option.

I will make this clearer in the wiki. Sorry for the confusion
