### ISSUE TITLE
FF says not verified

### ISSUE THREAD

**Issue by zooaka** [dillbyrne/random-agent-spoofer#352]
Recently upgraded my Firefox browser. It automatically stops the random agent plugin, stating that it's not verified...what do I do?

**Comment by RoxKilly** [comment]
uninstall Random Agent Spoofer from the add-ons, then reinstall it directly from [Mozilla](https://addons.mozilla.org/en-US/firefox/addon/random-agent-spoofer/)

**Comment by dillbyrne** [comment]
@zooaka  it should have updated if you were on a recent version. The most hassle free option is to uninstall it and install the AMO one. The full version is on AMO now so it is signed and you will receive automatic updates.

**Comment by dillbyrne** [comment]
Closing this. Feel free to reopen it if you still need help
