### ISSUE TITLE
RAS resets settings

### ISSUE THREAD

**Issue by IDKwhattoputhere** [dillbyrne/random-agent-spoofer#354]
I used RAS to make a few changes to my settings because it's easier than doing so manually in about:config. I uninstalled RAS afterwards since I didn't have any use for it anymore. Unfortunately that seems to reset the options back to factory default, even some I didn't change with RAS.

**Comment by dillbyrne** [comment]
@IDKwhattoputhere  RAS will only reset settings if you have disabled the addon using the default firefox disable button or uninstalled the addon. if you use the context menu entry or the "Enable Ras" check box in about:addons then you settings will persist.

see https://github.com/dillbyrne/random-agent-spoofer/wiki/Less-Common-Options-%28about:addons%29

and 

https://github.com/dillbyrne/random-agent-spoofer/wiki/Context-Menu-Usage

As you said, you uninstalled the addon. AMO policy requires all addons clean up after themselves and restore any preferences to their defaults and  remove any new ones added.

**Comment by IDKwhattoputhere** [comment]
So add-ons not doing that actually violate the policy? Didn't know that. Thanks.

**Comment by dillbyrne** [comment]
@IDKwhattoputhere 

RAS is only aware of all the prefs it can modify. It does not keep track if the user ever modified them or not, it only knows what they are currently set to. When uninstalling, RAS resets all prefs it can modify to their default values which also removes any additional prefs added by RAS. This ensures that the browser is left in a working state as the default values are known to work
