### ISSUE TITLE
Option to disable pop information on every profile change 

### ISSUE THREAD

**Issue by Lorentino** [dillbyrne/random-agent-spoofer#356]
Hi!
On every profile change a pop up notification appears in the right inferior corner and some times they are a lot and very annoying , specially with "Change periodically: every request" option. 

It would be nice to have an option to turn off this popups

Thanks!!

**Comment by GifJeff** [comment]
It already exists.

1. Go to the add-ons manager (about:addons) and click Extensions in the left menu.

3. Click "Options" next to Random Agent Spoofer.

4. Uncheck the box that next to "Show notifications?".

**Comment by dillbyrne** [comment]
@Lorentino it already exists in about:addons.

Thanks @GifJeff 

I have added a section to the user manual including this information sorry for any inconveniences 
https://github.com/dillbyrne/random-agent-spoofer/wiki/Less-Common-Options-%28about:addons%29
