### ISSUE TITLE
Option to disable random-agent pop-up banner

### ISSUE THREAD

**Issue by pyyhttu** [dillbyrne/random-agent-spoofer#359]
I read the [user manual](https://github.com/dillbyrne/random-agent-spoofer/wiki/user-manual) already, but couldn't find an answer.

I have random profile setup to change the profile every hour, and then every hour I see a pop-up banner on the bottom right corner. Is there an option to disable the pop-up? If it's deemed not to be in the scope of this project, then even a css code as workaround to hide the banner would suffice. 

Thanks!

**Comment by poochiethecat** [comment]
The menu seems to lack that option, but digging through the code for a bit I noticed that before notifications are sent, `extensions.jid1-AVgCeF1zoVzMjA@jetpack.show_notifications-option` is checked.

So as a workaround you can just set that option by going to [about:config] and pasting that option in the search bar. Then double click the option to change its value to 'false'. You will no longer receive any notifications from the extension.

**Comment by dillbyrne** [comment]
@pyyhttu See about:addons. I have updated the wiki to include this information 

https://github.com/dillbyrne/random-agent-spoofer/wiki/Less-Common-Options-%28about:addons%29
