### ISSUE TITLE
RAS + FF + Sandboxie

### ISSUE THREAD

**Issue by marzametal** [dillbyrne/random-agent-spoofer#360]
Hi... 

At the moment, running Windows 7 Home Premium 64 bit, Firefox 43.0.4.32bit...

I was wondering if anybody else uses Sandboxie alongside Firefox. I cannot for the life of me manage to get RAS to pop up in FF when sandboxed. When loading FF normally (not through Sandboxie), then all works well... the icon pops up in the icon area at the top of the window.

IN: Sandboxed FF - _RAS icon missing from top icon bar_, context menu still exists along with all changes made via RAS settings...
OUT: normal FF - all is well, nothing erroneous to report..

**Comment by RoxKilly** [comment]
I'm using RAS 0.9.5.5 + FF 44 + Sandboxie 5.06, with no problem. I'm on Windows 7 64bit.  I've been using them together for over a year without trouble so your problem is probably not about incompatibility

**Comment by marzametal** [comment]
Hmmmm... thanks.
