### ISSUE TITLE
Update Pale Moon UA strings, please   

### ISSUE THREAD

**Issue by LimboSlam** [dillbyrne/random-agent-spoofer#371]
Hey there.

I know you aren't supporting Pale Moon anymore due to them forking off a later version Firefox  (Pale Moon v25+ we have forked-off from Firefox and changed our GUID, Pale Moon v26+ now brings forth a new layout/rendering called [Goanna](https://moonchildproductions.info/goanna.shtml)) and with Firefox themselves making big changes with their UI. But would you be willing to update or replace some of Pale Moon old UA strings. Now over time I have collected several UA strings specific to Pale Moon, here they are:

Mozilla/5.0 (Windows NT 5.1; rv:25.5) Gecko/20150609 Firefox/31.9 PaleMoon/25.5.0
Mozilla/5.0 (Windows NT 5.2; rv:25.5) Gecko/20150609 Firefox/31.9 PaleMoon/25.5.0
Mozilla/5.0 (Windows NT 6.0; WOW64; rv:25.6) Gecko/20150727 Firefox/31.9 PaleMoon/25.6.0
Mozilla/5.0 (Windows NT 6.0; rv:25.7) Gecko/20151012 Firefox/31.9 PaleMoon/25.7.3
Mozilla/5.0 (Windows NT 6.1; rv:25.5) Gecko/20150609 Firefox/31.9 PaleMoon/25.5.0
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:25.8) Gecko/20151126 Firefox/31.9 PaleMoon/25.8.1
Mozilla/5.0 (Windows NT 6.1; rv:38.9) Gecko/20100101 Goanna/2.0 Firefox/38.9 PaleMoon/26.1.1
Mozilla/5.0 (Windows NT 6.2; WOW64; rv:38.9) Gecko/20100101 Goanna/2.0 Firefox/38.9 
PaleMoon/26.1.1
Mozilla/5.0 (Windows NT 10.0; rv:25.8) Gecko/20151126 Firefox/31.9 PaleMoon/25.8.1
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:38.9) Gecko/20100101 Goanna/2.0 Firefox/38.9 PaleMoon/26.0.3

My personal and should have been Pale Moon default UA string, but you know how hard compatibility is to maintain, especially for websites that use the old UA detection. Here you go: 

Mozilla/5.0 (Windows NT 6.0; rv:2.0) Goanna/20160204 PaleMoon/26.0.3
Mozilla/5.0 (Windows NT 6.0; rv:2.0) Goanna/20160222 PaleMoon/26.1.1

**Comment by LimboSlam** [comment]
@duelle is correct and we would definitely benefit from this. See here #376

**Comment by dillbyrne** [comment]
Pale Moon profiles have been removed from RAS so I'm closing this
