### ISSUE TITLE
Disable/Enable borked

### ISSUE THREAD

**Issue by forkoz** [dillbyrne/random-agent-spoofer#373]
If I right click and use disable RAS it doesn't change the icon in the menu, after that I have to play click and restart with the browser before it disables or enables and all icons show the same.

FF 44.02 x64

**Comment by dillbyrne** [comment]
A preference was removed by mozilla causing the toggle code to fail. The preference was `network.http.use-cache`. I have removed the old preference. The toggle is now working again however I will add some error checking to prevent this from happening again.

**Comment by dillbyrne** [comment]
I have wrapped the code in a try catch and tested it with a non existent pref and the toggle code still worked. I'll add some tests for the preferences used by the addon when I get time so we can catch these changes sooner.

Thanks for the bug report  :+1:
