### ISSUE TITLE
Add random noise to canvas

### ISSUE THREAD

**Issue by sheebree** [dillbyrne/random-agent-spoofer#374]
I found this addon that instead of blocking canvas completely, adds random noise so that it creates a different canvas fingerprint than your real one. It has a major flaw though in that it only randomizes the value once so your canvas fingerprint will be the same always, essentially making it worthless.

I still thought it could be an interesting addition to RAS if it was fixed so that it was randomized every time canvas is used. You could still keep the ability to disable canvas, but with the added ability to randomize it.

I will link the addon since the code might be helpful, should you be interested in implementing this feature.
https://addons.mozilla.org/en-US/firefox/addon/canvas-shadow/

**Comment by RoxKilly** [comment]
Try [CanvasBlocker](https://github.com/kkapsner/CanvasBlocker/); it generates a new fingerprint every time you refresh the page (tested with [BrowserLeaks](http://www.browserleaks.com/canvas)).

This is a feature that @dillbyrne has been made aware of and has put on the to-do for RAS 0.9.5.6, according to issue #111.

**Comment by dillbyrne** [comment]
closing as duplicate
