### ISSUE TITLE
Ability to supress the 'browser changed' popup

### ISSUE THREAD

**Issue by CHEF-KOCH** [dillbyrne/random-agent-spoofer#377]
Hello friends,
can we get an option to suppress/avoid the popup if browser agent is changing?

Would be nice.

**Comment by dillbyrne** [comment]
You can disable notifications in about:addons 

https://github.com/dillbyrne/random-agent-spoofer/wiki/Less-Common-Options-%28about:addons%29

**Comment by CHEF-KOCH** [comment]
Thanks, seems I missed that. 

Closing then. :+1:
