### ISSUE TITLE
Add an "On Browser Startup" option for changing profile periodically

### ISSUE THREAD

**Issue by gamingexpert13** [dillbyrne/random-agent-spoofer#380]
I feel like it would be more believable to spoof one profile per session on a website. If you change the browser profile in the middle of browsing the same site, it might be obvious that you're spoofing. So spoofing to a different profile every time you start up your browser would still give you some anonymity to persistent tracking, but allow believable stats per session.

**Comment by triple-square** [comment]
This already happens if you have either Random, Random (Desktop) or Random (Mobile) checked. Setting Change Periodically to No chooses a random profile on startup but doesn't change it until you restart your browser.

**Comment by dillbyrne** [comment]
As @triple-square states this is already possible if you start with any random option desktop, mobile or specific platform and do not change periodically.

**Comment by gamingexpert13** [comment]
Ah, it would be nice if this was communicated to the end user. There's no reason to assume that it changes on every browser launch. If Change Periodically is set to No, the natural assumption would be that it would not ever change (unless done manually).
