### ISSUE TITLE
Screen Size spoofing not works since firefox 45

### ISSUE THREAD

**Issue by Booff** [dillbyrne/random-agent-spoofer#383]
Hello, Screen Size Spoofing not worked after update to firefox 45
i have testet two times, i use the portable firefox 44 and it works
after update to 45 not works

Check
http://whoer.net/extended

**Comment by Wannabe-Programmer** [comment]
See #365 

This is a known bug that is in the process of being resolved.

**Comment by marzametal** [comment]
Awesome, glad this fix is in the works!
