### ISSUE TITLE
Pop Up...

### ISSUE THREAD

**Issue by nevertellmetheodds** [dillbyrne/random-agent-spoofer#384]
On windows 10 there is popup in lower right hand corner every time profile changes.

Can you add option to have that run silent so it doesn't popup but still changes profile?

Thanks

**Comment by Wannabe-Programmer** [comment]
The notifications can be switched off. 

Go into the Add-ons Manager>Extensions>Options>
Scroll down and uncheck "Show Notifications"

**Comment by nevertellmetheodds** [comment]
Thank you Wannabe-Programmer
