### ISSUE TITLE
New Pale Moon fork a possible new home for RAS?

### ISSUE THREAD

**Issue by sueridgepipe** [dillbyrne/random-agent-spoofer#386]
http://www.ghacks.net/2016/03/16/the-future-of-pale-moon/

In Pale Moon's words, this is a possiblilty...

> So, I've been looking closely at what would be a way forward, and the idea has come up to make a new browser product, re-forking from a later point in the Mozilla source tree to tackle the missed marks, compiler compatibility, and to some extent the complications in the Mozilla code. This re-forking would be done on the last stable version of Mozilla code that hasn't had a sledgehammer put to it yet and that offers the features and capabilities we as a project would still want (i.e.: Sync 1.1, XPCOM binary components in extensions, XUL, XBL, complete theme support, etc.).

> The team would pick a code base that would support all the features Pale Moon should retain including support for XPCOM and XUL, complete theme support and Sync 1.1 support among others. This would set it apart from future versions of Firefox which won't support these among others.

No timeline has been given, but IMO this could be a huge step forward in keeping all the flexibility and functionality that has made Firefox great... until Modzilla killed it.

**Comment by dillbyrne** [comment]
I'm not interested in maintaining RAS for pale moon nor do I have the time. If you wish to do so feel free.
