### ISSUE TITLE
Option to disable alerts

### ISSUE THREAD

**Issue by kly86** [dillbyrne/random-agent-spoofer#387]
Hi,

Thanks for creating this great plugin.
I'm using the random automatic profile change but I'm a bit annoyed by the fact that it constantly alerts me.
I think there should be an option to disable alerts, especially when in full-screen mode or whenever the browser window is not the active one.

Thanks again for the great plugin!

**Comment by dillbyrne** [comment]
https://github.com/dillbyrne/random-agent-spoofer/wiki/Less-Common-Options-%28about:addons%29

**Comment by ZIEXED** [comment]
WTF
unwatched
trillion issues opened asking how to disable the notifications
