### ISSUE TITLE
RAS is detected by whichbrowser.net

### ISSUE THREAD

**Issue by 3n7r0p1** [dillbyrne/random-agent-spoofer#389]
On Firefox 44.0.2; with RAS 0.9.5.5; Windows 7 x64:

All of the attempted browser profiles (about 10 recent versions, both desktop & mobile) return "You are using an unknown browser that imitates ..." on https://whichbrowser.net

Switching to 'Real Profile' results in correct browser identification.

Is evading spoofing detection one of RAS's goals?

Thanks!

**Comment by Kraxys** [comment]
Same issue here on a fresh FF profile but the site is correctly fooled when some FF on some windows OS is chosen.

On an other FF profile (the one I currently use, with many others security addons, the site is correctly fooled for desktop browser, but I get the same issue as you for mobile.

**Comment by Wannabe-Programmer** [comment]
@Kraxys You don't suppose the parser is making use of the FF Resource Header to detect imitation?

See #350

**Comment by dillbyrne** [comment]
RAS is not revealing your actual browser on this site, so it is not detected. I suspect it is using engine specific things to query for non firefox browsers. 

The main goal of RAS is to hinder browser fingerprinting.  It cannot 100% prevent it due to the browser implementation differences, addon limitations, manpower and the evolving web standards that continue to grow and become implemented.

**Comment by 3n7r0p1** [comment]
Understood - thanks! Was hoping it was an easy fix. Thought it might just have been related to the difference in the user-agents.

**Comment by dillbyrne** [comment]
Trying the current version that I'm working on, shows good results.

![a](https://cloud.githubusercontent.com/assets/2903711/15427956/77528934-1e90-11e6-871b-b7d8bc442917.png)
![b](https://cloud.githubusercontent.com/assets/2903711/15427955/77508562-1e90-11e6-9685-6a4793c37f54.png)
![c](https://cloud.githubusercontent.com/assets/2903711/15427954/774d3862-1e90-11e6-8ae2-bbce9887c98c.png)

**Comment by 3n7r0p1** [comment]
Thank you! Looking forward to it.
