### ISSUE TITLE
R.A.S P. v0.9.5.5:  Anonymization of window.name and screen size spoofing not working on ip-check.info

### ISSUE THREAD

**Issue by Kraxys** [dillbyrne/random-agent-spoofer#391]
Hi,

fresh install of this version on a fresh FF profile don't work as intended:

RAS  version 0.9.5.5 from AMO, fresh install
FF 45.0, new profile, no other addons
windows 7.1

Issues:
* windows.name is not anonymized and secreen size not spoofed on ip-check.info.
* Screen size not spoofed on browserspy.dk
* Time zone not spoofed on browserspy.dk

What is enabled:

Profile:
Random desktop  - peridiocally change: no

Options: 
script injection enabled
window.name protection enabled
Time Zone spoofing : -12
Scree Size spoofing ; 800x600

Headers: 
Spoof Accept, Spoof Accept-encoding, Spoof Accep Language (en, US)

**Comment by Kraxys** [comment]
But date and screen size are correctly spoofed on http://whatsmyuseragent.com/

**Comment by dillbyrne** [comment]
See #365
