### ISSUE TITLE
RAS 0.9.5.5: window.name protection, time and sceen size not working on ip-check.info and browserspy.dk

### ISSUE THREAD

**Issue by Kraxys** [dillbyrne/random-agent-spoofer#393]
I have tested a fresh install (from AMO) of RAS 0.9.5.5 on a fresh profile (no others addons) of FF 45.0 (no java, no schockwave flash). I use windows 7SP1 32b.

In RAS are checked;
* Profile Random (desktop)
* Enable script injection
*Time Zone Spoofing: +6
* Sceen size spoofing: 800x600
* Spoof Accept
* Spoof Accept-Encoding
* Spoof Accept-Language as

Results: 

On http://ip-check.info/?lang=en, click on "start test": the browser is being analyzed.

I get:
Tab name: "window.name" is traceable. Your unique ID: 7679119
Screen: 1280 x 1024 pixels 24 bit color depth
Screen (usable):1280 x 994 pixels (does not match screen)
Browser window: 1117 x 841 pixels (inner size) 

On http://browserspy.dk/screen.php (screen test) I get:

Width 	1280
Height 	1024
AvailHeight 	994
AvailWidth 	1280 

http://browserspy.dk/date.php (date & time test) I get:

Time and date; 	Wed Mar 30 2016 02:13:34 GMT+0200
GMT'ed: 	Wed, 30 Mar 2016 00:13:34 GMT
Locale String :	30/03/2016 à 02:13:34
Time-Zone offset: 	-120 minutes
Milliseconds since January 1, 1970 	1459296814000

On http://whatsmyuseragent.com I get:

Screen Resolution: 	1280 px x 1024 px
Browser Window: 	1100 px x 841 px
Local Time: 	2:16 am
Time Zone: 	--2 hours

On http://whatsmyscreenresolution.com I get:

Your screen resolution is 1280 x 1024
Your browser window resolution is 1100 x 841
Internet Beat: 	@ 51
Time on browserspy.dk server: 	Tue, 29 Mar 2016 19:13:18 -0500
Time on your PC 	30/03/2016 à 02:13:34 

![issue window dot name screen size on ip-check](https://cloud.githubusercontent.com/assets/14897785/14128176/bdfebcc6-f61e-11e5-981a-7ba309d79cad.jpg)
![issue date time on browserspy](https://cloud.githubusercontent.com/assets/14897785/14128179/c765302e-f61e-11e5-80e3-22c156f906c3.jpg)
![issue screen size on browserspy](https://cloud.githubusercontent.com/assets/14897785/14128181/ce731f7a-f61e-11e5-97fc-6b4d1428abea.jpg)
![issue date time and screen size on whatsmyuseragent](https://cloud.githubusercontent.com/assets/14897785/14128204/0e1d4d80-f61f-11e5-805c-e7fd9047ff2e.jpg)

**Comment by dillbyrne** [comment]
See #365
