### ISSUE TITLE
Always showing User-Agent: Mozilla/5.0 

### ISSUE THREAD

**Issue by XnimrodhunterX** [dillbyrne/random-agent-spoofer#394]
Hello,
The random agent spoofer is rotating the agent, but it always shows Mozilla/5.0 along with the changed agent.

Examples
User-Agent: Mozilla/5.0 (Mobile; rv:45.0) Gecko/45.0 Firefox/45.0
User-Agent: Mozilla/5.0 (Android; Tablet; rv:39.0) Gecko/39.0 Firefox/39.0
User-Agent: Mozilla/5.0 (PLAYSTATION 3; 4.66) AppleWebKit/531.22.8 (KHTML, like Gecko)
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .N

Is there a way to disable Mozilla/5.0?

When I use a different user-agent spoofer, it does not show Mozilla at all. The downside is that it will not rotate the agent so I like RAS much butter, but because it shows Mozilla/5.0, it makes it not so random.

**Comment by Wannabe-Programmer** [comment]
This is normal - every browser’s user agent starts with “Mozilla”.

It's a long, ridiculous story as to why it's so confusing.

**Comment by dillbyrne** [comment]
This is not a bug read up on the history of user agents 

https://en.wikipedia.org/wiki/User_agent#Format_for_human-operated_web_browsers
