### ISSUE TITLE
Fix tracking protection option on ff >= 45

### ISSUE THREAD

**Issue by dillbyrne** [dillbyrne/random-agent-spoofer#396]
The internal about:config preference has changed.

**Comment by B00ze64** [comment]
Care to tell us what it is now?

I've got these so far:
user_pref("privacy.trackingprotection.ui.enabled", true);
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.pbmode.enabled", true);

Thanks.

**Comment by dillbyrne** [comment]
Hi @B00ze64 You have them listed above. The RAS pref corresponds to  user_pref("privacy.trackingprotection.enabled", true); but it appears that by default it is only applied in private browsing so I'll have to have more preferences or checkbox / dropdown combo. Either way I'll take care of it once I fix the script injection issue which is the most pressing issue at the moment.

**Comment by dillbyrne** [comment]
I found this resource https://wiki.mozilla.org/Security/Tracking_protection  which explains that the tracking protection pref used in RAS is the global pref and will enforce tracking protection. So we are covered by this. I tested it with the test links on that page to be sure.
