### ISSUE TITLE
Some ideas / Improvmentes for Random Agent Spoofer 

### ISSUE THREAD

**Issue by gihub101** [dillbyrne/random-agent-spoofer#399]
Hello I'm newbie. 
I'm currently using Random Agent Spoofer in firefox 40 with optimum results. I'm not a programmer but if I were or If I could I will add (in a possible future version) options to Disconnect request from Facebook and Twitter.  I'm  actually using to and ancient FB disconnect plugin and Twitter disconnect plugin to improve my privacy. I'd pfrefer to use just one plugin with all in one functions
Regards

**Comment by alct** [comment]
Hello,

That's not a job for RAS. You should have a look at [Request Policy continued](https://requestpolicycontinued.github.io/) and [Self-Destructing Cookies](https://addons.mozilla.org/en-US/firefox/addon/self-destructing-cookies/).

**Comment by dillbyrne** [comment]
RAS has an option to toggle firefox's built in tracking protection which uses disconnect's blocklist.  You can choose the strict version of disconnect's blocklist if you desire https://support.mozilla.org/en-US/kb/tracking-protection-pbm#w_to-change-your-blocklist

**Comment by gihub101** [comment]
It doesn't work as the same way. RAS does not block FB and Twitter connect requests.
 Rte: Quintana Alejandro Daniel

**Comment by dillbyrne** [comment]
@gihub101 At this point in time I do not wish to add a blocklist to RAS as there are other addons that are built specifically  to handle that and I already have enough to deal with.

**Comment by gihub101** [comment]
Well not aproved ok 
Another idea could be to select customized profile. The option is limited  and you can't put all the browser profiles. Its awkward Rte: Quintana Alejandro Daniel Condarco 3537 1419 = Capital Federal

**Comment by gihub101** [comment]
1) I'm not talking about a block list. A block list can break a lot of things including scripting
2) firefox tracking protection is useless. It doesn't stop anything 
Take a look to a old add on called FB disconnect.  it Just disconnecst FB tracking requests, including the facebook button.  
Another sugestion  (you could take it or not) is a posibility to add a customized profile in the menu
Why ?
First at all because selectable profilse are already old: chrome 42 and Firefox 43. 
What you gonna do ?  
To release a new version every 3 months ?
If there's a chance to put a customized i profile we could add what we want as profile. If you don't want to update the soft for improvement I'll understand. 
Bye
