### ISSUE TITLE
Disable Bug?

### ISSUE THREAD

**Issue by Mclaughlinux** [dillbyrne/random-agent-spoofer#400]
Please note that in Firefox (45.0.2) disabling the extension **_DOES NOT_** Disable in reality… it continues running…

Thank you!

**Comment by forkoz** [comment]
On earlier fierfox it doesn't disable and enable readily either. I posted this and got 0 replies so you're not alone.

**Comment by dillbyrne** [comment]
Hello @forkoz @Mclaughlinux I have seen both of your issues I simply have not had time to deal with them. I'm still trying to get the script injection stuff working again and I will address other issues once I get that sorted. 

If you could both clarify one thing for me, are you talking about disabling RAS from the context menu or using firefox's built in disable addon option.

**Comment by forkoz** [comment]
I'm using the context menu. Didn't upgrade to 45 yet because injection doesn't work. Sounds like there it doesn't disable either way.

**Comment by dillbyrne** [comment]
What happens when you disable from the context menu ?  the addon icon should turn red and the options in the panel should be greyed out. Does this happen ? 

https://github.com/dillbyrne/random-agent-spoofer/wiki/Context-Menu-Usage

**Comment by dillbyrne** [comment]
I'll uses #373 to track this. I have confirmed the issue and I will deal with it before the next release. Thanks to  both of you for reporting this :+1:
