### ISSUE TITLE
fix screen resolutin like this

### ISSUE THREAD

**Issue by seli11** [dillbyrne/random-agent-spoofer#401]
i found this plugin https://addons.mozilla.org/en-US/firefox/addon/stop-fingerprinting/  who spoof beter screen resolution without leaks on https://www.browserleaks.com/javascript ,  iframe's contentWindow, 
why random agent spoofer have this issues? can you add the code on random agent? \

// emulate standard fullHD screen
fakeGetters(window.Screen.prototype, { bind: true, }, {
	width() { return 1980; },
	availWidth() { return 1980; },
	height() { return 1080; },
	availHeight() { return 1040; }, // 40px for taskbar at bottom
	colorDepth() { return 24; },
	pixelDepth() { return 24; },
	top() { return 0; },
	left() { return 0; },
	availTop() { return 0; },
	availLeft() { return 0; },
});
window.devicePixelRatio = 1;

**Comment by dillbyrne** [comment]
@seli11 Thanks :+1:

**Comment by dillbyrne** [comment]
I have the screen spoofing fixed in #365 but I have not yet been able to find a new way to spoof the window size attributes
