### ISSUE TITLE
RAS window name don't work

### ISSUE THREAD

**Issue by bourgeoise** [dillbyrne/random-agent-spoofer#402]
I use Firefox 45.0.2
Windows 7 32 bit
On http://ip-check.info/?lang=en
I can read number for tab name.

**Comment by marzametal** [comment]
Script Injection isn't working for >=45 ... this has already been explained in another issue thread. A re-write is in the works since 45 changed something...

**Comment by bourgeoise** [comment]
OK

**Comment by dillbyrne** [comment]
Closing as it will be handled in the script injection issue
