### ISSUE TITLE
User agent leaks

### ISSUE THREAD

**Issue by seli11** [dillbyrne/random-agent-spoofer#403]
i have make a test in https://whichbrowser.net/ and here we have issues with non firefox browsers, with firefox browsers we can spoof easy no matter what version you seet, i have edit useragents.json and i have seet 50 diferent fake firefox user agent, like  firefox 39.2.8, firefox 39.7.6, ect,, and works fine, 
the best think its to set option like, set random firefox browser, 
because with chrome,opera,safari,ect,, they can detect easy fake user agent on firefox browser,
![capture1](https://cloud.githubusercontent.com/assets/10393461/14761334/c9da5b16-0912-11e6-9808-9d34737309d8.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10393461/14761335/c9da849c-0912-11e6-9099-e4d548500dc0.PNG)

**Comment by forkoz** [comment]
I'm guessing "Mozilla/5.0" gives it away, I don't think chrome reports that....

**Comment by dillbyrne** [comment]
This is not a leak. The Mozilla/5.0 has nothing to do with it, read up on the history of user agents. This site is probably relying on engine specific things which gecko obviously does not have. With that said it still does not know you real browser so it is not leaking.
