### ISSUE TITLE
spoof HTTP_ACCEPT_ENCODING ..

### ISSUE THREAD

**Issue by publicstorage689** [dillbyrne/random-agent-spoofer#406]
if you set your os to windows but HTTP_ACCEPT_ENCODING return gzip it's likely you are using linux.. is someone have better tools for agent spoofing ? so far i'm finding a lot of returning header revealing your true identity. should be examined precisely.

**Comment by dillbyrne** [comment]
These values are taken from actual  browsers on actual platforms. https://github.com/dillbyrne/random-agent-spoofer/blob/master/data/json/useragents.json
