### ISSUE TITLE
Window Size.... is it working??

### ISSUE THREAD

**Issue by Gym6969** [dillbyrne/random-agent-spoofer#408]
I have tried almost everything to let this work but it will not spoof with any profile. I have set profile (Screen Size Spoofing) in script injection options. 

Am I missing something??

Thanks
Ray

**Comment by dillbyrne** [comment]
Hi @Gym6969 . Firefox >= version 45 broke the script injection mechanism on which window and screen spoofing depend. I am working on a fix see #365 . I'll close this now as the other issue will deal with it
