### ISSUE TITLE
How to replace Useragents.json in the extension .xpi file?

### ISSUE THREAD

**Issue by gggirlgeek** [dillbyrne/random-agent-spoofer#414]
Hello,

I wanted to update my useragents with the downloaded version of Useragents.json.  So I tried unzipping the RAS .xpi file, replacing it and zipping it back up (in uncompressed format.)  However, when I install the modded version of the extension in firefox the RAS toolbar icon won't show at all.  It installs OK and I can change options in about:addons, but I have no access to the options from the toolbar button.  It's not listed under "Customize" either.

Can someone tell me what I'm doing wrong?

**Comment by dillbyrne** [comment]
I always use the jpm tool to create the xpi. You could of perhaps made a syntax error and that would cause the json to not parse correctly. The format for the json file is tightly coupled with the addon so if you remove a major section such as mobile, desktop or other then it will break.

The script injection bug is slowly getting fixed and once it is I will release a new version with updated profiles, if you would prefer to wait.

Also firefox will treat the addon as unsigned if you modify it so it could be blocking it from installing if you have not set the preference  `xpinstall.signatures.required` to false. 

I can not support custom builds so the above is the only help I can offer with regards to that.

**Comment by gggirlgeek** [comment]
Thanks for the reply.  I tried the about:config setting but no luck.  Oh well.  I guess I'll wait.  I just feel we stick out more by having old useragents.

**Comment by gggirlgeek** [comment]
Also, I think it would be good to get rid of the Windows 8/8.1 profiles -- or at least put them in a separate category.  Most people have switched to Windows 10 or are sticking with Windows 7.  I disabled them in my settings but then lost my settings by messing arond too much.  It's a pain to untick them all again.

Here is one site's most used useragents:  https://techblog.willshouse.com/2012/01/03/most-common-user-agents/
