### ISSUE TITLE
Make website context menu toggle changes for current website only

### ISSUE THREAD

**Issue by gggirlgeek** [dillbyrne/random-agent-spoofer#415]
I think it would be more convenient if the context menu options toggled enable/disable RAS for the current website only.  Either this or add a context menu item to whitelist the current website.  I think it should also add all the whitelist options to the these whitelisted websites.

I say this because sometimes I can't figure out which option is breaking a website so I like to quickly disable RAS.  However, I have to toggle it back and forth when switching tabs to other websites.  It gets annoying.

I understand if you think this would slow down the browser page loading too much.  Hope you can find a way around that.

**Comment by dillbyrne** [comment]
Hi @gggirlgeek please see #412 . I am currently working on fixing script injection  and with that the whitelist. So you will be able to whitelist problematic sites once again when it is fixed

**Comment by gggirlgeek** [comment]
I'm getting used to the settings now.  It takes a minute.  I finally hunkered down and disabled 2 settings at a time until I found the problem ones.  Had to do this for Youtube (requies "Disable Dom resource timing|" to be unticked) and for all sites with advanced searches (requies "disable referrer" to be unticked.)  I used a Whitelist option for the latter.

**Comment by gggirlgeek** [comment]
Thanks for this addon, BTW!  Going to add a review right now.
