### ISSUE TITLE
Instead of "Disable Canvas Support" - Spoof the fingerprint on a per session basis.

### ISSUE THREAD

**Issue by DrunkenSasquatch** [dillbyrne/random-agent-spoofer#418]
This adds to the #111 enhancement for the 0.9.5.6 release. 
I found this [add-on](https://addons.mozilla.org/en-US/firefox/addon/no-canvas-fingerprinting/?src=cb-dl-hotness) with a detailed description as to why disabling canvas support is actually anti-productive and makes users stand out - possibly more than leaving it enabled. 

Here is a the blog:
https://multiloginapp.com/how-canvas-fingerprint-blockers-make-you-easily-trackable/

The blog mentions that even spoofing the fingerprint at random intervals is a bad idea and should only be changed on a per session basis or when the user agent string has been changed. So, my question is - can the canvas fingerprint be directly linked to the user agent, when the user agent string is spoofed, the canvas element is changed at the same time? Along with "screen size" and "time zone" spoofing as well.

![canvasdefender](https://cloud.githubusercontent.com/assets/16097892/15791627/c60a1100-2a1b-11e6-8394-5a35953d93c8.jpg)

**Comment by bonbonboi** [comment]
What happened to this issue? Closed=Solved?

**Comment by dkasak** [comment]
@bonbonboi The issue wasn't closed as far as I can see.
