### ISSUE TITLE
Change the profile on a per-session basis

### ISSUE THREAD

**Issue by mindstormer12** [dillbyrne/random-agent-spoofer#420]
I was looking to creating several profiles and switching between them manually but I came across this addon and it seems to achieve the same thing in a more convenient manner. However, I noticed that the profiles can only be set to change every X hours, without the option to do it on a per-session basis. Per-session basis is much more effective at reducing fingerprint because things like user-agent do not typically change within a session--if it does, then this unusual behavior will make you unique to tracking companies and a more interesting target. 

Also, I only see an option to disable canvas fingerprinting, not spoofing it. Disabling canvas fingerprinting also makes you more unique for the same reason and breaks sites that use it. Spoofing it instead and on a per-session basis would support sites that use it while effectively blending in with the crowd (i.e. reduce fingerprinting) even more so that outright disabling it. 

I cannot use the addon for these reasons but if these are things that are going to be implemented, then I will switch to it for sure. These seem to be the only criticisms (besides support for cookies to be separated entirely) but they are common ones based on my research in finding similar addons.

**Comment by Wannabe-Programmer** [comment]
"I noticed that the profiles can only be set to change every X hours, without the option to do it on a per-session basis."

Well actually, the user agents can be set to only change per session. In the "Change Periodically" radio box, simply select "No". When you close the browser and re-open the browser the user agent will change. Perhaps dillbyrne should rename the "No" to "Per Session"

`<select id="timerdd">
			<option value="none">Per Session</option>`

**Comment by dillbyrne** [comment]
In future keep it to one issue per ticket please. I am addressing the canvas spoofing. I am still working on fixing the script injection and  reimplementing the whitelist. 

Per session spoofing is mentioned in the FAQ
https://github.com/dillbyrne/random-agent-spoofer/wiki/Frequently-Asked-Questions
