### ISSUE TITLE
Periodical changes too noisy

### ISSUE THREAD

**Issue by markus2330** [dillbyrne/random-agent-spoofer#424]
Is it possible to make periodical changes quiet without information to which browser the switch was made? It is currently very annoying when the browser is unused in the background and I get informed every X minutes that the profile changed.

Expected behaviour: no information about profile changes, at least when there is no browser activity.

When using changing per request it gets even worse: the popup which displays new profiles is so busy showing new profiles that it does not even go away.

Random Agent Spoofer 0.9.5.5
with Firefox ESR 45.2.0

**Comment by plo-** [comment]
IIUC you want an option to disable profile chance notifications? It's already there, in _about:addons_ > Random Agent Spoofer > Options > "Show notifications".
Cf https://github.com/dillbyrne/random-agent-spoofer/wiki/Less-Common-Options-(about:addons).

**Comment by markus2330** [comment]
Thank you for your quick reply!

So there are two different options dialogs? Isn't it possible to change it in the "Options" tab when clicking on the icon? Are all the options there really necessary? What about some "beginners" and "experts" settings dialog?

**Comment by markus2330** [comment]
Btw. the issue can be tagged as solved if you want: it now works for me. Thanks for your help.

But thus I am doing research on configuration I wonder what the rationale was to move 3 options somewhere else when nearly hundret (?) options are at an easier accessable place.

Maybe some of you have even time to do a 15min survey on such issues:
http://elektra.limequery.org/625192

We would appreciate your input!

**Comment by duck57** [comment]
I can't seem to find the "Options" tab from about:addons.  I only see "preferences", which doesn't actually let me change anything.

**Comment by zkanda** [comment]
@duck57 All you need is the preferences, scroll down to the bottom and you will find the "Show Notifications?" with a checkbox.
