### ISSUE TITLE
UAs:  FF 47.0 and Chrome 51.0.2704.106 on 64-bit ubuntu, 

### ISSUE THREAD

**Issue by Copyrites** [dillbyrne/random-agent-spoofer#426]
Here's the info for FF 47.0 and Chrome 51.0.2704.106 on 64-bit ubuntu, also captured the date stuff too.  I used a fresh profile for FF and Chrome had only the google-docs extension installed

## Firefox 47.0 

Browser Information

Shows some of the basic information available in the browser like codename, version, platform and online information.
Test 	Result
navigator.appName 	Netscape
navigator.appCodeName 	Mozilla
navigator.appVersion 	5.0 (X11)
navigator.appMinorVersion 	Property is not supported! navigator.appMinorVersion is not a string. It's a undefined
navigator.vendor 	
navigator.userAgent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 . More info...
navigator.oscpu 	Linux x86_64 . More info...
navigator.platform 	Linux x86_64
navigator.securityPolicy 	Property is not supported! navigator.securityPolicy is not a string. It's a undefined . More info...
navigator.onLine 	true . More info...
Info browser.name 	firefox
Info browser.version 	47.0
Info layout.name 	gecko
Info layout.version 	47.0
Info os.name 	linux
Internet Explorer real version 	This only works in Microsoft Internet Explorer!
Operating System 	Linux/Unix - More info...

=================================

Accepted Filetypes Information

Find out which MIME types, charsets, encodings and languages your browser accepts? Your browser may support more than the ones shown below.
Test 	Result
Accepted Documents 	text/html
application/xhtml+xml
application/xml;q=0.9
*/*;q=0.8
Accepted Charsets 	Not available!
Accepted Encodings 	gzip
deflate
Accepted Languages 	en-US
en;q=0.5

=================================

Screen Information

Find out information about your screen including width, height, DPI, color depth, font smoothing.
Test 	Result
Width 	2560
Height 	1600
AvailHeight 	1572
AvailWidth 	2560
Normal horizontal dots per inch (DPI) 	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI) 	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI) 	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI) 	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window? 	false
PixelDepth 	24
ColorDepth 	24
FontSmoothing Enabled 	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth 	Property not supported or blank!
Update interval 	Property is not supported! screen.updateInterval is not a number. It's a undefined 

=================================

Date and Time Information

Find out information about the time and date on your system. See timezone information and see if your system time needs to be fixed.
Test 	Result
Time and date 	Fri Jun 24 2016 11:59:28 GMT-0400 (EDT)
GMT'ed 	Fri, 24 Jun 2016 15:59:28 GMT
Locale String 	6/24/2016, 11:59:28 AM
Time-Zone offset 	240 minutes
Milliseconds since January 1, 1970 	1466783968000
Internet Beat 	@ 707
Time on browserspy.dk server 	Fri, 24 Jun 2016 10:59:28 -0500
Time on your PC 	6/24/2016, 11:59:28 AM
Difference between server and PC time 	0 seconds 

==================================
==================================
==================================
## Chrome 51.0.2704.106

Browser Information
Shows some of the basic information available in the browser like codename, version, platform and online information.
Test	Result
navigator.appName	Netscape
navigator.appCodeName	Mozilla
navigator.appVersion	5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36
navigator.appMinorVersion	Property is not supported! navigator.appMinorVersion is not a string. It's a undefined
navigator.vendor	Google Inc.
navigator.userAgent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 . More info...
navigator.oscpu	Property is not supported! navigator.oscpu is not a string. It's a undefined . More info...
navigator.platform	Linux x86_64
navigator.securityPolicy	Property is not supported! navigator.securityPolicy is not a string. It's a undefined . More info...
navigator.onLine	true . More info...
Info browser.name	chrome
Info browser.version	51.0.2704.106
Info layout.name	webkit
Info layout.version	537.36
Info os.name	linux
Internet Explorer real version	This only works in Microsoft Internet Explorer!
Operating System	Linux/Unix - More info...

==================================

Accepted Filetypes Information
Find out which MIME types, charsets, encodings and languages your browser accepts? Your browser may support more than the ones shown below.
Test	Result
Accepted Documents	text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8
Accepted Charsets	Not available!
Accepted Encodings	gzip
deflate
sdch
Accepted Languages	en-US
en;q=0.8

==================================

Screen Information
Find out information about your screen including width, height, DPI, color depth, font smoothing.
Test	Result
Width	2560
Height	1600
AvailHeight	1572
AvailWidth	2560
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	24
ColorDepth	24
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

==================================

Date and Time Information
Find out information about the time and date on your system. See timezone information and see if your system time needs to be fixed.
Test	Result
Time and date	Fri Jun 24 2016 12:02:15 GMT-0400 (EDT)
GMT'ed	Fri, 24 Jun 2016 16:02:15 GMT
Locale String	6/24/2016, 12:02:15 PM
Time-Zone offset	240 minutes
Milliseconds since January 1, 1970	1466784135000
Internet Beat	@ 709
Time on browserspy.dk server	Fri, 24 Jun 2016 11:02:15 -0500
Time on your PC	6/24/2016, 12:02:15 PM
Difference between server and PC time	0 seconds

**Comment by dillbyrne** [comment]
Thanks I'll add these in #390
