### ISSUE TITLE
Add Seamonkey Support

### ISSUE THREAD

**Issue by cwmke** [dillbyrne/random-agent-spoofer#43]
I'm not sure if this is feasible or not, but from what I understand, it shouldn't be too bad since it's very closely related to Firefox and Thunderbird.  Here's a site I found with more information.  Thanks for the consideration.

https://developer.mozilla.org/en-US/Add-ons/SeaMonkey_2

**Comment by Wiccio** [comment]
After more than a year from the first request, may I ask if there is news about the use of your add-on on SeaMonkey?

I managed to install it on SeaMonkey through a converter (https://github.com/lemon-juice/addonconverter) but unfortunately doesn't work properly.
