### ISSUE TITLE
Default reset handled wrong way? High privacy risk.

### ISSUE THREAD

**Issue by noname-123** [dillbyrne/random-agent-spoofer#433]
I'm new to GitHub so I'm not sure how this works, but I guess it's better to make a new issue than to comment in the closed one, #423, even though the question is mostly the same although more explained.

I don't see how setting stuff to default is "reverting changes". For me, that was _making_ changes, as I myself had previously changed the settings, and what RAS did was to change that to something I hadn't set. I have never seen an add-on with this behaviour before.

If it isn't possible to save the settings in a file (locally of course), and revert to that except items that has been changed manually later, can't there at least be a question dialog like "Do you want to keep the current settings or revert to Firefox default settings?"? Or at the very least a warning that can't be missed.

What it does now seems clunky, somewhat "treacherous" against the user, and unsafe. Particularly re-enabling WebRTC without warning is dangerous, as that leaks your IP address straight through VPN services and Tor!

**Comment by dillbyrne** [comment]
I can't be sure that the settings that people have modified will be guaranteed to be error free so resetting them to default is a guaranteed way to make sure the browser will be in a working state. As I mentioned in the other issue RAS has a temporary option to disable all its settings if you choose. 

If you don't want to use that then you can change the options one by one. RAS depends on the states of its preferences being valid data. 

Many of the options have a limited number of states and RAS will do different things depending on the state. If a user has modified a preference and it is not valid or it is unexpected by RAS it could cause errors. For example in the UI many of the options are checkboxes that are represented by two different preference values. This would be a nightmare to manage if users can put anything into any preference, what then constitutes checked and unchecked. Or for dropdowns when there are multiple options ?

So I chose to do it this way to prevent "power users" from shooting themselves in the foot.

Also the webRTC is your local IP only not your actual IP address so it is not that dangerous.

I should have communicated it better to users that the preferences are reset and I will add it to the addon description and possibly some notifications.

Thanks for your feedback.
