### ISSUE TITLE
incompat with LastPass if "Random Linux Browsers" profile is enabled

### ISSUE THREAD

**Issue by pgnd** [dillbyrne/random-agent-spoofer#435]
I've FF 49a2 dev installed, w/ latest RAS.

Works as expected, save for pending Whitelist & Script Injection.

I've also install LastPass pwd manager.  Typically, when a LogIn form is presented in browser, LastPass populates the User/Pwd fields -- with clickable icons to invole the LastPass data entry, &/or 'autofill' as specified.

This works with RAS installed as well, with any/all Headers & Options selected (afaict, so far ...).

But, if "Random Linux Browsers" _profile_ is selected, none of the LastPass in-browser overlay functionality works anymore.  No icons, no autofill.  I can still login by manual entry -- just not using the (semi)automated LastPass entry methods.

I suspect this may (?) have to do with the RAS script injection?  Perhaps other.  Not clear 2 me yet in any case ...

**Comment by Wannabe-Programmer** [comment]
LastPass probably collects information relating to your default user-agent when installed. This means when you change the user agent - whether it's the browser or the operating system (not sure which one), then LastPass may not recognize the browser. I would assume, that this would be something that the LastPass developers would have to change on their end.

**Comment by geeknik** [comment]
Using the latest Firefox Nightly 52.0a1 with RAS (which works great btw) makes it impossible to login to the LastPass extension and the LastPass website. I've even added lastpass.com to the Whitelist, but the only workaround I've found to this is to disable RAS. I haven't figured out which configuration option is interfering yet.

**Comment by guntbert** [comment]
The same bit me just now - maybe add some hint to the Readme?
