### ISSUE TITLE
New UAs: Opera, Opera Developer (x2), Chrome on 64-bit ubuntu

### ISSUE THREAD

**Issue by Copyrites** [dillbyrne/random-agent-spoofer#438]
**Opera 38.0.2220.41**

Browser Information

Test	Result
navigator.appName	Netscape
navigator.appCodeName	Mozilla
navigator.appVersion	5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41
navigator.appMinorVersion	Property is not supported! navigator.appMinorVersion is not a string. It's a undefined
navigator.vendor	Google Inc.
navigator.userAgent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41 . More info...
navigator.oscpu	Property is not supported! navigator.oscpu is not a string. It's a undefined . More info...
navigator.platform	Linux x86_64
navigator.securityPolicy	Property is not supported! navigator.securityPolicy is not a string. It's a undefined . More info...
navigator.onLine	true . More info...
Info browser.name	chrome
Info browser.version	51.0.2704.106
Info layout.name	webkit
Info layout.version	537.36
Info os.name	linux
Internet Explorer real version	This only works in Microsoft Internet Explorer!
Operating System	Linux/Unix - More info...

----------------------------------

Accepted Filetypes Information

Test	Result
Accepted Documents	text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8
Accepted Charsets	Not available!
Accepted Encodings	gzip
deflate
lzma
sdch
Accepted Languages	en-US
en;q=0.8

----------------------------------

Screen Information

Test	Result
Width	2560
Height	1600
AvailHeight	1574
AvailWidth	2560
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	24
ColorDepth	24
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

-----------------------
Date and Time Information

Test	Result
Time and date	Sat Jul 23 2016 09:51:17 GMT-0400 (EDT)
GMT'ed	Sat, 23 Jul 2016 13:51:17 GMT
Locale String	7/23/2016, 9:51:17 AM
Time-Zone offset	240 minutes
Milliseconds since January 1, 1970	1469281877000
Internet Beat	@ 618
Time on browserspy.dk server	Sat, 23 Jul 2016 08:51:17 -0500
Time on your PC	7/23/2016, 9:51:17 AM
Difference between server and PC time	0 seconds

=================================================================================

**Opera Developer 	40.0.2288.0** 

Browser Information

Test	Result
navigator.appName	Netscape
navigator.appCodeName	Mozilla
navigator.appVersion	5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2774.3 Safari/537.36 OPR/40.0.2288.0 (Edition developer)
navigator.appMinorVersion	Property is not supported! navigator.appMinorVersion is not a string. It's a undefined
navigator.vendor	Google Inc.
navigator.userAgent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2774.3 Safari/537.36 OPR/40.0.2288.0 (Edition developer) . More info...
navigator.oscpu	Property is not supported! navigator.oscpu is not a string. It's a undefined . More info...
navigator.platform	Linux x86_64
navigator.securityPolicy	Property is not supported! navigator.securityPolicy is not a string. It's a undefined . More info...
navigator.onLine	true . More info...
Info browser.name	chrome
Info browser.version	53.0.2774.3
Info layout.name	webkit
Info layout.version	537.36
Info os.name	linux
Internet Explorer real version	This only works in Microsoft Internet Explorer!
Operating System	Linux/Unix - More info...

--------------------

Accepted Filetypes Information

Test	Result
Accepted Documents	text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8
Accepted Charsets	Not available!
Accepted Encodings	gzip
deflate
lzma
sdch
Accepted Languages	en-US
en;q=0.8

------------------

Screen Information

Test	Result
Width	2560
Height	1600
AvailHeight	1574
AvailWidth	2560
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	24
ColorDepth	24
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

---------------------

Date and Time Information

Test	Result
Time and date	Sat Jul 23 2016 09:53:57 GMT-0400 (EDT)
GMT'ed	Sat, 23 Jul 2016 13:53:57 GMT
Locale String	7/23/2016, 9:53:57 AM
Time-Zone offset	240 minutes
Milliseconds since January 1, 1970	1469282037000
Internet Beat	@ 620
Time on browserspy.dk server	Sat, 23 Jul 2016 08:53:57 -0500
Time on your PC	7/23/2016, 9:53:57 AM
Difference between server and PC time	0 seconds

================================================================================

**Opera Developer 40.0.2296.0**

Browser Information
Shows some of the basic information available in the browser like codename, version, platform and online information.
Test	Result
navigator.appName	Netscape
navigator.appCodeName	Mozilla
navigator.appVersion	5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2783.2 Safari/537.36 OPR/40.0.2296.0 (Edition developer)
navigator.appMinorVersion	Property is not supported! navigator.appMinorVersion is not a string. It's a undefined
navigator.vendor	Google Inc.
navigator.userAgent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2783.2 Safari/537.36 OPR/40.0.2296.0 (Edition developer) . More info...
navigator.oscpu	Property is not supported! navigator.oscpu is not a string. It's a undefined . More info...
navigator.platform	Linux x86_64
navigator.securityPolicy	Property is not supported! navigator.securityPolicy is not a string. It's a undefined . More info...
navigator.onLine	true . More info...
Info browser.name	chrome
Info browser.version	53.0.2783.2
Info layout.name	webkit
Info layout.version	537.36
Info os.name	linux
Internet Explorer real version	This only works in Microsoft Internet Explorer!
Operating System	Linux/Unix - More info...

----------------

Accepted Filetypes Information

Test	Result
Accepted Documents	text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8
Accepted Charsets	Not available!
Accepted Encodings	gzip
deflate
lzma
sdch
Accepted Languages	en-US
en;q=0.8

-------------------------

Screen Information

Test	Result
Width	2560
Height	1600
AvailHeight	1574
AvailWidth	2560
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	24
ColorDepth	24
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

---------------------

Date and Time Information

Test	Result
Time and date	Sat Jul 23 2016 09:58:06 GMT-0400 (EDT)
GMT'ed	Sat, 23 Jul 2016 13:58:06 GMT
Locale String	7/23/2016, 9:58:06 AM
Time-Zone offset	240 minutes
Milliseconds since January 1, 1970	1469282286000
Internet Beat	@ 623
Time on browserspy.dk server	Sat, 23 Jul 2016 08:58:06 -0500
Time on your PC	7/23/2016, 9:58:06 AM
Difference between server and PC time	0 seconds

==============================================================

**Chrome 52.0.2743.82 (64-bit)**

Browser Information
Shows some of the basic information available in the browser like codename, version, platform and online information.
Test	Result
navigator.appName	Netscape
navigator.appCodeName	Mozilla
navigator.appVersion	5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36
navigator.appMinorVersion	Property is not supported! navigator.appMinorVersion is not a string. It's a undefined
navigator.vendor	Google Inc.
navigator.userAgent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36 . More info...
navigator.oscpu	Property is not supported! navigator.oscpu is not a string. It's a undefined . More info...
navigator.platform	Linux x86_64
navigator.securityPolicy	Property is not supported! navigator.securityPolicy is not a string. It's a undefined . More info...
navigator.onLine	true . More info...
Info browser.name	chrome
Info browser.version	52.0.2743.82
Info layout.name	webkit
Info layout.version	537.36
Info os.name	linux
Internet Explorer real version	This only works in Microsoft Internet Explorer!
Operating System	Linux/Unix - More info...

---------------------------

Accepted Filetypes Information

Test	Result
Accepted Documents	text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8
Accepted Charsets	Not available!
Accepted Encodings	gzip
deflate
sdch
Accepted Languages	en-US
en;q=0.8

---------------------------------

Screen Information

Test	Result
Width	2560
Height	1600
AvailHeight	1574
AvailWidth	2560
Normal horizontal dots per inch (DPI)	Property is not supported! screen.deviceXDPI is not a number. It's a undefined
Normal vertical dots per inch (DPI)	Property is not supported! screen.deviceYDPI is not a number. It's a undefined
Actual horizontal dots per inch (DPI)	Property is not supported! screen.logicalXDPI is not a number. It's a undefined
Actual vertical dots per inch (DPI)	Property is not supported! screen.logicalYDPI is not a number. It's a undefined
Full screen window?	Property is not supported! window.fullScreen is not a boolean. It's a undefined
PixelDepth	24
ColorDepth	24
FontSmoothing Enabled	Property is not supported! screen.fontSmoothingEnabled is not a boolean. It's a undefined
BufferDepth	Property not supported or blank!
Update interval	Property is not supported! screen.updateInterval is not a number. It's a undefined

-------------------------------------

Date and Time Information
Find out information about the time and date on your system. See timezone information and see if your system time needs to be fixed.
Test	Result
Time and date	Sat Jul 23 2016 10:00:36 GMT-0400 (EDT)
GMT'ed	Sat, 23 Jul 2016 14:00:36 GMT
Locale String	7/23/2016, 10:00:36 AM
Time-Zone offset	240 minutes
Milliseconds since January 1, 1970	1469282436000
Internet Beat	@ 625
Time on browserspy.dk server	Sat, 23 Jul 2016 09:00:35 -0500
Time on your PC	7/23/2016, 10:00:36 AM
Difference between server and PC time	1 seconds

**Comment by dillbyrne** [comment]
@Copyrites Thanks for these. I have updated Opera profiles added. :+1:
