### ISSUE TITLE
Checkboxes for beacons and link prefetch do not stick but settings do?

### ISSUE THREAD

**Issue by Matvei27** [dillbyrne/random-agent-spoofer#441]
Having a strange issue.
I can disable beacons and link prefetching, but when I restart Firefox those checkmarks disappear.
However, looking in about:config reveals that the settings themselves do stick.
Other add-ons installed are u-block origin, https everywhere, self destructing cookies, and privacy settings.

**Comment by dillbyrne** [comment]
@Matvei27 I have fixed this issue a while back and It will be in the 0.9.5.6 which I am planning on releasing later today.
