### ISSUE TITLE
Spoof Browser Size and Color Depth

### ISSUE THREAD

**Issue by gj12** [dillbyrne/random-agent-spoofer#446]
It would  be nice to have the option to spoof Browser Size and Color Depth. http://www.whatsmybrowser.org/ can show the Size and Depth. You can easily identify a Linux browser by its color depth (24). This could prevent tracking by fingerprinting even more.

**Comment by tramway11** [comment]
Hello, Dill!
How can I contact you by email?

**Comment by dillbyrne** [comment]
@gj12 The addon could do this already until it broke due to changes by mozilla and I have partially fixed it most of the script injection code. I still have to get the window.inner/outer width/height fixed
