### ISSUE TITLE
Disabling and Re-enabling Blows Up Configuration

### ISSUE THREAD

**Issue by Copyrites** [dillbyrne/random-agent-spoofer#451]
It seems that disabling the extension in the about:addons page and then re-enabling it causes most (all?) settings to be reset or at least scrambled.  For example, I configure specific IP addresses for the Spoof Via and Spoof X-Forwarded-For headers, but disabling and re-enabling zeros them out.

**Comment by B00ze64** [comment]
Yup, you are supposed to disable the extension by clicking on "Options" in the addOns list, and unCheck the Enabled? choice. When you disable using the disable button, the addOn tries to bring everything back to Firefox defaults. I don't like it, but I don't think this will change - there is some merit to defaulting settings when the addOn is disabled...

**Comment by bonbonboi** [comment]
I confirm that happened even by "soft" disable aka right-click anywhere > RAS > Disable RAS

**Comment by dillbyrne** [comment]
0.9.5.6 has been released which has fixed the built in RAS toggle system which keeps your selected preferences. It is in the mouse context menu or you can also access it from the RAS preferences in the about:addons page.
