### ISSUE TITLE
[New Feature] Option to NOT show notifications on agent change

### ISSUE THREAD

**Issue by fitdev** [dillbyrne/random-agent-spoofer#455]
When I set profile to some of the random values and set it to change periodically, a notification in the lower right is shown every time a profile is changed. It gets very annoying after a few times. It would be nice if there was an option to turn that notification off.

**Comment by RdKoyoe** [comment]
there is already an option to turn off that notification

**Comment by fitdev** [comment]
Oh really? Where? I just installed the extension yesterday, so have the latest version. Searched extensively in the UI and about:config but found nothing.

**Comment by Arsouf** [comment]
Directly into RAS options in addons list

**Comment by fitdev** [comment]
Thanks so much! SIlly me. Sorry about this
