### ISSUE TITLE
RAS 0.9.5.5 "via" not working on gma.yahoo.com

### ISSUE THREAD

**Issue by ipatjolvur** [dillbyrne/random-agent-spoofer#463]
Firefox 48.0.2
RAS 0.9.5.5

Enable "Spoof Via using a" select "random IP". Go to yahoo.com. Hover over the news headlines to find one that links to the gma.yahoo.com subdomain. Right-click and Open in a New Tab. Firefox times-out with the error:

"The page isn’t redirecting properly. Firefox has detected that the server is redirecting the request for this address in a way that will never complete. This problem can sometimes be caused by disabling or refusing to accept cookies."

Solution:
In the RAS whitelist, add the rule:
`{"url":"gma.yahoo.com","options":["via"]}`

**Comment by ipatjolvur** [comment]
Example:
https://gma.yahoo.com/authorities-high-alert-multiple-explosive-devices-found-nyc-102914938--abc-news-topstories.html

**Comment by dillbyrne** [comment]
That is what the whitelist is for, to try to reduce the problems RAS can cause on various sites. I'll close this as you have solved it.
