### ISSUE TITLE
oscpu work only in Firefox profiles

### ISSUE THREAD

**Issue by malumma** [dillbyrne/random-agent-spoofer#464]
Hello dillbyrne! Thanks for a great job at first!  Unfortunately i find that oscpu feauture works only in Firefox profiles. I try all versions from 0.9.9.3 to 0.9.9.6 (03.09 update) 37.0.1-47.0.1 Firefox and i find this bug..

**Comment by dillbyrne** [comment]
This is not a bug. Only firefox profiles make use of oscpu. Check the real versions of other browsers.
