### ISSUE TITLE
[0.9.5.6] IP-Check displays now my real browser window's resolution

### ISSUE THREAD

**Issue by BananaMangoFestival** [dillbyrne/random-agent-spoofer#467]
First of all, thank you for this update and what it brings.

Yet, I can see on ip-check my real "Browser window" resolution whereas with 0.9.5.5 version, this value was anonymized according to ip-check.

**Comment by dillbyrne** [comment]
@BananaMangoFestival Window spoofing and Date spoofing still have to be reimplemented. I stated this in the release notes. If you were using firefox 45 with 0.9.5.5 then all the script injection features were broken by ff45 . This update fixes most of the script injection code and the rest will be fixed when I get it working.
