### ISSUE TITLE
0.9.5.6 - Exclude Linux Not Sticking

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#472]
Using 0.9.5.6 in Linux with Firefox 45.4.0 ESR two Linux options are not sticking when I check mark to exclude them;

Firefox 51.0 32bit
Firefox 51.0 64 bit

If I restart Firefox they become unchecked.

If I uncheck these two below, I noticed when restarting Firefox they are rechecked;

Firefox 50.0 32bit
Firefox 50.0 64 bit

Hmm

This is on a clean profile of Firefox with no addons installed, only RAS.

**Comment by Geyup** [comment]
I also see a problem in Windows using Firefox 49.0.2

When I checked to exclude all the Windows borwsers (FF 50.0 Win7 WOW64) was unchecked, when I reopened RAS...

**Comment by dillbyrne** [comment]
@Geyup This is a bug with the profile ID's  I have fixed this. Well spotted and thanks for pointing it out.
