### ISSUE TITLE
Why is "disable CSS visited links" still included?

### ISSUE THREAD

**Issue by tzimon** [dillbyrne/random-agent-spoofer#473]
In the wiki it says that the "Disable CSS visited links" option is redundant an needs to be removed, but it still is in the new release. Did you forget it, or is this still an issue?

**Comment by dillbyrne** [comment]
I have read it was fixed https://developer.mozilla.org/en-US/docs/Web/CSS/Privacy_and_the_:visited_selector

but the preference still exists in the latest firefox so there is no harm in leaving it.

https://blog.mozilla.org/security/2010/03/31/plugging-the-css-history-leak/
https://dbaron.org/mozilla/visited-privacy#limits
