### ISSUE TITLE
Random Agent Spoofer does not add an icon to the main toolbar of Firefox

### ISSUE THREAD

**Issue by Bobo8** [dillbyrne/random-agent-spoofer#48]
- I have tried the extension on 2 PC with Win XP (updated), Czech language, Firefox 27 and 28, no other active extension. I have done the FF renewal.
Technical info:

Název: Firefox
Verze: 28.0
Identifikace prohlížeče: Mozilla/5.0 (Windows NT 5.1; rv:28.0) Gecko/20100101 Firefox/28.0

Hlášení o pádech za poslední 3 dny
----------------------------------

Všechna hlášení o pádech

Rozšíření
---------

Název: Random Agent Spoofer
Verze: 0.8.2
Povoleno: true
Id: jid1-AVgCeF1zoVzMjA@jetpack

Název: Java Quick Starter
Verze: 1.0
Povoleno: false
Id: jqs@sun.com

Název: Microsoft .NET Framework Assistant
Verze: 0.0.0
Povoleno: false
Id: {20a82645-c095-46ed-80e3-08825760534b}

Název: Skype Click to Call
Verze: 6.13.0.13771
Povoleno: false
Id: {82AF8DCA-6DE9-405D-BD5E-43525BDAD38A}

Důležité změněné předvolby
--------------------------

browser.cache.disk.capacity: 358400
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.disk.smart_size_cached_value: 296960
browser.places.smartBookmarksVersion: 6
browser.sessionstore.upgradeBackup.latestBuildID: 20140314220517
browser.startup.homepage_override.buildID: 20140314220517
browser.startup.homepage_override.mstone: 28.0
dom.mozApps.used: true
extensions.lastAppVersion: 28.0
network.cookie.prefsMigrated: true
places.database.lastMaintenance: 1397061174
places.history.expiration.transient_current_max_pages: 31060
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.importedState: true
privacy.sanitize.migrateFx3Prefs: true
storage.vacuum.last.index: 0
storage.vacuum.last.places.sqlite: 1397061174

Grafika
-------

Aktivní GPU #2: false
Datum ovladače: 1-31-2013
DirectWrite povolen: false (0.0.0.0)
Grafická akcelerace Windows: 1/1 Direct3D 9
Id výrobce: 0x10de
Id zařízení: 0x016a
Ovladače adaptéru: nv4_disp
Popis adaptéru: NVIDIA GeForce 7100 GS
RAM adaptéru: Unknown
Verze ovladače: 6.14.13.783
windowLayerManagerRemote: false
Zobrazování WebGL: Google Inc. -- ANGLE (NVIDIA GeForce 7100 GS Direct3D9 vs_3_0 ps_3_0)
AzureCanvasBackend: skia
AzureContentBackend: cairo
AzureFallbackCanvasBackend: cairo
AzureSkiaAccelerated: 0

JavaScript
----------

Inkrementální GC: true

Přístupnost
-----------

Aktivována: false
Zakázána: 0

Verze knihoven
--------------

NSPR
Očekávaná minimální verze: 4.10.3
Používaná verze: 4.10.3

NSS
Očekávaná minimální verze: 3.15.5 Basic ECC
Používaná verze: 3.15.5 Basic ECC

NSSSMIME
Očekávaná minimální verze: 3.15.5 Basic ECC
Používaná verze: 3.15.5 Basic ECC

NSSSSL
Očekávaná minimální verze: 3.15.5 Basic ECC
Používaná verze: 3.15.5 Basic ECC

NSSUTIL
Očekávaná minimální verze: 3.15.5
Používaná verze: 3.15.5

**Comment by dillbyrne** [comment]
@Bobo8 can you try https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.0 and tell me if it fixes your problem. I will close this issue in a few weeks if there is no response by then. Thanks

**Comment by k-h** [comment]
The new one works for me. The ability to block canvas and limit font lists is excellent.

On 2015/Jan/14, at 7:48 AM, dillbyrne wrote:

> @Bobo8 can you try https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.0 and tell me if it fixes your problem. I will close this issue in a few weeks if there is no response by then. Thanks 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dillbyrne/random-agent-spoofer/issues/48#issuecomment-69816887

-- 
Kim Holburn
IT Network & Security Consultant
T: +61 2 61402408  M: +61 404072753
mailto:kim@holburn.net  aim://kimholburn
skype://kholburn - PGP Public Key on request

**Comment by dillbyrne** [comment]
@k-h That is great to know thanks. I'm glad you like it.

**Comment by Bobo8** [comment]
Sorry for not responding, I didn't use Firefox for long time (I used Opera, but now I move to Firefox). Now it is OK, I have your icon in toolbar. I didn't change anything, then I think, that new version helped.

**Comment by dillbyrne** [comment]
@Bobo8 Good to know thanks.

**Comment by mack318** [comment]
one of my favorite add ons.
tried to add it to the new developer addition of Firefox.  The icon does not appear.
it might be helpful if there was an alt settings button inside the add on manager.  Without the icon there is no way to adjust the settings.
Im running win 8 64bit
Firefox developer edition 40.0a2  (2015-06-08)

**Comment by dillbyrne** [comment]
@mack318 If an issue is closed please make a new issue to deal with your query. I have made a new issue for your query https://github.com/dillbyrne/random-agent-spoofer/issues/240
