### ISSUE TITLE
random  agent  spoofer   0.9.5.6

### ISSUE THREAD

**Issue by frankflash9** [dillbyrne/random-agent-spoofer#482]
When  spoof  in none - match  Etags is turn on 
is block to much of the site   www.newstalkzb.co.nz

firefox 49.01  64 bit  
![newstalkzb co nz](https://cloud.githubusercontent.com/assets/22673806/19261958/dbebe9b8-8ff0-11e6-92a8-07cae1544956.PNG)

**Comment by forkoz** [comment]
Breaks a bunch of forums too. Thanks for letting me know which setting it was.

**Comment by frankflash9** [comment]
very slow at fixing this useless
