### ISSUE TITLE
Profile > Change periodically: Every Request - Major Notification Flooding!

### ISSUE THREAD

**Issue by Geyup** [dillbyrne/random-agent-spoofer#485]
For the Profile, when set to Change periodically: E very Request, this generates massive amounts of popups that fill up the entire desktop. This really needs to be fixed, otherwise this is not a very beneficial option, needing to wait on the flood of popup notifications to clear the desktop before you are able to browse again.

Please see the attached screen shot to see what I mean happens when you enable this feature.

![requests](https://cloud.githubusercontent.com/assets/13072581/19422281/8ee3e32c-9401-11e6-8f1f-ccd341bc9ed4.jpg)

**Comment by Geyup** [comment]
I don't understand why anyone would want such a feature, the idea of having a different profile is to mask the OS you are using, and to make it look like a legitimate request. When you enable something like this, with mass amounts of request changes, you do not look like a legitimate OS, no one can use 
multiple systems at one time like this.

This makes a person stand out from the crowd and greater fingerprinting, making you an easy target.

I do not see the point at all to this feature...

**Comment by geeknik** [comment]
It's a perfectly useful feature if every request you're making comes from a different IP address. Of course not everyone is going to have the resources for that sort of setup, but some of us do.

**Comment by Geyup** [comment]
@geeknik are you saying when you load a page, you're going to have it load using 15 different IP addresses as example and 15 differenet RAS profiles?

**Comment by geeknik** [comment]
Yes. I have a proxy that can bounce each browser request off of a network of upstream proxy servers spread around the globe. It's faster than Tor and to whichever website I'm visiting, they'll just see IP1 requesting / and IP2 request /logo.png and IP3 requesting /site.css and so on and so forth.

**Comment by Wannabe-Programmer** [comment]
@Geyup Go to about:addons click the extensions tab, find RAS and click options. Scroll down the bottom and uncheck show notifications.

Problem solved.

**Comment by Geyup** [comment]
@Wannabe-Programmer thanks...

@geeknik any special service that provides you these proxies you're using?
