### ISSUE TITLE
Conflicts with Gmail in Firefox

### ISSUE THREAD

**Issue by thegrackle** [dillbyrne/random-agent-spoofer#487]
When RAS is enabled, I cannot type anything in the quick reply box in my emails in Gmail. The cursor won't move.

**Comment by I-Heart-Unicorns** [comment]
I was experiencing the same problem with RAS where if my profile was set to anything other than my real profile (Firefox/Ubuntu) then I couldn't compose emails in Gmail, I couldn't reply to emails in Gmail, and I couldn't search my emails using the Gmail search box. If I tried to type anything in the compose/reply/search text boxes no text appeared and the text cursor didn't move.
If I switch to my real profile (Firefox/Ubuntu) and refresh the page (which logs me into Gmail again), Gmail works fine. Have you tried switching to your real profile when logging into Gmail?
I use Firefox 49.0 on Ubuntu 16.04 LTS (Xenial Xerus).
I'm not sure if this is an issue with RAS or Firefox or Gmail.
I've also emailed Firefox & Gmail about this.

**Comment by thegrackle** [comment]
Thanks, I wasn't aware of that and never looked in the options before. One question, if you set it to 'real profile', then is it still even 'spoofing'?  I thought the whole purpose was to randomize your browser profile.

**Comment by icasdri** [comment]
I believe if you set "Real Profile" it no longer spoofs. Maybe RAS should add an button to manually rotate profiles (on demand), as this sounds like it's due to Gmail serving different versions of the site per-browser with potentially browser-specific code.

**Comment by thegrackle** [comment]
Or maybe an option to disable the spoofing on a per domain basis. Not sure if that would even be feasible.

**Comment by icasdri** [comment]
@thegrackle Isn't per-domain disabling the Whitelisting feature? I feel that disabling spoofing altogether in these cases is overkill as it needlessly disables other RAS protections (like script injection options, etc.). It seems to only be a user-agent issue.

**Comment by thegrackle** [comment]
I just set the profile back to random, and then added mail.google.com to the whitelist, and now gmail doesn't seem to be experiencing the same problems, so I guess that is a solution. thanks everyone.

**Comment by thegrackle** [comment]
I guess I will close the issue.
