### ISSUE TITLE
random profile notification popup

### ISSUE THREAD

**Issue by sfzombie13** [dillbyrne/random-agent-spoofer#493]
first off, thanx a bunch for this great tool, i have used it for a while now.  second, this isn't really a problem per se, just something that bugs me.  whenever the profile changes when it is set to random, a box pops up telling me that.  it is just annoying to me and distracting sometimes.  i looked for an option to turn it off, but didn't see one.  as there seems to be no reports of it, it looks like it isn't much of a problem to anyone else either.  i am going to look through the source code to see if it is something i may be able to fix myself, and if it is, i will send it to you and save you the time and trouble of fixing it.  again, thanx for sharing this with us.

**Comment by icasdri** [comment]
See #491. Unfortunately, the option is kinda hard to find.

**Comment by sfzombie13** [comment]
Sorry about that, looks like it is quite popular though.  Maybe having
it disabled by default so that people don't start looking for how to
turn it off.  Thanx so much for the great tool.  You are doing a hell
of a job.
-- 
Tim Sayre
Kanawha IT Security <http://kitswv.com>

**Comment by dillbyrne** [comment]
I plan to move the option to the options tab for the next release, as the issue keeps popping up
