### ISSUE TITLE
Ramdom IP spofing, dont have range

### ISSUE THREAD

**Issue by Carlosggmm** [dillbyrne/random-agent-spoofer#494]
Ramdom IP spofing, Dont let select range of ip's, only ramdom and unique, I need a range of USA ip's only for example, from 11.11.11.11 to 70.70.70.70 its ok

**Comment by FoxMiner** [comment]
If you also could change on every request, it would be the perfect

**Comment by DrunkenSasquatch** [comment]
Duplicate of #409

**Comment by dillbyrne** [comment]
closing as duplicate . It will be dealt with in #409 . Please use the search function in future. Thanks
