### ISSUE TITLE
spoofing, mac address?

### ISSUE THREAD

**Issue by FoxMiner** [dillbyrne/random-agent-spoofer#495]
it would be possible to add an option to spoofing mac address?

**Comment by DrunkenSasquatch** [comment]
@FoxMiner  - Mac spoofing is done on the operating system level, so websites are not able to retrieve this information. You should also understand that Mac addresses are to uniquely identify each node on the local network, this information does not leave the local network.

This is not a browser fingerprinting vector nor does it relate in anyway.

**Comment by FoxMiner** [comment]
if is possible get mac address with JavaScript.
https://github.com/bevry/getmac

**Comment by DrunkenSasquatch** [comment]
@FoxMiner - You are either....

1. Spreading Disinformation
2. Genuinely have no idea what you're talking about.

Please read these articles ([1](https://superuser.com/questions/653554/mac-address-when-visiting-a-website-does-the-web-see-that), [2](https://superuser.com/questions/802421/can-a-website-see-know-my-mac-address-even-if-i-use-a-vpn)). I did not say that it's possible for plugins to retrieve your mac address, I said that websites <b>DO NOT</b> have this ability using only JavaScript.

**Comment by dillbyrne** [comment]
Closing as it is beyond the scope of an addon.

To spoof your mac address use macchanger on linux. Something probably exists for windows too if you use that.

`macchanger` - utility for manipulating the MAC address of network interfaces
`macchanger-gtk` - a GTK+ interface for GNU/MACchanger

**Comment by FoxMiner** [comment]
I understand that the problem is that it is impossible to do mac spoofing
The mac address is obtained directly from the pc using cmd getmac and the only way is changing in windows
