### ISSUE TITLE
V.1.8.9  Timezone Spoofing Missing

### ISSUE THREAD

**Issue by FireRooster** [dillbyrne/random-agent-spoofer#498]
Shows in Manager; not in Options. Still a great add-on. Thank you.

**Comment by dillbyrne** [comment]
There is no version 1.8.9 ?. Where did you download it from. Script injection was broken with the release of ff45 I have managed to restore the majority of the features that broke but I have not yet managed to get timezone spoofing working. It will be added back when I get it working
