### ISSUE TITLE
Adding regexp expansions to white list

### ISSUE THREAD

**Issue by trog-levrai** [dillbyrne/random-agent-spoofer#502]
Disabling canvas was also disabling PDF.js... So I decided to implement regexp expansions for the whitelist to be able to whitelist all PDF files.

I thought we would discuss the matter on the pull request page but since nothing happened I think I'm better open this issue.

The pull request is #490. I'd be glad to discuss the matter and modify the pull request if it is necessary !

**Comment by dillbyrne** [comment]
Closing this as I've commented on the PR directly. Thanks
