### ISSUE TITLE
'Disable Referer' breaks shit

### ISSUE THREAD

**Issue by rhazor** [dillbyrne/random-agent-spoofer#503]
Reproduce:
1. Tick 'Disable referer' under Headers tab
2. E.g. to to Reddit and look for posts that contain embedded Imgur gallery/images (that's what it breaks)

Example link given:
https://www.reddit.com/r/pathofexile/comments/5dy7mk/fishing_ring_what_zoom_in/

![untitled-1](https://cloud.githubusercontent.com/assets/22996586/20483579/63c25622-affb-11e6-85ec-3de9f64e32ed.jpg)

Also if it helps, same happens with some outdated addon '[Smart Referer](https://addons.mozilla.org/en-US/firefox/addon/smart-referer/)' on Firefox

**Comment by dillbyrne** [comment]
I'm not seeing this with RAS only or with a clean firefox with no addons. 

Anyway RAS by its very nature is going to break some sites. Use the whitelist with the referer option, try one of the referer spoofing options or don't disable it.

https://github.com/dillbyrne/random-agent-spoofer/wiki/Whitelist-Tab-Usage
