### ISSUE TITLE
Is it possible to spoof the fonts detected by CSS and Javascript to match a selected profile?

### ISSUE THREAD

**Issue by DrunkenSasquatch** [dillbyrne/random-agent-spoofer#512]
I have noticed the current implementation of limiting detectable fonts uses the Firefox preference `browser.display.use_document_fonts`. However, is it possible to add a profile attribute to `useragents.json` for specific fonts to be used when the user selects a specific user agent?

Using BrowserLeaks, I was able to retrieve the available fonts used by Safari on iOS 9.3.5. Here are the results: 
```
Symbol 	
Arial 	
Courier New 	
Georgia 	
Trebuchet MS 	
Verdana 	
Courier 	
Arial Unicode MS 	
Simplified Arabic 	
Simplified Arabic Fixed 	
Traditional Arabic 	
Arabic Typesetting 	
Papyrus 	
Arial Rounded MT Bold 	
Arabic Transparent 	
Adobe Arabic 	
Myriad Arabic 	
WP ArabicScript Sihafa 	
WP Arabic Sihafa 	
Helvetica
```

Is it possible to add these to a matching profile via script injection? 
How complex would this be to implement and what are the side effects?

**Comment by PatSpiegel** [comment]
just connect css file
`@font-face {
font-family: 'Shaurma Font of World';
src: local('Arial');
font-style: normal;
}`

**Comment by Pydis** [comment]
It looks like new methodology is implemented in font fingerprint https://browserleaks.com/fonts

JS Fonts (unicode)
JS Fonts (classic) 
It is detected for me: 6 fonts and 8 unique metrics found in the list of 512 fonts

**Comment by DrunkenSasquatch** [comment]
Good News for [Firefox](http://www.ghacks.net/2016/12/28/firefox-52-better-font-fingerprinting-protection/)

Just create a new parameter in `about:config` and name it `font.system.whitelist`. Then add the fonts separated by a comma. We could easily implement this in `useragents.json`.

**Comment by anatoli26** [comment]
Will that be done? At this time if I check "Limit detectable fonts", I get visualization problems on a lot of pages (most basic fonts are used instead of the intended ones)
