### ISSUE TITLE
Add support for screen size and window offsets in the profiles

### ISSUE THREAD

**Issue by dillbyrne** [dillbyrne/random-agent-spoofer#54]
In addition to the current random screen size option that exists as of 0.9.2. Screen sizes should also be added to the profiles so that they match the real devices values to allow users to blend in better. 

Examples of this are Iphones and tablets where the sizes are all the same for each device type.

Also color and pixel depth values need to be added too.

**Comment by deqoksijnc** [comment]
For desktop it would seem that fullScreen would still be the "least fingerprintable" option? Luckily a large enough share of users run their browsers in fullScreen.

Afaics maximised windows suffer from highly configuration specific window decoration size so they will offer much more fingerprinting opportunities.

Changing (spoofed) window size and offsets randomly might also work, but if the remote fingerprinter can observe such changes (cookie not deleted or other fingerprinting) it might reveal to him that something interesting is going on.

**Comment by dillbyrne** [comment]
I doubt very many people run in fullscreen all the time but I will add an option and you can check it if you wish.

>Afaics maximised windows suffer from highly configuration specific window decoration size so they will offer much more fingerprinting opportunities.

This issue when completed should account for the various browser and system toolbars.
 
>Changing (spoofed) window size and offsets randomly might also work, but if the remote fingerprinter can observe such changes (cookie not deleted or other fingerprinting) it might reveal to him that something interesting is going on.

currently they are set per request and if the random or profile option is selected it will change for each request .  This is assuming that the available different screen sizes for the current profile are more than 1. So not an iphone which has a single size where as a desktop can have multiple screen sizes.

**Comment by dillbyrne** [comment]
investigate CSS screen detection http://www.imamasim.com/cli/css3.htm
