### ISSUE TITLE
Disable webRTC doesn't work

### ISSUE THREAD

**Issue by AdamFo** [dillbyrne/random-agent-spoofer#569]
According to whoer.net "Disable webRTC" option doesn't work in RAS, when with "Disable WebRTC" plugin it does work.

**Comment by Atavic** [comment]
How to [disable WebRTC](https://privacytoolsio.github.io/privacytools.io/#webrtc) in Firefox?

[ghacks-user.js](https://github.com/ghacksuserjs/ghacks-user.js) section 2000: MEDIA / CAMERA / MIC

```
user_pref("media.peerconnection.enabled", false);
user_pref("media.peerconnection.use_document_iceservers", false);
user_pref("media.peerconnection.video.enabled", false);
user_pref("media.peerconnection.identity.enabled", false);
user_pref("media.peerconnection.identity.timeout", 1);
user_pref("media.peerconnection.turn.disable", true);
user_pref("media.peerconnection.ice.tcp", false);
user_pref("media.navigator.video.enabled", false); // video capability for WebRTC
```

Also related is Section 1840.
