### ISSUE TITLE
Will it be ported to web-extensions?

### ISSUE THREAD

**Issue by desputinski** [dillbyrne/random-agent-spoofer#579]
Hi, I think soon the random agend spoofer will be outdated when Firefox-Webextensions are going to be activated. Will the Plugin be ported?

**Comment by dillbyrne** [comment]
I have no plans to port it as I no longer have the time and the web extensions api is quite restrictive. Others are free to fork and do so if they wish

**Comment by gitressa** [comment]
Perhaps use https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/ in stead?

**Comment by sheddup** [comment]
@gitressa lacking all the other features of RAS

**Comment by desputinski** [comment]
Thanks user agent switcher is all right.
