### ISSUE TITLE
Icon remains always black 

### ISSUE THREAD

**Issue by Lucie235** [dillbyrne/random-agent-spoofer#58]
FF 29.0.1 crashes frequently with RAS enabled. Since last crash today RAS icon remains black and cannot be right clicked, so RAS switched on or off is no longer easyly to see.

Uninstalling and re-installing RAS didn't help. Restart FF changes nothing.

Installed addons:

Adblock plus 2.6.3
BetterPrivacy 1.68
FlashGot 1.5.5.98
Google Translator 2.1.0.3
HTTPS-Everywhere 3.5.1
Dict.Leo 0.5
NoScript 2.6.8.28
RAS 0.8.2
Tabs on Bottom 0.5

OS is XP prof SP3

**Comment by dillbyrne** [comment]
@Lucie235 can you try https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.0 and tell me if it fixes your problem. I will close this issue in a few weeks if there is no response by then. Thanks

**Comment by Lucie235** [comment]
Hi dillbyrne,

thanks so much, 0.9.5.0 seems so solve the prob!

Also billyboy1's hint has been true, he wrote:

"i've the same issue concerning the black icon but it's seems that 
BetterPrivacy 1.68 is the culprit because if i deactivate it, RAS icon 
work as expected."

Am 13.01.2015 um 21:48 schrieb dillbyrne:
>
> @Lucie235 <https://github.com/Lucie235> can you try 
> https://github.com/dillbyrne/random-agent-spoofer/releases/tag/0.9.5.0 
> and tell me if it fixes your problem. I will close this issue in a few 
> weeks if there is no response by then. Thanks
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dillbyrne/random-agent-spoofer/issues/58#issuecomment-69816971>.
>


--

**Comment by dillbyrne** [comment]
@Lucie235 That is good to know. Thanks
