### ISSUE TITLE
FF57's new api?  

### ISSUE THREAD

**Issue by nyancat18** [dillbyrne/random-agent-spoofer#581]
What had planned RAS for the new api? 
mozilla said that after firefox 59 addons with the old api may be blocked

**Comment by dillbyrne** [comment]
I have no plans to port RAS and even if I did, it would lose many options as the WE API does will not support changing internal browser preferences like about:config. Also I no longer have enough time to devote to it as I once did. 

Anyone is free to fork it and try a WE version. I have personally moved to the brave browser which has anti fingerprinting built in
