### ISSUE TITLE
Improve language header support

### ISSUE THREAD

**Issue by dillbyrne** [dillbyrne/random-agent-spoofer#67]
Currently only US english is supported.  Add support for more languages in the correct string format to match the target browsers in the same way the current option is implemented

I only want to add locales supported by all browsers. 

Lists of locales
http://www.karakas-online.de/forum/viewtopic.php?t=858
http://www.roseindia.net/tutorials/I18N/locales-list.shtml

Firefox locales
https://www.mozilla.org/en-US/firefox/all/

Chrome web store (I need to confirm for the actual browser) 
https://developer.chrome.com/webstore/i18n?csw=1#localeTable 

Opera
http://www.opera.com/download/languagefiles/

Safari

InternetExplorer

http://blogs.msdn.com/b/ie/archive/2006/10/17/accept-language-header-for-internet-explorer-7.aspx (Accept header changes from IE6 to IE7)

http://msdn.microsoft.com/en-us/library/ms533052%28v=vs.85%29.aspx ( out of date)

http://download.microsoft.com/download/9/5/E/95EF66AF-9026-4BB0-A41D-A4F81802D92C/Windows_Protocols.zip

**Comment by seli11** [comment]
this is for firefox albanian language,you mean only for my country? or to download all versions language of firefox,chrome,opera,internet explorer, and install for acepted languages, i will do if necessary.
but if i disable flash player, canvas fingerprinting can detect me!  ihave disbled flash,  i have changed profile to opera, or chrome,  youtube can detect me anyway https://www.browserleaks.com/canvas     i cant disable flash player and canvas same time,  :)  

Accepted Documents 	text/html
application/xhtml+xml
application/xml;q=0.9
*/*;q=0.8
Accepted Charsets 	Not available!
Accepted Encodings 	gzip
deflate
Accepted Languages 	sq
sq-AL;q=0.8
en-us;q=0.5
en;q=0.3

**Comment by dillbyrne** [comment]
@seli11 Basically I need one version of each of the main desktop browsers. So the default Albanian download of firefox, chrome, opera and safari.  

The mobile versions are a bit trickier as they can change depending on the device so I will need to find each language type for each device.

I will address your canvas comment in the other issue.

**Comment by seli11** [comment]
for chrome 39.0.2171.95 

Accepted Documents
text/html
application/xhtml+xml
application/xml;q=0.9
image/webp
*/*;q=0.8

Accepted Charsets	   Not available!

Accepted Encodings	
gzip
deflate
sdch

Accepted Languages	
en-US
en;q=0.8
sq;q=0.6

**Comment by dillbyrne** [comment]
@seli11 I now have the code in place to support multiple accept language choices, it will fall back to the US english if there is no option for the chosen language  in the current  profile's accept language attribute ,which is an array of name value pairs.

I will add the chrome and firefox to the existing list of language headers.

Can you provide me with the Albanian accept language headers for the opera browser and IE ? and any mobile devices you have

**Comment by dillbyrne** [comment]
Since this has been implemented and no one has responded with accept language headers for other browsers I am closing this. The functionality is done so users only need to submit the default accept language headers for browsers downloaded in their country. E.g the default IE accept language header in Russia or the Default Chrome header in Brazil

**Comment by grotego** [comment]
FireFox 51.0.1 (32-bits) Dutch

Accepted Documents 	

text/html
application/xhtml+xml
application/xml;q=0.9
*/*;q=0.8

Accepted Charsets

Not available!

Accepted Encodings

gzip
deflate

Accepted Languages

nl
en-US;q=0.7
en;q=0.3
