### ISSUE TITLE
Html5 Canvas Fingerprinting

### ISSUE THREAD

**Issue by mt2012** [dillbyrne/random-agent-spoofer#74]
Problem:
http://www.browserleaks.com/canvas

Solution:
turn off "hardware acceleration" by default
(this is the only solution i tried, any other ways how to randomize this value?)

P.S. Thanks for the last 0.9.3 github version, its the greatest addon to break browserfingerprinting at the moment. anyway do you know the reason behind mozilla reviewer do not allow screen & timezone modifications?

What I'm scare is mozilla doing this because instructed by google:
if big companies feel that one browser is blocking their fingerprinting techniques they can just easily blocked all access by this browser. User will feel it is browser's bug then change to another browser. It happens with opera once (the best privacy company that time). This opera browser was growing fastly couple years ago and it becoming a threat for google chrome growth, so google blocked all access to most google service by opera browser then recommend big 3 browser instead.

http://dev.opera.com/blog/google-browser-sniffing-and-the-open-web/

Now what happens? opera becomes google's bootlicker. Now they agree whatever google wants them to do. See all opera browser you will notice many google product is there now. Even opera now uses Google's Blink as their engine.

**Comment by seli11** [comment]
with canvasblocker option fake readout api looks diferent every time refresh the page
https://www.browserleaks.com/canvas
1-Your Fingerprint
Signature	3AE7F9BE
Found in DB	× False
General Conclusion	Your system fingerprint appears to be unique, yet we don't collect signatures here, just check.


2-Signature	56E16BF7
Found in DB	× False
General Conclusion	Your system fingerprint appears to be unique, yet we don't collect signatures here, just check.
----------------------------------------------------
can't read about my operating system or browser detail

**Comment by dillbyrne** [comment]
@seli11 which version of RAS are you using. The mozilla version has no support for canvas blocking only the github version. 

In the github version there is an extra's option to disable the canvas
![extras](https://cloud.githubusercontent.com/assets/2903711/5685418/e2a9bbb2-9831-11e4-9168-fb4be2b584da.png)

When that option is checked you should see the following output on the canvas test
![canvas_temp](https://cloud.githubusercontent.com/assets/2903711/5685423/f3269fbe-9831-11e4-8c74-8d6e88a217d1.png)

**Comment by seli11** [comment]
i make some tests with youtube and i have disabled flash player, because can not spof flash player, but canvas is easier to spof, (my idea) :),  and this plugin 
https://addons.mozilla.org/en-US/firefox/addon/canvasblocker  has option 'fake readout api'  
 in this site http://www.propublica.org/article/meet-the-online-tracking-device-that-is-virtually-impossible-to-block   with canvasblocker addon 'fake readout api'  every time do refresh he Give me another id ;), i mean it's god,
my idea is to change my id of pc like another person with vpn, user agent, and other things,  google and youtube has changed the security for the unemployed :),
 im waiting new  version of random user agent for extra options

**Comment by danielcra** [comment]
Actually the page at https://www.browserleaks.com/canvas sometimes shows a fingerprint and sometimes it doesn't, depending on how I load it (retry several times: bookmark, menu at bottom left, reload in browser). I did clear my browser cache ;-)
My settings are: canvas, webgl, webrtc disabled, the rest left to default.
Whitelist: youtube.com

**Comment by dillbyrne** [comment]
@danielcra I need you to test a fix in #121

@seli11 Like I said above I plan to improve the fingerprinting support. I need to address other issues before I can get to this such as plugins. @seli11 if ras fingerprinting blocking is not working post in #121 not here thanks
