### ISSUE TITLE
HTTP Referer 

### ISSUE THREAD

**Issue by DarKWinGTM** [dillbyrne/random-agent-spoofer#89]
- When this functions will be available ?
- In this option " Change random profile on time interval " we need more choice " Change : Per enter web "

**Comment by louipc** [comment]
There is a nice plugin here too: https://github.com/muzuiget/referrer_control

**Comment by QuasarX** [comment]
**This extension not working, not change referer.**
https://github.com/muzuiget/referrer_control

https://addons.mozilla.org/en-US/firefox/addon/refcontrol/
This not good, only changing referer per site, **we really need change referer per site link.**
**Site:** http://www.A.com/1   =>  **Referer:** www.google.com
**Site:** http://www.A.com/2   =>  **Referer:** www.yahoo.com

**Comment by dillbyrne** [comment]
@QuasarX  

For now Ras can only allow or deny the referer header. Improvements will come in an update and can be tracked in issue #110 

I'm closing this issue as the original author  has not responded back in months
