### ISSUE TITLE
Update / Finish the user manual in the wiki 

### ISSUE THREAD

**Issue by dillbyrne** [dillbyrne/random-agent-spoofer#93]

**Comment by SPOTBEAM** [comment]
Please add descriptions of new features added such as disable battery/gamepad api etc.
Please update "Use standard font set" to "Use document fonts". Maybe a visual aid can find some place as well:
Before -  ![Before](https://i.imgur.com/myQmrNg.jpg)
After -  ![After](https://i.imgur.com/BykAjkj.jpg)

**Comment by dillbyrne** [comment]
Hello @SPOTBEAM 

Thanks for the suggestions. I'll update the wiki soon.
