### ISSUE TITLE
Batterly level spoofing

### ISSUE THREAD

**Issue by wrzhouse** [dillbyrne/random-agent-spoofer#99]
There is a way to get battery level remotely, as well as charging status.
It would be nice to add an option to disable battery level output AND to randomly spoof the value.

http://davidwalsh.name/demo/battery-api.php
http://codepen.io/matt-west/details/vIwra

**Comment by dillbyrne** [comment]
@wrzhouse I added options a while back to disable the battery and gamepad API's. So I'm going to close this now.
